package defpackage;

import java.util.List;

/* renamed from: e00, reason: case insensitive filesystem */
/* loaded from: classes.dex */
public abstract class AbstractC19579e00 {
    public static final List a = AbstractC43165ve3.Y("TEST_APP_START_CONFIG_KEY", "MAX_IO_CONCURRENT_TASKS", "IO_THREAD_POOL_PRIORITY", "SNAP_PRIORITY_QUEUE_CONFIG", "UI_BG_THREAD_POOL_SIZE_MULTIPLIER", "CPU_THREAD_POOL_SIZE_MULTIPLIER", "DB_QUERIES_THREAD_POOL_SIZE", "CPU_THREAD_POOL_PRIORITY", "IDLE_SCHEDULER_USE_CPU_POOL", "UI_BG_SCHEDULER_USE_CPU_POOL", "BLIZZARD_SCHEDULER_ENABLED", "BLIZZARD_THREAD_POOL_SIZE", "BLIZZARD_THREAD_PRIORITY", "SNAP_SCHEDULERS_USE_ASER_V2", "ASERV2_SANITY_CHECK");
}
