package defpackage;

import org.json.JSONObject;

/* renamed from: m5k, reason: case insensitive filesystem */
/* loaded from: classes2.dex */
public final class C30403m5k {
    public char[] A;
    public char[] B;
    public char[] C;
    public int D;
    public int E;
    public char[] F;
    public int G;
    public int H;
    public int I;

    /* renamed from: J, reason: collision with root package name */
    public char[] f15896J;
    public char[] K;
    public int L;
    public char[] M;
    public char[] N;
    public char[] O;
    public int P;
    public int Q;
    public char[] R;
    public int S;
    public char[] T;
    public int U;
    public int V;
    public char[] W;
    public int X;
    public char[] Y;
    public char[] Z;
    public int a;
    public int a0;
    public int b;
    public int b0;
    public int c;
    public int c0;
    public int d;
    public int d0;
    public char[] e;
    public int e0;
    public int f;
    public char[] g;
    public char[] h;
    public char[] i;
    public char[] j;
    public char[] k;
    public char[] l;
    public char[] m;
    public char[] n;
    public char[] o;
    public char[] p;
    public int q;
    public int r;
    public int s;
    public char[] t;
    public char[] u;
    public char[] v;
    public int w;
    public char[] x;
    public char[] y;
    public char[] z;

    public final JSONObject a() {
        JSONObject jSONObject = new JSONObject();
        jSONObject.putOpt("AccelerometerRotation", Integer.valueOf(this.a));
        jSONObject.putOpt("BluetoothDiscoverability", Integer.valueOf(this.b));
        jSONObject.putOpt("BluetoothDiscoverabilityTimeout", Integer.valueOf(this.c));
        jSONObject.putOpt("DateFormat", String.valueOf(this.d));
        jSONObject.putOpt("DtmfToneWhenDialing", AbstractC31740n5k.c(this.e));
        jSONObject.putOpt("EndButtonBehavior", String.valueOf(this.f));
        jSONObject.putOpt("FontScale", AbstractC31740n5k.c(this.g));
        jSONObject.putOpt("HapticFeedbackEnabled", AbstractC31740n5k.c(this.h));
        jSONObject.putOpt("ModeRingerStreamsAffected", AbstractC31740n5k.c(this.i));
        jSONObject.putOpt("NotificationSound", AbstractC31740n5k.c(this.j));
        jSONObject.putOpt("MuteStreamsAffected", AbstractC31740n5k.c(this.k));
        jSONObject.putOpt("Ringtone", AbstractC31740n5k.c(this.l));
        jSONObject.putOpt("ScreenBrightness", AbstractC31740n5k.c(this.m));
        jSONObject.putOpt("ScreenBrightnessMode", AbstractC31740n5k.c(this.n));
        jSONObject.putOpt("ScreenOffTimeout", AbstractC31740n5k.c(this.o));
        jSONObject.putOpt("SoundEffectsEnabled", AbstractC31740n5k.c(this.p));
        jSONObject.putOpt("TextAutoCaps", String.valueOf(this.q));
        jSONObject.putOpt("TextAutoPunctuate", Integer.valueOf(this.r));
        jSONObject.putOpt("TextAutoReplace", String.valueOf(this.s));
        jSONObject.putOpt("TextShowPassword", AbstractC31740n5k.c(this.t));
        jSONObject.putOpt("Time1224", AbstractC31740n5k.c(this.u));
        jSONObject.putOpt("UserRotation", AbstractC31740n5k.c(this.v));
        jSONObject.putOpt("VibrateOn", String.valueOf(this.w));
        jSONObject.putOpt("VibrateWhenRinging", AbstractC31740n5k.c(this.x));
        jSONObject.putOpt("DtmfToneTypeWhenDialing", AbstractC31740n5k.c(this.y));
        jSONObject.putOpt("AccessibilityEnabled", AbstractC31740n5k.c(this.z));
        jSONObject.putOpt("AccessibilitySpeakPassword", AbstractC31740n5k.c(this.A));
        jSONObject.putOpt("AllowedGeolocationOrigins", AbstractC31740n5k.c(this.B));
        jSONObject.putOpt("DefaultInputMethod", AbstractC31740n5k.c(this.C));
        jSONObject.putOpt("InputMethodSelectorVisibility", String.valueOf(this.D));
        jSONObject.putOpt("EnabledInputMethods", String.valueOf(this.E));
        jSONObject.putOpt("InstallNonMarketApps", AbstractC31740n5k.c(this.F));
        jSONObject.putOpt("TtsDefaultRate", String.valueOf(this.G));
        jSONObject.putOpt("TtsDefaultSynth", String.valueOf(this.H));
        jSONObject.putOpt("TtsEnabledPlugins", String.valueOf(this.I));
        jSONObject.putOpt("AdbEnabled", AbstractC31740n5k.c(this.f15896J));
        jSONObject.putOpt("AirplaneModeRadios", AbstractC31740n5k.c(this.K));
        jSONObject.putOpt("AlwaysFinishActivities", String.valueOf(this.L));
        jSONObject.putOpt("AutoTime", AbstractC31740n5k.c(this.M));
        jSONObject.putOpt("AutoTimeZone", AbstractC31740n5k.c(this.N));
        jSONObject.putOpt("DevelopmentSettingsEnabled", AbstractC31740n5k.c(this.O));
        jSONObject.putOpt("HttpProxy", String.valueOf(this.P));
        jSONObject.putOpt("NetworkPreference", String.valueOf(this.Q));
        jSONObject.putOpt("StayOnWhilePluggedIn", AbstractC31740n5k.c(this.R));
        jSONObject.putOpt("TransitionAnimationScale", Integer.valueOf(this.S));
        jSONObject.putOpt("UsbMassStorageEnabled", AbstractC31740n5k.c(this.T));
        jSONObject.putOpt("UseGoogleMail", String.valueOf(this.U));
        jSONObject.putOpt("WaitForDebugger", String.valueOf(this.V));
        jSONObject.putOpt("WifiNetworksAvailableNotificationOn", AbstractC31740n5k.c(this.W));
        jSONObject.putOpt("AnimatorDurationScale", String.valueOf(this.X));
        jSONObject.putOpt("DataRoaming", AbstractC31740n5k.c(this.Y));
        jSONObject.putOpt("DeviceProvisioned", AbstractC31740n5k.c(this.Z));
        jSONObject.putOpt("TtsDefaultPitch", String.valueOf(this.a0));
        jSONObject.putOpt("SysPropSettingVersion", AbstractC31740n5k.c(null));
        jSONObject.putOpt("SkipFirstUseHints", String.valueOf(this.b0));
        jSONObject.putOpt("EnabledAccessibilityServices", String.valueOf(this.c0));
        jSONObject.putOpt("AccessibilityDisplayInversionEnabled", String.valueOf(this.d0));
        jSONObject.putOpt("LocationMode", String.valueOf(this.e0));
        return jSONObject;
    }
}
