package defpackage;

/* renamed from: nB, reason: case insensitive filesystem */
/* loaded from: classes.dex */
public final class C31851nB extends VOi {
    public final C2929Ff2 b;

    public /* synthetic */ C31851nB(C21488fQg c21488fQg, C2929Ff2 c2929Ff2) {
        super(c21488fQg);
        this.b = c2929Ff2;
    }

    public C6948Mpg e(InterfaceC23642h28 interfaceC23642h28) {
        return new C6948Mpg(-572017208, new String[]{"Friend", "CombinedUsername", "FriendWhoAddedMe", "Story", "StorySnap", "Snap"}, this.a, "AddedMeFriend.sq", "selectAddedMeFriends", "SELECT\n    Friend._id,\n    Friend.username,\n    -- CAST(... AS TEXT) exploits a SqlDelight bug that causes the column to not be marked nullable. This is safe due\n    -- to the WHERE Friend.userId IS NOT NULL clause below (WHERE IS NOT NULL does _not_ cause SqlDelight to realise\n    -- the field is non-null, and it continues to use the nullable constraint from the original table definition!).\n    CAST(Friend.userId AS TEXT) AS userId,\n    Friend.displayName,\n    Friend.bitmojiSelfieId,\n    Friend.bitmojiAvatarId,\n    Friend.addedTimestamp,\n    Friend.reverseAddedTimestamp,\n    Friend.isPopular,\n    Friend.isOfficial,\n    Friend.publicProfilePictureUrl,\n    displayInfo.added AS isAdded,\n    displayInfo.ignored AS isIgnored,\n    displayInfo.addSource AS addSource,\n    displayInfo.score AS score,\n    displayInfo.ranked AS ranked,\n    Story._id AS storyRowId,\n    Story.viewed AS storyViewed,\n    Story.latestTimeStamp AS storyLatestTimestamp,\n    Story.latestExpirationTimestamp AS storyLatestExpirationTimestamp,\n    displayInfo.hasViewed AS hasViewed,\n    displayInfo.isHighQualityForBlending AS isHighQualityForBlending,\n    displayInfo.considerForLocationSharingProtection AS considerForLocationSharingProtection,\n    displayInfo.impressionCount AS impressionCount\nFROM\nFriendWithUsername AS Friend\nINNER JOIN FriendWhoAddedMe AS displayInfo ON Friend._id = displayInfo.friendRowId\nLEFT OUTER JOIN (\n   SELECT * FROM StoryViewActiveSnaps\n   WHERE StoryViewActiveSnaps._id IN (\n      SELECT StoryViewActiveSnaps._id FROM StoryViewActiveSnaps WHERE StoryViewActiveSnaps.kind = 0 GROUP BY StoryViewActiveSnaps.friendStoryPosterUserId\n   )\n ) AS Story ON (Story.friendStoryPosterUserId = Friend.userId AND Story.kind = 0)\nWHERE displayInfo.ignored = 0\n    AND Friend.reverseAddedTimestamp > 0\n    AND Friend.friendLinkType != 2\n    AND Friend.userId IS NOT NULL\nORDER BY displayInfo.hasViewed ASC, Friend.reverseAddedTimestamp DESC", new W6f(interfaceC23642h28, 15, this));
    }

    public C6948Mpg f() {
        return new C6948Mpg(2099812548, new String[]{"Friend", "CombinedUsername", "FriendWhoAddedMe", "Story", "StorySnap", "Snap"}, this.a, "AddedMeFriend.sq", "selectIgnoredAddedMeFriends", "SELECT\n    Friend._id,\n    Friend.username,\n    -- CAST(... AS TEXT) exploits a SqlDelight bug that causes the column to not be marked nullable. This is safe due\n    -- to the WHERE Friend.userId IS NOT NULL clause below (WHERE IS NOT NULL does _not_ cause SqlDelight to realise\n    -- the field is non-null, and it continues to use the nullable constraint from the original table definition!).\n    CAST(Friend.userId AS TEXT) AS userId,\n    Friend.displayName,\n    Friend.bitmojiSelfieId,\n    Friend.bitmojiAvatarId,\n    Friend.addedTimestamp,\n    Friend.reverseAddedTimestamp,\n    Friend.publicProfilePictureUrl,\n    displayInfo.added AS isAdded,\n    displayInfo.ignored AS isIgnored,\n    displayInfo.addSource AS addSource,\n    Story._id AS storyRowId,\n    Story.viewed AS storyViewed,\n    Story.latestTimeStamp AS storyLatestTimestamp,\n    Story.latestExpirationTimestamp AS storyLatestExpirationTimestamp\nFROM\nFriendWithUsername AS Friend\nINNER JOIN FriendWhoAddedMe AS displayInfo ON Friend._id = displayInfo.friendRowId\nLEFT OUTER JOIN (\n SELECT * FROM StoryViewActiveSnaps\n WHERE StoryViewActiveSnaps.kind = 0\n GROUP BY StoryViewActiveSnaps.friendStoryPosterUserId\n) AS Story ON (Story.friendStoryPosterUserId = Friend.userId AND Story.kind = 0)\nWHERE displayInfo.ignored = 1\n    AND Friend.userId IS NOT NULL\n    AND Friend.friendLinkType != 2\nORDER BY Friend.reverseAddedTimestamp DESC", new C34775pMf(28, this));
    }
}
