package defpackage;

import kotlin.jvm.functions.Function1;

/* renamed from: rLh, reason: case insensitive filesystem */
/* loaded from: classes4.dex */
public final class C37430rLh extends AbstractC37275rE9 implements Function1 {
    public final /* synthetic */ Long A0;
    public final /* synthetic */ Double B0;
    public final /* synthetic */ Long C0;
    public final /* synthetic */ Boolean D0;
    public final /* synthetic */ String E0;
    public final /* synthetic */ Long F0;
    public final /* synthetic */ String G0;
    public final /* synthetic */ Long H0;
    public final /* synthetic */ Boolean I0;
    public final /* synthetic */ byte[] J0;
    public final /* synthetic */ String K0;
    public final /* synthetic */ Boolean L0;
    public final /* synthetic */ Boolean M0;
    public final /* synthetic */ Long N0;
    public final /* synthetic */ Boolean O0;
    public final /* synthetic */ Long P0;
    public final /* synthetic */ long Q0;
    public final /* synthetic */ C38768sLh R0;
    public final /* synthetic */ long X;
    public final /* synthetic */ EnumC46035xn2 Y;
    public final /* synthetic */ Long Z;
    public final /* synthetic */ String a;
    public final /* synthetic */ String b;
    public final /* synthetic */ String c;
    public final /* synthetic */ Double e0;
    public final /* synthetic */ Boolean f0;
    public final /* synthetic */ Boolean g0;
    public final /* synthetic */ Long h0;
    public final /* synthetic */ Boolean i0;
    public final /* synthetic */ String j0;
    public final /* synthetic */ String k0;
    public final /* synthetic */ Boolean l0;
    public final /* synthetic */ Boolean m0;
    public final /* synthetic */ Long n0;
    public final /* synthetic */ byte[] o0;
    public final /* synthetic */ byte[] p0;
    public final /* synthetic */ byte[] q0;
    public final /* synthetic */ String r0;
    public final /* synthetic */ String s0;
    public final /* synthetic */ byte[] t;
    public final /* synthetic */ String t0;
    public final /* synthetic */ String u0;
    public final /* synthetic */ Long v0;
    public final /* synthetic */ Boolean w0;
    public final /* synthetic */ Boolean x0;
    public final /* synthetic */ Boolean y0;
    public final /* synthetic */ Boolean z0;

    /* JADX WARN: 'super' call moved to the top of the method (can break code semantics) */
    public C37430rLh(String str, String str2, String str3, byte[] bArr, long j, EnumC46035xn2 enumC46035xn2, Long l, Double d, Boolean bool, Boolean bool2, Long l2, Boolean bool3, String str4, String str5, Boolean bool4, Boolean bool5, Long l3, byte[] bArr2, byte[] bArr3, byte[] bArr4, String str6, String str7, String str8, String str9, Long l4, Boolean bool6, Boolean bool7, Boolean bool8, Boolean bool9, Long l5, Double d2, Long l6, Boolean bool10, String str10, Long l7, String str11, Long l8, Boolean bool11, byte[] bArr5, String str12, Boolean bool12, Boolean bool13, Long l9, Boolean bool14, Long l10, long j2, C38768sLh c38768sLh) {
        super(1);
        this.a = str;
        this.b = str2;
        this.c = str3;
        this.t = bArr;
        this.X = j;
        this.Y = enumC46035xn2;
        this.Z = l;
        this.e0 = d;
        this.f0 = bool;
        this.g0 = bool2;
        this.h0 = l2;
        this.i0 = bool3;
        this.j0 = str4;
        this.k0 = str5;
        this.l0 = bool4;
        this.m0 = bool5;
        this.n0 = l3;
        this.o0 = bArr2;
        this.p0 = bArr3;
        this.q0 = bArr4;
        this.r0 = str6;
        this.s0 = str7;
        this.t0 = str8;
        this.u0 = str9;
        this.v0 = l4;
        this.w0 = bool6;
        this.x0 = bool7;
        this.y0 = bool8;
        this.z0 = bool9;
        this.A0 = l5;
        this.B0 = d2;
        this.C0 = l6;
        this.D0 = bool10;
        this.E0 = str10;
        this.F0 = l7;
        this.G0 = str11;
        this.H0 = l8;
        this.I0 = bool11;
        this.J0 = bArr5;
        this.K0 = str12;
        this.L0 = bool12;
        this.M0 = bool13;
        this.N0 = l9;
        this.O0 = bool14;
        this.P0 = l10;
        this.Q0 = j2;
        this.R0 = c38768sLh;
    }

    @Override // kotlin.jvm.functions.Function1
    public final Object invoke(Object obj) {
        InterfaceC45561xR interfaceC45561xR = (InterfaceC45561xR) obj;
        interfaceC45561xR.bindString(0, this.a);
        interfaceC45561xR.bindString(1, this.b);
        interfaceC45561xR.bindString(2, this.c);
        interfaceC45561xR.j(3, this.t);
        interfaceC45561xR.b(4, Long.valueOf(this.X));
        AbstractC10372Sxc.b((Number) ((C19323do9) this.R0.b.b).c(this.Y), interfaceC45561xR, 5);
        interfaceC45561xR.b(6, this.Z);
        interfaceC45561xR.i(7, this.e0);
        interfaceC45561xR.h(8, this.f0);
        interfaceC45561xR.h(9, this.g0);
        interfaceC45561xR.b(10, this.h0);
        interfaceC45561xR.h(11, this.i0);
        interfaceC45561xR.bindString(12, this.j0);
        interfaceC45561xR.bindString(13, this.k0);
        interfaceC45561xR.h(14, this.l0);
        interfaceC45561xR.h(15, this.m0);
        interfaceC45561xR.b(16, this.n0);
        interfaceC45561xR.j(17, this.o0);
        interfaceC45561xR.j(18, this.p0);
        interfaceC45561xR.j(19, this.q0);
        interfaceC45561xR.bindString(20, this.r0);
        interfaceC45561xR.bindString(21, this.s0);
        interfaceC45561xR.bindString(22, this.t0);
        interfaceC45561xR.bindString(23, this.u0);
        interfaceC45561xR.b(24, this.v0);
        interfaceC45561xR.h(25, this.w0);
        interfaceC45561xR.h(26, this.x0);
        interfaceC45561xR.h(27, this.y0);
        interfaceC45561xR.h(28, this.z0);
        interfaceC45561xR.b(29, this.A0);
        interfaceC45561xR.i(30, this.B0);
        interfaceC45561xR.b(31, this.C0);
        interfaceC45561xR.h(32, this.D0);
        interfaceC45561xR.bindString(33, this.E0);
        interfaceC45561xR.b(34, this.F0);
        interfaceC45561xR.bindString(35, this.G0);
        interfaceC45561xR.b(36, this.H0);
        interfaceC45561xR.j(37, null);
        interfaceC45561xR.h(38, this.I0);
        interfaceC45561xR.j(39, this.J0);
        interfaceC45561xR.bindString(40, this.K0);
        interfaceC45561xR.h(41, this.L0);
        interfaceC45561xR.h(42, this.M0);
        interfaceC45561xR.b(43, this.N0);
        interfaceC45561xR.h(44, this.O0);
        interfaceC45561xR.b(45, this.P0);
        interfaceC45561xR.b(46, Long.valueOf(this.Q0));
        return C25099i7j.a;
    }
}
