package defpackage;

import android.content.Context;
import com.snap.ads.core.lib.db.AdPersistentStoreCleanupJob;
import com.snap.ads.core.lib.db.RemoveAdServeItemDurableJob;
import com.snap.ads.core.lib.network.durablejob.SnapAdsNetworkRequestJob;
import com.snap.analytics.performance.SchedulerPerfDurableJob;
import com.snap.bitmoji.content.job.BitmojiClientRenderPrefetchDurableJob;
import com.snap.bitmoji.ui.avatar.job.AvatarGlbBackgroundPrefetchDurableJob;
import com.snap.bitmoji.ui.avatar.job.AvatarGlbBackgroundPrefetchSingletonDurableJob;
import com.snap.bitmoji.ui.avatar.job.AvatarGlbForegroundPrefetchDurableJob;
import com.snap.bitmoji.ui.avatar.mirror.content.PrefetchLiveMirrorModelDurableJob;
import com.snap.blizzard.v2.lifecycle.BlizzardAdvertisingInfoCacheUpdatePeriodicJob;
import com.snap.bloops.data.DownloadBloopsAiModelsDurableJob;
import com.snap.bloops.data.DownloadFriendTargetDataDurableJob;
import com.snap.bloops.data.PreparingBloopsDiscoverDataDurableJob;
import com.snap.bloops.data.PreparingBloopsOnboardingDataDurableJob;
import com.snap.bloops.data.PreparingUserTargetDataDurableJob;
import com.snap.bolt.core.configs.FetchNetworkMappingDurableJob;
import com.snap.camera.subcomponents.lockscreen.infoicon.durablejob.LockscreenInfoIconPrefetchJob;
import com.snap.clientintegrity.api.IntegritySyncDurableJob;
import com.snap.clientsearch.indexer.ClientSearchIndexerJob;
import com.snap.commerce.lib.job.FavoritesDeltaSyncDurableJob;
import com.snap.commerce.lib.job.UploadLowResBitmojiImageDurableJob;
import com.snap.commerce.lib.screenshop.memories.perception.RecurringScanDurableJob;
import com.snap.communities.api.SyncMemberRankingJob;
import com.snap.composer.jobscheduler.lib.durablejob.ComposerJobDurableJob;
import com.snap.composer.jobscheduler.lib.durablejob.ComposerJobSchedulerInitDurableJob;
import com.snap.content.comments.core.actions.delete.DeleteCommentDurableJob;
import com.snap.content.comments.core.actions.post.PostCommentDurableJob;
import com.snap.content.comments.core.actions.reaction.CommentReactDurableJob;
import com.snap.content.comments.core.actions.updateallcommentsstate.UpdateAllCommentsStateDurableJob;
import com.snap.content.comments.core.actions.updatecommentstate.UpdateCommentStateDurableJob;
import com.snap.content.comments.core.data.purge.PurgeCachedCommentReactionsDurableJob;
import com.snap.content.snapdoc.impl.export.job.SnapExportJob;
import com.snap.content.storage.api.UnifiedContentStorageCleanupJob;
import com.snap.core.net.appstate.monitor.ASFDurableJob;
import com.snap.core.net.appstate.monitor.ASFDurableJobScheduler;
import com.snap.crash.impl.anr.durableJob.AnrDetectionDurableJob;
import com.snap.crash.impl.exitinfo.ExitInfoLoggerDurableJob;
import com.snap.crash.impl.logupload.Crash2ReportLogUploadJob;
import com.snap.datasync.DataSyncBackgroundSchedulingJob;
import com.snap.datasync.IndividualBackgroundDataSyncJob;
import com.snap.deltaforce.ConditionalWriteDurableJob;
import com.snap.deltaforce.FlushPendingWritesDurableJob;
import com.snap.discoverfeed.data.DiscoverFeedCleanupJob;
import com.snap.discoverplayback.api.durablejob.DiscoverFeedPlaybackSnapsCleanupJob;
import com.snap.dynamicdelivery.durablejob.DynamicDeliveryDurableJob;
import com.snap.explore.client.BatchExploreViewUpdateDurableJob;
import com.snap.fidelius.impl.FetchFideliusUpdatesDurableJob;
import com.snap.fidelius.impl.FideliusRemoveArroyoMessageKeyDurableJob;
import com.snap.fidelius.impl.FideliusRemoveSnapKeyDurableJob;
import com.snap.fidelius.impl.FideliusRetryDurableJob;
import com.snap.fidelius.impl.FideliusSaveArroyoMessageKeyDurableJob;
import com.snap.fidelius.impl.FideliusSaveSnapKeyDurableJob;
import com.snap.friending.lib.job.InvalidateFriendRowDurableJob;
import com.snap.identity.contacts.job.ContactsPermissionAutoGrantDurableJob;
import com.snap.identity.contacts.job.ContactsPermissionStatusCheckDurableJob;
import com.snap.identity.durablejob.legalagreement.DownloadTosHtmlDurableJob;
import com.snap.identity.job.ContactPermissionRevokeDurableJob;
import com.snap.identity.job.PermissionSettingsReporterDurableJob;
import com.snap.identity.job.SignupPermissionSettingsReporterDurableJob;
import com.snap.identity.job.snapchatter.AddFriendDurableJob;
import com.snap.identity.job.snapchatter.AddFriendsDurableJob;
import com.snap.identity.job.snapchatter.BlockFriendDurableJob;
import com.snap.identity.job.snapchatter.DismissSeenSuggestionDurableJob;
import com.snap.identity.job.snapchatter.FullContactSyncJob;
import com.snap.identity.job.snapchatter.HideFriendListDurableJob;
import com.snap.identity.job.snapchatter.HideSuggestionDurableJob;
import com.snap.identity.job.snapchatter.IgnoreFriendDurableJob;
import com.snap.identity.job.snapchatter.InviteOrAddFriendsDurableJob;
import com.snap.identity.job.snapchatter.RemoveFriendDurableJob;
import com.snap.identity.job.snapchatter.SeenSuggestionDurableJob;
import com.snap.identity.job.snapchatter.SyncSuggestionsDurableJob;
import com.snap.identity.job.snapchatter.UnblockFriendDurableJob;
import com.snap.identity.onetaplogin.durablejob.OneTapLoginNetworkRequestDurableJob;
import com.snap.identity.onetaplogin.durablejob.OneTapLoginUpdateDurableJob;
import com.snap.identity.onetaplogin.durablejob.OneTapLoginUpdateKickOffDurableJob;
import com.snap.identity.prefs.legalagreement.UpdateLegalAgreementDurableJob;
import com.snap.identity.takeover.VerificationTakeoverImpressionUpdateDurableJob;
import com.snap.identity.usernameui.service.ChangeUsernameDurableJob;
import com.snap.impala.model.durablejob.GiftingTermsDurableJob;
import com.snap.lenses.app.explorer.data.contentpreviews.ExplorerContentPreviewsUpdateJob;
import com.snap.lenses.data.unlock.UnlockOrganicLensJob;
import com.snap.lenses.prefetch.LensesPrefetchJob;
import com.snap.lenses.processing.persistence.LensesPersistentDataCleanupJob;
import com.snap.location.livelocation.LiveLocationPeriodicDurableJob;
import com.snap.location.loda.mainapp.LodaDurableJob;
import com.snap.lockscreenmode.lib.durablejob.LockScreenModeReportingJob;
import com.snap.lockscreenmode.lib.durablejob.LockScreenModeSwitchJob;
import com.snap.maps.components.memories.footsteps.FootstepsMemoriesBackfillDurableJob;
import com.snap.maps.framework.basemap.lib.refresh.MapRefreshDurableJob;
import com.snap.media.analyzer.VideoAnalyzerDurableJob;
import com.snap.media.manager.MediaPackageCleanupJob;
import com.snap.media.ort.lib.OrtJob;
import com.snap.media.quality.MediaQualityAnalysisDurableJob;
import com.snap.memories.backup.jobs.MemoriesUpdateEntryJob;
import com.snap.memories.backup.jobs.MemoriesUploadJob;
import com.snap.memories.backup.jobs.TranscodingJob;
import com.snap.memories.backup.jobs.UploadTagsJob;
import com.snap.memories.backup.orchestration.BackgroundOperationResurfaceJob;
import com.snap.memories.backup.orchestration.MigrateLegacyOperationToTacomaJob;
import com.snap.memories.backup.orchestration.OperationReviveJob;
import com.snap.memories.backup.tacoma.BackupJob;
import com.snap.memories.backup.tacoma.ScheduleBackupForIncompleteOperationsJob;
import com.snap.memories.lib.backfillindexing.MemoriesSnapIndexingDurableJob;
import com.snap.memories.lib.camerarollmetadata.CameraRollMetadataDbPurgeDurableJob;
import com.snap.memories.lib.camerarollmetadata.CameraRollMetadataScanKickoffDurableJob;
import com.snap.memories.lib.camerarollmetadata.CameraRollMetadataScanRecurringDurableJob;
import com.snap.memories.lib.camerarollmetadata.CameraRollMetadataUploadDurableJob;
import com.snap.memories.lib.embedding.durablejob.EmbeddingPersistDurableJob;
import com.snap.memories.lib.faceclustering.job.FaceClusteringJob;
import com.snap.memories.lib.featuredstories.CameraRollFeaturedStoriesUploadJob;
import com.snap.memories.lib.featuredstories.FeaturedStoriesFetchDurableJob;
import com.snap.memories.lib.resurface.MemoriesResurfaceCameraRollScanDurableJob;
import com.snap.memories.lib.resurface.MemoriesResurfaceMediaCheckDurableJob;
import com.snap.memories.lib.saving.MemoriesThumbnailRepairJob;
import com.snap.memories.lib.saving.SaveJob;
import com.snap.memories.lib.search.ClientSearchSyncTagsDurableJob;
import com.snap.memories.lib.snapfeed.durablejob.SnapFeedColdStartEligibilityDurableJob;
import com.snap.memories.lib.snapfeed.durablejob.SnapFeedColdStartEligibilitySchedulerDurableJob;
import com.snap.memories.lib.sync.upload.OperationsBridgeJob;
import com.snap.memories.lib.sync.upload.OpportunisticUploadJob;
import com.snap.memories.save.core.CameraRollSaveJob;
import com.snap.messaging.job.ArroyoBackgroundWakeupDurableJob;
import com.snap.monitoring.disk.impl.DiskCleanupDurableJob;
import com.snap.monitoring.disk.impl.DiskCleanupSchedulerDurableJob;
import com.snap.monitoring.disk.impl.DiskUsageReportDurableJob;
import com.snap.mushroom.startup.ProcessRestartDurableJob;
import com.snap.notification.processor.durablejob.NotificationAcknowledgementDurableJob;
import com.snap.notification.processor.durablejob.NotificationDeviceTriggerDurableJob;
import com.snap.notification.processor.durablejob.NotificationNativeHandlerRedriverJob;
import com.snap.notification.processor.durablejob.NotificationPeriodicDurableJob;
import com.snap.notification.processor.durablejob.NotificationProcessingOnlyDurableJob;
import com.snap.notification.processor.durablejob.NotificationRecoverFromPnsJob;
import com.snap.notification.processor.durablejob.ScheduleNotificationPeriodicDurableJob;
import com.snap.playstate.lib.UploadSnapReadReceiptDurableJob;
import com.snap.plus.lib.inapppurchase.InAppPurchaseDurableJob;
import com.snap.plus.lib.streakrestore.StreakRestoreDurableJob;
import com.snap.plus.lib.subscription.PlusAcknowledgeDurableJob;
import com.snap.profile.performance.durablejob.CleanUpExpiredPreloadConfigJob;
import com.snap.profile.performance.durablejob.LogPerformanceMetricsJob;
import com.snap.profile.performance.durablejob.PersistPreloadConfigJob;
import com.snap.prompting.lib.takeover.TakeoverKickoffDurableJob;
import com.snap.prompting.lib.takeover.TakeoverRecurringDurableJob;
import com.snap.ranking.lib.instantlogging.durablejob.InstantLoggerSendEventsJob;
import com.snap.recipientdevicecapabilities.lib.RecipientDeviceCapabilitiesSyncJob;
import com.snap.schedulersstartup.lib.SchedulersStartupConfigUpdaterJob;
import com.snap.security.api.LogoutDurableJob;
import com.snap.security.devicetoken.TokenRefreshDurableJob;
import com.snap.sharing.durablejob.MediaLinkBackgroundProcessingJob;
import com.snap.sharing.ranking.durablejob.features.ASTFeaturesDurableJob;
import com.snap.sharing.shortcuts.data.RemoveUserFromListsDurableJob;
import com.snap.snapactions.db.ContextCleanupJob;
import com.snap.snapshots.durablejob.SnapshotsRemoveSnapshot;
import com.snap.snapshots.durablejob.SnapshotsUploadMedia;
import com.snap.spectacles.lib.main.durablejob.SpectaclesDepthMapsPassiveDownloadDurableJob;
import com.snap.spectacles.lib.main.durablejob.SpectaclesDeviceSyncDurableJob;
import com.snap.spectacles.lib.main.durablejob.SpectaclesPassiveFirmwareUpdateDurableJob;
import com.snap.stickers.content.DeleteCustomStickersJob;
import com.snap.stickers.content.UploadCustomStickersJob;
import com.snap.stories.api.sync.ContentTakeDownOnServingSyncJob;
import com.snap.stories.client.StoriesSendMessageRecipientDeletionDurableJob;
import com.snap.stories.management.shared.UpdateMobStoryDurableJob;
import com.snap.stories.management.shared.settings.MyStoryPrivacySettingsDurableJob;
import com.snap.subscription.api.SubscriptionCleanupJob;
import com.snap.tinsel.lib.durablejob.TinselCleanupJob;
import com.snap.tinsel.lib.durablejob.TinselContentPrepDurableJob;
import com.snap.tinsel.lib.durablejob.TinselScanContentJob;
import com.snap.unlock.core.cleanup.UnlockCleanupJob;
import com.snap.upload.service.BackgroundUploadJob;
import com.snap.venueeditor.durablejob.VenueEditorDurableJob;
import com.snap.widgets.core.durablejob.WidgetAnalyticsDurableJob;
import com.snapchat.client.file_manager.CacheScope;

/* renamed from: vX1, reason: case insensitive filesystem */
/* loaded from: classes.dex */
public final class C43013vX1 implements InterfaceC16558bke {
    public final /* synthetic */ int a;
    public final /* synthetic */ Object b;

    public /* synthetic */ C43013vX1(int i, Object obj) {
        this.a = i;
        this.b = obj;
    }

    @Override // defpackage.InterfaceC16558bke
    public final Object get() {
        String str;
        Object obj = this.b;
        switch (this.a) {
            case 0:
                return (C34655pH0) ((C45686xX1) obj).W.getValue();
            case 1:
                return ((TZ1) obj).a();
            case 2:
                return ((C17110c9g) obj).a("CameraFrameDispatcher");
            case 3:
                return ((InterfaceC34355p32) ((CS3) obj).b).a();
            case 4:
                return new C29201lC3(0, (InterfaceC34553pC3) ((XZ5) obj).get());
            case 5:
                RY4 ry4 = (RY4) obj;
                C23107ge2 b = AbstractC18396d79.b(170);
                b.e(PermissionSettingsReporterDurableJob.class, ry4.q);
                b.e(SignupPermissionSettingsReporterDurableJob.class, ry4.r);
                b.e(AddFriendDurableJob.class, ry4.s);
                b.e(AddFriendsDurableJob.class, ry4.t);
                b.e(InviteOrAddFriendsDurableJob.class, ry4.u);
                b.e(ContactPermissionRevokeDurableJob.class, ry4.v);
                b.e(ContactsPermissionStatusCheckDurableJob.class, ry4.w);
                b.e(ContactsPermissionAutoGrantDurableJob.class, ry4.x);
                b.e(ASFDurableJob.class, ry4.z);
                b.e(ASFDurableJobScheduler.class, ry4.A);
                b.e(BlizzardAdvertisingInfoCacheUpdatePeriodicJob.class, ry4.C);
                b.e(DiskUsageReportDurableJob.class, ry4.E);
                b.e(DiskCleanupDurableJob.class, ry4.F);
                b.e(DiskCleanupSchedulerDurableJob.class, ry4.G);
                b.e(MediaPackageCleanupJob.class, ry4.H);
                b.e(MapRefreshDurableJob.class, ry4.f15770J);
                b.e(SchedulerPerfDurableJob.class, ry4.L);
                b.e(ExplorerContentPreviewsUpdateJob.class, ry4.N);
                b.e(ProcessRestartDurableJob.class, ry4.P);
                b.e(LogoutDurableJob.class, ry4.R);
                b.e(AdPersistentStoreCleanupJob.class, ry4.T);
                b.e(RemoveAdServeItemDurableJob.class, ry4.U);
                b.e(SnapAdsNetworkRequestJob.class, ry4.V);
                b.e(AvatarGlbBackgroundPrefetchSingletonDurableJob.class, ry4.X);
                b.e(AvatarGlbBackgroundPrefetchDurableJob.class, ry4.Y);
                b.e(AvatarGlbForegroundPrefetchDurableJob.class, ry4.Z);
                b.e(BitmojiClientRenderPrefetchDurableJob.class, ry4.a0);
                b.e(PrefetchLiveMirrorModelDurableJob.class, ry4.c0);
                b.e(DownloadBloopsAiModelsDurableJob.class, ry4.e0);
                b.e(DownloadFriendTargetDataDurableJob.class, ry4.f0);
                b.e(PreparingBloopsDiscoverDataDurableJob.class, ry4.g0);
                b.e(PreparingBloopsOnboardingDataDurableJob.class, ry4.h0);
                b.e(PreparingUserTargetDataDurableJob.class, ry4.i0);
                b.e(LockscreenInfoIconPrefetchJob.class, ry4.k0);
                b.e(LockScreenModeReportingJob.class, ry4.l0);
                b.e(LockScreenModeSwitchJob.class, ry4.n0);
                b.e(ClientSearchIndexerJob.class, ry4.p0);
                b.e(FavoritesDeltaSyncDurableJob.class, ry4.r0);
                b.e(RecurringScanDurableJob.class, ry4.s0);
                b.e(UploadLowResBitmojiImageDurableJob.class, ry4.t0);
                b.e(ComposerJobDurableJob.class, ry4.v0);
                b.e(ComposerJobSchedulerInitDurableJob.class, ry4.w0);
                b.e(CommentReactDurableJob.class, ry4.y0);
                b.e(DeleteCommentDurableJob.class, ry4.z0);
                b.e(PostCommentDurableJob.class, ry4.A0);
                b.e(PurgeCachedCommentReactionsDurableJob.class, ry4.B0);
                b.e(UpdateAllCommentsStateDurableJob.class, ry4.C0);
                b.e(UpdateCommentStateDurableJob.class, ry4.D0);
                b.e(UnifiedContentStorageCleanupJob.class, ry4.F0);
                b.e(ContextCleanupJob.class, ry4.H0);
                b.e(DiscoverFeedPlaybackSnapsCleanupJob.class, ry4.J0);
                b.e(DiscoverFeedCleanupJob.class, ry4.L0);
                b.e(InstantLoggerSendEventsJob.class, ry4.M0);
                b.e(FetchFideliusUpdatesDurableJob.class, ry4.O0);
                b.e(FideliusRemoveArroyoMessageKeyDurableJob.class, ry4.P0);
                b.e(FideliusRemoveSnapKeyDurableJob.class, ry4.Q0);
                b.e(FideliusRetryDurableJob.class, ry4.R0);
                b.e(FideliusSaveArroyoMessageKeyDurableJob.class, ry4.S0);
                b.e(FideliusSaveSnapKeyDurableJob.class, ry4.T0);
                b.e(FullContactSyncJob.class, ry4.V0);
                b.e(DismissSeenSuggestionDurableJob.class, ry4.W0);
                b.e(HideFriendListDurableJob.class, ry4.X0);
                b.e(HideSuggestionDurableJob.class, ry4.Y0);
                b.e(SeenSuggestionDurableJob.class, ry4.Z0);
                b.e(SyncSuggestionsDurableJob.class, ry4.a1);
                b.e(VerificationTakeoverImpressionUpdateDurableJob.class, ry4.b1);
                b.e(BlockFriendDurableJob.class, ry4.d1);
                b.e(IgnoreFriendDurableJob.class, ry4.e1);
                b.e(InvalidateFriendRowDurableJob.class, ry4.f1);
                b.e(RemoveFriendDurableJob.class, ry4.g1);
                b.e(UnblockFriendDurableJob.class, ry4.h1);
                b.e(DownloadTosHtmlDurableJob.class, ry4.j1);
                b.e(UpdateLegalAgreementDurableJob.class, ry4.k1);
                b.e(OneTapLoginNetworkRequestDurableJob.class, ry4.m1);
                b.e(OneTapLoginUpdateKickOffDurableJob.class, ry4.n1);
                b.e(OneTapLoginUpdateDurableJob.class, ry4.o1);
                b.e(ChangeUsernameDurableJob.class, ry4.q1);
                b.e(GiftingTermsDurableJob.class, ry4.s1);
                b.e(UploadSnapReadReceiptDurableJob.class, ry4.u1);
                b.e(BatchExploreViewUpdateDurableJob.class, ry4.w1);
                b.e(FootstepsMemoriesBackfillDurableJob.class, ry4.y1);
                b.e(BackupJob.class, ry4.A1);
                b.e(ScheduleBackupForIncompleteOperationsJob.class, ry4.B1);
                b.e(CameraRollMetadataScanKickoffDurableJob.class, ry4.D1);
                b.e(CameraRollMetadataDbPurgeDurableJob.class, ry4.E1);
                b.e(CameraRollMetadataScanRecurringDurableJob.class, ry4.F1);
                b.e(CameraRollMetadataUploadDurableJob.class, ry4.G1);
                b.e(ClientSearchSyncTagsDurableJob.class, ry4.I1);
                b.e(EmbeddingPersistDurableJob.class, ry4.K1);
                b.e(FaceClusteringJob.class, ry4.M1);
                b.e(CameraRollFeaturedStoriesUploadJob.class, ry4.O1);
                b.e(CameraRollSaveJob.class, ry4.Q1);
                b.e(MemoriesSnapIndexingDurableJob.class, ry4.S1);
                b.e(MemoriesThumbnailRepairJob.class, ry4.U1);
                b.e(MigrateLegacyOperationToTacomaJob.class, ry4.W1);
                b.e(FeaturedStoriesFetchDurableJob.class, ry4.X1);
                b.e(MemoriesUploadJob.class, ry4.Y1);
                b.e(OperationReviveJob.class, ry4.Z1);
                b.e(TranscodingJob.class, ry4.a2);
                b.e(BackgroundOperationResurfaceJob.class, ry4.b2);
                b.e(MemoriesUpdateEntryJob.class, ry4.c2);
                b.e(OperationsBridgeJob.class, ry4.d2);
                b.e(OpportunisticUploadJob.class, ry4.e2);
                b.e(SaveJob.class, ry4.f2);
                b.e(UploadTagsJob.class, ry4.g2);
                b.e(MemoriesResurfaceMediaCheckDurableJob.class, ry4.i2);
                b.e(MemoriesResurfaceCameraRollScanDurableJob.class, ry4.j2);
                b.e(SnapFeedColdStartEligibilityDurableJob.class, ry4.l2);
                b.e(SnapFeedColdStartEligibilitySchedulerDurableJob.class, ry4.m2);
                b.e(ArroyoBackgroundWakeupDurableJob.class, ry4.o2);
                b.e(NotificationAcknowledgementDurableJob.class, ry4.q2);
                b.e(NotificationDeviceTriggerDurableJob.class, ry4.r2);
                b.e(NotificationNativeHandlerRedriverJob.class, ry4.s2);
                b.e(NotificationPeriodicDurableJob.class, ry4.t2);
                b.e(NotificationProcessingOnlyDurableJob.class, ry4.u2);
                b.e(NotificationRecoverFromPnsJob.class, ry4.v2);
                b.e(ScheduleNotificationPeriodicDurableJob.class, ry4.w2);
                b.e(InAppPurchaseDurableJob.class, ry4.y2);
                b.e(StreakRestoreDurableJob.class, ry4.A2);
                b.e(PlusAcknowledgeDurableJob.class, ry4.C2);
                b.e(CleanUpExpiredPreloadConfigJob.class, ry4.E2);
                b.e(LogPerformanceMetricsJob.class, ry4.F2);
                b.e(PersistPreloadConfigJob.class, ry4.G2);
                b.e(SyncMemberRankingJob.class, ry4.I2);
                b.e(SnapshotsRemoveSnapshot.class, ry4.K2);
                b.e(SnapshotsUploadMedia.class, ry4.L2);
                b.e(TinselCleanupJob.class, ry4.N2);
                b.e(TinselContentPrepDurableJob.class, ry4.O2);
                b.e(TinselScanContentJob.class, ry4.P2);
                b.e(ASTFeaturesDurableJob.class, ry4.R2);
                b.e(MediaLinkBackgroundProcessingJob.class, ry4.T2);
                b.e(RemoveUserFromListsDurableJob.class, ry4.U2);
                b.e(SnapExportJob.class, ry4.W2);
                b.e(SpectaclesDepthMapsPassiveDownloadDurableJob.class, ry4.Y2);
                b.e(SpectaclesDeviceSyncDurableJob.class, ry4.Z2);
                b.e(SpectaclesPassiveFirmwareUpdateDurableJob.class, ry4.a3);
                b.e(DeleteCustomStickersJob.class, ry4.c3);
                b.e(UploadCustomStickersJob.class, ry4.d3);
                b.e(StoriesSendMessageRecipientDeletionDurableJob.class, ry4.f3);
                b.e(ContentTakeDownOnServingSyncJob.class, ry4.g3);
                b.e(MyStoryPrivacySettingsDurableJob.class, ry4.h3);
                b.e(UpdateMobStoryDurableJob.class, ry4.i3);
                b.e(SubscriptionCleanupJob.class, ry4.k3);
                b.e(UnlockCleanupJob.class, ry4.m3);
                b.e(VenueEditorDurableJob.class, ry4.o3);
                b.e(WidgetAnalyticsDurableJob.class, ry4.q3);
                b.e(FetchNetworkMappingDurableJob.class, ry4.s3);
                b.e(IntegritySyncDurableJob.class, ry4.u3);
                b.e(AnrDetectionDurableJob.class, ry4.w3);
                b.e(ConditionalWriteDurableJob.class, ry4.y3);
                b.e(DataSyncBackgroundSchedulingJob.class, ry4.z3);
                b.e(FlushPendingWritesDurableJob.class, ry4.A3);
                b.e(IndividualBackgroundDataSyncJob.class, ry4.B3);
                b.e(LiveLocationPeriodicDurableJob.class, ry4.D3);
                b.e(LodaDurableJob.class, ry4.F3);
                b.e(VideoAnalyzerDurableJob.class, ry4.H3);
                b.e(MediaQualityAnalysisDurableJob.class, ry4.J3);
                b.e(OrtJob.class, ry4.L3);
                b.e(DynamicDeliveryDurableJob.class, ry4.N3);
                b.e(RecipientDeviceCapabilitiesSyncJob.class, ry4.P3);
                b.e(SchedulersStartupConfigUpdaterJob.class, ry4.R3);
                b.e(TokenRefreshDurableJob.class, ry4.T3);
                b.e(BackgroundUploadJob.class, ry4.V3);
                b.e(LensesPrefetchJob.class, ry4.X3);
                b.e(UnlockOrganicLensJob.class, ry4.Z3);
                b.e(LensesPersistentDataCleanupJob.class, ry4.b4);
                b.e(TakeoverKickoffDurableJob.class, ry4.g4);
                b.e(TakeoverRecurringDurableJob.class, ry4.h4);
                b.e(Crash2ReportLogUploadJob.class, ry4.j4);
                b.e(ExitInfoLoggerDurableJob.class, ry4.k4);
                return b.c();
            case 6:
                return new C13584Yv8((C39534sv8) obj);
            case 7:
                return (C39994tGa[]) ((C12718Xfi) ((C28935l00) obj).Z).getValue();
            case 8:
                return ((C28325kY4) obj).Xa();
            case 9:
                return (C26869jSa) obj;
            case 10:
                return (C41714uYj) obj;
            case 11:
                return (Z1j) obj;
            case 12:
                CacheScope cacheScope = CacheScope.USER;
                C47672z0g c47672z0g = (C47672z0g) obj;
                LSg a = ((XSg) ((C21642fY4) c47672z0g.c).get()).a();
                if (a == null || (str = a.a) == null) {
                    str = "";
                }
                return new C28159kQ3(cacheScope, str, ((Boolean) ((C6860Mlc) ((InterfaceC16558bke) c47672z0g.t).get()).c.getValue()).booleanValue());
            case 13:
                return (C28159kQ3) obj;
            case 14:
                C14438a9g a2 = ((C17110c9g) ((C40291tUe) obj).a.t).a("RenderingContextManagerImpl");
                int i = AbstractC41627uUe.a;
                return new C15775b9g(a2);
            case 15:
                return ((C4757Iof) obj).h;
            default:
                return new A33((Context) obj);
        }
    }
}
