package defpackage;

import android.net.Uri;
import java.util.LinkedHashMap;
import java.util.concurrent.Callable;

/* renamed from: rHg, reason: case insensitive filesystem */
/* loaded from: classes8.dex */
public final class CallableC37345rHg implements Callable {
    public final /* synthetic */ int a;
    public final /* synthetic */ AbstractC38683sHg b;
    public final /* synthetic */ boolean c;
    public final /* synthetic */ C28357kZf t;

    public CallableC37345rHg(int i, AbstractC38683sHg abstractC38683sHg, boolean z, C28357kZf c28357kZf) {
        this.a = i;
        this.b = abstractC38683sHg;
        this.c = z;
        this.t = c28357kZf;
    }

    @Override // java.util.concurrent.Callable
    public final Object call() {
        LinkedHashMap linkedHashMap = EnumC37220rBh.b;
        C42883vQg c42883vQg = this.b.a;
        int i = this.a;
        if (i == 6) {
            String str = c42883vQg.j;
            if (str != null) {
                return new C4332Hu8(c42883vQg.b, new C2656Eu8(str, str, null));
            }
            throw new IllegalArgumentException("External Url is null");
        }
        if (i == 8) {
            Boolean bool = c42883vQg.o;
            Boolean bool2 = Boolean.TRUE;
            if (AbstractC2032Dq9.j(bool, bool2)) {
                if (c42883vQg.k == null) {
                    throw new IllegalArgumentException("Missing AttachmentUrl for autogenerated sticker");
                }
            } else if (c42883vQg.j == null) {
                throw new IllegalArgumentException("Partner Sticker's external url is null");
            }
            return new C21152fAg(c42883vQg.b, new C18469dAg(c42883vQg.k, c42883vQg.j, c42883vQg.l, c42883vQg.m, AbstractC2032Dq9.j(c42883vQg.o, bool2), this.c));
        }
        if (i == 0) {
            String str2 = c42883vQg.p;
            if (str2 != null) {
                return new C20015eK6(c42883vQg.b, new C44084wK6(str2, RJ6.a(str2)), 1);
            }
            throw new IllegalArgumentException("Sticker id is null");
        }
        if (i == 2) {
            String str3 = c42883vQg.p;
            if (str3 != null) {
                String str4 = (String) c42883vQg.r.getValue();
                if (str4 != null) {
                    return new K21(c42883vQg.b, new I71(str3, c42883vQg.s, str4, this.c, EnumC36440qc7.PREVIEW, (C16636bo4) null, 96));
                }
                throw new IllegalArgumentException("Missing avatar id!");
            }
            throw new IllegalArgumentException("Sticker id is null");
        }
        if (i == 3 || i == 1) {
            String str5 = c42883vQg.p;
            if (str5 != null) {
                String str6 = c42883vQg.s;
                if (str6 != null) {
                    return new K21(c42883vQg.b, new C21570fUg(str5, str6, this.c), EnumC15883bEh.o0);
                }
                throw new IllegalArgumentException("Pack id is null");
            }
            throw new IllegalArgumentException("Sticker id is null");
        }
        if (i == 4) {
            String queryParameter = c42883vQg.a.getQueryParameter("custom_sticker_data");
            if (queryParameter != null) {
                return new C12808Xk4(new C10115Sl4((C15256am4) this.t.d(C15256am4.class, queryParameter)), c42883vQg.b, 1);
            }
            throw new IllegalAccessException("Custom sticker data is null");
        }
        if (i == 12) {
            String str7 = c42883vQg.p;
            if (str7 != null) {
                String str8 = c42883vQg.j;
                if (str8 != null) {
                    return new K21(c42883vQg.b, new HZc(str7, str8));
                }
                throw new IllegalArgumentException("External Url is null");
            }
            throw new IllegalArgumentException("Sticker id is null");
        }
        if (i == 13) {
            String str9 = c42883vQg.p;
            if (str9 != null) {
                String str10 = c42883vQg.j;
                if (str10 != null) {
                    String str11 = c42883vQg.q;
                    if (str11 != null) {
                        return new C47537yue(c42883vQg.b, new C44865wue(str9, str10, str11));
                    }
                    throw new IllegalArgumentException("Conversation Id is null");
                }
                throw new IllegalArgumentException("External Url is null");
            }
            throw new IllegalArgumentException("Sticker id is null");
        }
        if (i == 10) {
            String str12 = c42883vQg.p;
            if (str12 != null) {
                String str13 = c42883vQg.j;
                if (str13 != null) {
                    String str14 = c42883vQg.u;
                    if (str14 == null) {
                        str14 = "";
                    }
                    return new K21(new C6452Ls1(str12, Uri.parse(str13), Uri.parse(str13), null, null, null, str14, C38757sL6.a), c42883vQg.b);
                }
                throw new IllegalArgumentException("External Url is null");
            }
            throw new IllegalArgumentException("Sticker id is null");
        }
        if (i == 15) {
            String str15 = c42883vQg.p;
            if (str15 != null) {
                String str16 = c42883vQg.j;
                if (str16 != null) {
                    String str17 = c42883vQg.y;
                    if (str17 != null) {
                        return new C42841vOg(c42883vQg.b, new C38830sOg(str15, str16, str17));
                    }
                    throw new IllegalArgumentException("Conversation id is null");
                }
                throw new IllegalArgumentException("External Url is null");
            }
            throw new IllegalArgumentException("Sticker id is null");
        }
        if (i == 16) {
            String str18 = c42883vQg.p;
            if (str18 != null) {
                String str19 = c42883vQg.j;
                if (str19 != null) {
                    return new K21(c42883vQg.b, new C22544gD7(1, str18, str19), (byte) 0);
                }
                throw new IllegalArgumentException("External Url is null");
            }
            throw new IllegalArgumentException("Sticker id is null");
        }
        if (i == 19) {
            String str20 = c42883vQg.p;
            if (str20 != null) {
                String str21 = c42883vQg.j;
                if (str21 != null) {
                    String str22 = c42883vQg.q;
                    if (str22 != null) {
                        return new K21(c42883vQg.b, new C46157xse(str20, str21, str22));
                    }
                    throw new IllegalArgumentException("Conversation Id is null");
                }
                throw new IllegalArgumentException("External Url is null");
            }
            throw new IllegalArgumentException("Sticker id is null");
        }
        if (i == 21) {
            String str23 = c42883vQg.p;
            if (str23 != null) {
                String str24 = c42883vQg.j;
                if (str24 != null) {
                    return new K21(c42883vQg.b, new C22544gD7(0, str23, str24));
                }
                throw new IllegalArgumentException("External Url is null");
            }
            throw new IllegalArgumentException("Sticker id is null");
        }
        throw new IllegalStateException("This sticker type is not supported yet");
    }
}
