package defpackage;

/* loaded from: classes8.dex */
public enum DOf implements InterfaceC22815gQ6 {
    RATE_LIMITED(0),
    INTENTIONAL(1),
    LOCKED(2),
    MALFORMED_REQUEST(3),
    PERSISTENCE(4),
    UPDATE_NOT_APPLICABLE(5),
    NOT_FRIENDS(6),
    DUPLICATE_REQUEST(7),
    DEPENDENCY_NOT_SATISFIED(8),
    OUT_OF_SYNC(9),
    NOT_FOUND(10),
    MESSAGE_ALREADY_EXPIRED(11),
    UNKNOWN_SERVICE_FAILURE_REASON(12),
    TIMEOUT(13),
    RESOURCE_EXHAUSTED(14),
    UNAVAILABLE(15),
    CANCELLED(16),
    UNAUTHORIZED(17),
    PERMISSION_DENIED(18),
    INTERNAL_ERROR(19),
    UNKNOWN(20),
    UNEXPECTED_GRPC_ERROR(21),
    MISSING_CLIENT_CONVERSATION_ID(22),
    MISSING_STORY_ID(23),
    MISSING_PHONE_NUMBER(24),
    MISSING_CCM_RESULT(25),
    CONV_DOES_NOT_EXIST(26),
    MSG_DOES_NOT_EXIST(27),
    STORAGE_ERROR(28),
    MISSING_STORY_MEDIA(29),
    PHONE_NUMBER_INCONSISTENT(30),
    MISSING_USER_ID(31),
    UPLOAD_RESULTS_EMPTY(32),
    MAX_SEVERITY_RESULT_FAILED(33),
    UPLOAD_EMPTY_ID(34),
    UPLOAD_XCODING_RETRY_NO_ENC_INFO(35),
    UPLOAD_XCODING_CANNOT_RESTART(36),
    UPLOAD_EMPTY_DATA(37),
    TRANSCODE_RETRY(38);

    public final int a;

    DOf(int i) {
        this.a = i;
    }

    @Override // defpackage.InterfaceC22815gQ6
    public final int a() {
        return this.a;
    }
}
