package defpackage;

/* renamed from: Nd7, reason: case insensitive filesystem */
/* loaded from: classes.dex */
public enum EnumC7231Nd7 implements InterfaceC22815gQ6 {
    CAMERA_FIRST_PREVIEW_FRAME_RECEIVED(0),
    CAMERA_FIRST_PREVIEW_FRAME_RENDERED(1),
    CAMERA_OPEN_STARTED(9),
    CAMERA_OPEN_COMPLETED(10),
    CAMERA_PAGE_INJECT_STARTED(5),
    CAMERA_PAGE_INJECT_COMPLETED(6),
    CAMERA_PAGE_CONSTRUCTOR_STARTED(3),
    CAMERA_PAGE_CONSTRUCTOR_COMPLETED(4),
    CAMERA_PAGE_LAYOUT_INFLATION_STARTED(7),
    CAMERA_PAGE_LAYOUT_INFLATION_COMPLETED(8),
    CAMERA_ANDROID_FIRST_UI_RENDERED(33),
    CAMERA_ANDROID_PAGE_INJECT_STARTED(34),
    CAMERA_ANDROID_PAGE_INJECT_COMPLETED(35),
    CAMERA_ANDROID_PAGE_CONSTRUCTOR_STARTED(36),
    CAMERA_ANDROID_PAGE_CONSTRUCTOR_COMPLETED(37),
    CAMERA_ANDROID_PAGE_LAYOUT_INFLATION_STARTED(38),
    CAMERA_ANDROID_PAGE_LAYOUT_INFLATION_COMPLETED(39),
    CAMERA_ANDROID_PREPARE_TRIGGERED(11),
    CAMERA_ANDROID_PREPARE_COMPLETED(12),
    CAMERA_ANDROID_SERVICE_OPEN_TRIGGERED(13),
    CAMERA_ANDROID_SERVICE_OPEN_COMPLETED(14),
    CAMERA_ANDROID_ENABLE_STREAMING_TRIGGERED(15),
    CAMERA_ANDROID_START_PREVIEW_TRIGGERED(16),
    CAMERA_ANDROID_START_PREVIEW_STARTED(17),
    CAMERA_ANDROID_START_PREVIEW_COMPLETED(18),
    CAMERA_ANDROID_START_PREVIEW_BG_THREAD_COMPLETED(19),
    CAMERA_ANDROID_START_PREVIEW_MAIN_THREAD_COMPLETED(20),
    CAMERA_ANDROID_FRAGMENT_ATTACH_STARTED(21),
    CAMERA_ANDROID_FRAGMENT_ATTACH_COMPLETED(22),
    CAMERA_ANDROID_FRAGMENT_ON_CREATE_VIEW_STARTED(23),
    CAMERA_ANDROID_FRAGMENT_ON_CREATE_VIEW_COMPLETED(24),
    CAMERA_ANDROID_FRAGMENT_ON_VIEW_CREATED_STARTED(25),
    CAMERA_ANDROID_FRAGMENT_ON_VIEW_CREATED_COMPLETED(26),
    CAMERA_ANDROID_APPLICATION_WARMUP_MAIN_THREAD_STARTED(27),
    CAMERA_ANDROID_APPLICATION_WARMUP_MAIN_THREAD_COMPLETED(28),
    CAMERA_ANDROID_APPLICATION_WARMUP_BG_THREAD_STARTED(29),
    CAMERA_ANDROID_APPLICATION_WARMUP_BG_THREAD_COMPLETED(30),
    CAMERA_ANDROID_OPEN_RETRY_COOLDOWN_STARTED(31),
    CAMERA_ANDROID_OPEN_RETRY_COOLDOWN_COMPLETED(32),
    CAMERA_ANDROID_CAPTURE_BUTTON_CLICKABLE(70),
    CAMERA_IOS_PREVIEW_VIEW_DID_LAYOUT(54),
    CAMERA_IOS_HARDWARE_INIT_STARTED(40),
    CAMERA_IOS_HARDWARE_INIT_COMPLETED(41),
    CAMERA_IOS_HARDWARE_DEVICE_INPUTS_SETUP_STARTED(42),
    CAMERA_IOS_HARDWARE_DEVICE_INPUTS_SETUP_COMPLETED(43),
    CAMERA_IOS_HARDWARE_WILL_ENTER_FOREGROUND_STARTED(44),
    CAMERA_IOS_HARDWARE_WILL_ENTER_FOREGROUND_COMPLETED(45),
    CAMERA_IOS_RENDERER_SETUP_STARTED(46),
    CAMERA_IOS_RENDERER_SETUP_COMPLETED(47),
    CAMERA_IOS_RENDERER_ATTACH_STARTED(48),
    CAMERA_IOS_RENDERER_ATTACH_COMPLETED(49),
    CAMERA_IOS_DATA_SOURCE_SETUP_STARTED(50),
    CAMERA_IOS_DATA_SOURCE_SETUP_COMPLETED(51),
    CAMERA_IOS_DEVICE_FORMAT_UPDATE_STARTED(52),
    CAMERA_IOS_DEVICE_FORMAT_UPDATE_COMPLETED(53),
    FRIENDS_FEED_IOS_SYNC_FEED_STARTED(55),
    FRIENDS_FEED_IOS_SYNC_FEED_COMPLETED(56),
    FRIENDS_FEED_IOS_PROCESS_SYNC_FEED_RESPONSE_COMPLETED(57),
    FRIENDS_FEED_IOS_PROCESS_INDIVIDUAL_SOURCES_STARTED(58),
    FRIENDS_FEED_IOS_PROCESS_FEED_ITEMS_COMPLETED(59),
    FRIENDS_FEED_IOS_RANK_FEED_ITEMS_COMPLETED(60),
    FRIENDS_FEED_IOS_PROPAGATE_CHANGE_TO_UI_STARTED(61),
    FRIENDS_FEED_IOS_TABLEVIEW_UPDATE_STARTED(62),
    FRIENDS_FEED_IOS_TABLEVIEW_UPDATE_COMPLETED(63),
    FRIENDS_FEED_IOS_CACHED_DATA_TABLEVIEW_UPDATE_COMPLETED(64),
    FRIENDS_FEED_IOS_ENTRYPOINT_BEGIN(68),
    FRIENDS_FEED_IOS_INJECTION_END(65),
    FRIENDS_FEED_IOS_ENTER_PAGE(69),
    FRIENDS_FEED_ANDROID_FRAGMENT_ATTACH(71),
    FRIENDS_FEED_ANDROID_INJECTION_END(72),
    FRIENDS_FEED_ANDROID_CONFIG_LOAD_START(73),
    FRIENDS_FEED_ANDROID_CONFIG_LOAD_END(74),
    FRIENDS_FEED_ANDROID_DATA_LOAD_START(75),
    FRIENDS_FEED_ANDROID_DATA_LOAD_ENDS(76),
    FRIENDS_FEED_ANDROID_SECTION_VIEW_MODEL_START(77),
    FRIENDS_FEED_ANDROID_SECTION_VIEW_MODEL_END(78),
    FRIENDS_FEED_ANDROID_SYNCER_START(79);

    public final int a;

    EnumC7231Nd7(int i) {
        this.a = i;
    }

    @Override // defpackage.InterfaceC22815gQ6
    public final int a() {
        return this.a;
    }
}
