package defpackage;

import com.snap.modules.contacts_api.SmsInviteFeature;
import com.snap.sharing.share_sheet.ShareDestination;
import com.snapchat.client.messaging.Tweaks;
import java.util.Set;
import java.util.concurrent.TimeUnit;

/* JADX WARN: Enum visitor error
jadx.core.utils.exceptions.JadxRuntimeException: Init of enum field 'c' uses external variables
	at jadx.core.dex.visitors.EnumVisitor.createEnumFieldByConstructor(EnumVisitor.java:451)
	at jadx.core.dex.visitors.EnumVisitor.processEnumFieldByField(EnumVisitor.java:372)
	at jadx.core.dex.visitors.EnumVisitor.processEnumFieldByWrappedInsn(EnumVisitor.java:337)
	at jadx.core.dex.visitors.EnumVisitor.extractEnumFieldsFromFilledArray(EnumVisitor.java:322)
	at jadx.core.dex.visitors.EnumVisitor.extractEnumFieldsFromInsn(EnumVisitor.java:262)
	at jadx.core.dex.visitors.EnumVisitor.convertToEnum(EnumVisitor.java:151)
	at jadx.core.dex.visitors.EnumVisitor.visit(EnumVisitor.java:100)
 */
/* JADX WARN: Failed to restore enum class, 'enum' modifier and super class removed */
/* renamed from: Lfg, reason: case insensitive filesystem */
/* loaded from: classes.dex */
public final class EnumC6196Lfg implements BI3 {
    public static final EnumC6196Lfg A0;
    public static final EnumC6196Lfg A1;
    public static final EnumC6196Lfg A2;
    public static final EnumC6196Lfg B0;
    public static final EnumC6196Lfg B1;
    public static final EnumC6196Lfg B2;
    public static final EnumC6196Lfg C0;
    public static final EnumC6196Lfg C1;
    public static final EnumC6196Lfg C2;
    public static final EnumC6196Lfg D0;
    public static final EnumC6196Lfg D1;
    public static final EnumC6196Lfg D2;
    public static final EnumC6196Lfg E0;
    public static final EnumC6196Lfg E1;
    public static final EnumC6196Lfg E2;
    public static final EnumC6196Lfg F0;
    public static final EnumC6196Lfg F1;
    public static final EnumC6196Lfg F2;
    public static final EnumC6196Lfg G0;
    public static final EnumC6196Lfg G1;
    public static final EnumC6196Lfg G2;
    public static final EnumC6196Lfg H0;
    public static final EnumC6196Lfg H1;
    public static final EnumC6196Lfg H2;
    public static final EnumC6196Lfg I0;
    public static final EnumC6196Lfg I1;
    public static final EnumC6196Lfg I2;
    public static final EnumC6196Lfg J0;
    public static final EnumC6196Lfg J1;
    public static final EnumC6196Lfg J2;
    public static final EnumC6196Lfg K0;
    public static final EnumC6196Lfg K1;
    public static final EnumC6196Lfg K2;
    public static final EnumC6196Lfg L0;
    public static final EnumC6196Lfg L1;
    public static final EnumC6196Lfg L2;
    public static final EnumC6196Lfg M0;
    public static final EnumC6196Lfg M1;
    public static final EnumC6196Lfg M2;
    public static final EnumC6196Lfg N0;
    public static final EnumC6196Lfg N1;
    public static final EnumC6196Lfg N2;
    public static final EnumC6196Lfg O0;
    public static final EnumC6196Lfg O1;
    public static final EnumC6196Lfg O2;
    public static final EnumC6196Lfg P0;
    public static final EnumC6196Lfg P1;
    public static final EnumC6196Lfg P2;
    public static final EnumC6196Lfg Q0;
    public static final EnumC6196Lfg Q1;
    public static final EnumC6196Lfg Q2;
    public static final EnumC6196Lfg R0;
    public static final EnumC6196Lfg R1;
    public static final EnumC6196Lfg R2;
    public static final EnumC6196Lfg S0;
    public static final EnumC6196Lfg S1;
    public static final EnumC6196Lfg S2;
    public static final EnumC6196Lfg T0;
    public static final EnumC6196Lfg T1;
    public static final EnumC6196Lfg T2;
    public static final EnumC6196Lfg U0;
    public static final EnumC6196Lfg U1;
    public static final EnumC6196Lfg U2;
    public static final EnumC6196Lfg V0;
    public static final EnumC6196Lfg V1;
    public static final /* synthetic */ EnumC6196Lfg[] V2;
    public static final EnumC6196Lfg W0;
    public static final EnumC6196Lfg W1;
    public static final EnumC6196Lfg X;
    public static final EnumC6196Lfg X0;
    public static final EnumC6196Lfg X1;
    public static final EnumC6196Lfg Y;
    public static final EnumC6196Lfg Y0;
    public static final EnumC6196Lfg Y1;
    public static final EnumC6196Lfg Z;
    public static final EnumC6196Lfg Z0;
    public static final EnumC6196Lfg Z1;
    public static final EnumC6196Lfg a1;
    public static final EnumC6196Lfg a2;
    public static final EnumC6196Lfg b = new EnumC6196Lfg("MEDIA_LINKS", 0, QR1.I(false));
    public static final EnumC6196Lfg b1;
    public static final EnumC6196Lfg b2;
    public static final EnumC6196Lfg c;
    public static final EnumC6196Lfg c1;
    public static final EnumC6196Lfg c2;
    public static final EnumC6196Lfg d1;
    public static final EnumC6196Lfg d2;
    public static final EnumC6196Lfg e0;
    public static final EnumC6196Lfg e1;
    public static final EnumC6196Lfg e2;
    public static final EnumC6196Lfg f0;
    public static final EnumC6196Lfg f1;
    public static final EnumC6196Lfg f2;
    public static final EnumC6196Lfg g0;
    public static final EnumC6196Lfg g1;
    public static final EnumC6196Lfg g2;
    public static final EnumC6196Lfg h0;
    public static final EnumC6196Lfg h1;
    public static final EnumC6196Lfg h2;
    public static final EnumC6196Lfg i0;
    public static final EnumC6196Lfg i1;
    public static final EnumC6196Lfg i2;
    public static final EnumC6196Lfg j0;
    public static final EnumC6196Lfg j1;
    public static final EnumC6196Lfg j2;
    public static final EnumC6196Lfg k0;
    public static final EnumC6196Lfg k1;
    public static final EnumC6196Lfg k2;
    public static final EnumC6196Lfg l0;
    public static final EnumC6196Lfg l1;
    public static final EnumC6196Lfg l2;
    public static final EnumC6196Lfg m0;
    public static final EnumC6196Lfg m1;
    public static final EnumC6196Lfg m2;
    public static final EnumC6196Lfg n0;
    public static final EnumC6196Lfg n1;
    public static final EnumC6196Lfg n2;
    public static final EnumC6196Lfg o0;
    public static final EnumC6196Lfg o1;
    public static final EnumC6196Lfg o2;
    public static final EnumC6196Lfg p0;
    public static final EnumC6196Lfg p1;
    public static final EnumC6196Lfg p2;
    public static final EnumC6196Lfg q0;
    public static final EnumC6196Lfg q1;
    public static final EnumC6196Lfg q2;
    public static final EnumC6196Lfg r0;
    public static final EnumC6196Lfg r1;
    public static final EnumC6196Lfg r2;
    public static final EnumC6196Lfg s0;
    public static final EnumC6196Lfg s1;
    public static final EnumC6196Lfg s2;
    public static final EnumC6196Lfg t;
    public static final EnumC6196Lfg t0;
    public static final EnumC6196Lfg t1;
    public static final EnumC6196Lfg t2;
    public static final EnumC6196Lfg u0;
    public static final EnumC6196Lfg u1;
    public static final EnumC6196Lfg u2;
    public static final EnumC6196Lfg v0;
    public static final EnumC6196Lfg v1;
    public static final EnumC6196Lfg v2;
    public static final EnumC6196Lfg w0;
    public static final EnumC6196Lfg w1;
    public static final EnumC6196Lfg w2;
    public static final EnumC6196Lfg x0;
    public static final EnumC6196Lfg x1;
    public static final EnumC6196Lfg x2;
    public static final EnumC6196Lfg y0;
    public static final EnumC6196Lfg y1;
    public static final EnumC6196Lfg y2;
    public static final EnumC6196Lfg z0;
    public static final EnumC6196Lfg z1;
    public static final EnumC6196Lfg z2;
    public final AI3 a;

    static {
        AI3 I = QR1.I(false);
        I.t = "MEDIA_LINK_EXPIRATION_TIME_SHOW_SEND_TO";
        c = new EnumC6196Lfg("MEMORY_LINK_EXPIRATION_TIME_SHOW", 1, I);
        AI3 M = QR1.M(72);
        M.e0 = 822;
        t = new EnumC6196Lfg("MEMORY_LINK_EXPIRATION_TIME_HOURS", 2, M);
        AI3 I3 = QR1.I(false);
        I3.t = "MEDIA_LINK_PRIVACY_ALERT";
        X = new EnumC6196Lfg("MEDIA_LINK_PRIVACY_ALERT", 3, I3);
        AI3 I4 = QR1.I(false);
        I4.e0 = 852;
        Y = new EnumC6196Lfg("HAS_SEEN_MEDIA_LINK_TOOLTIP_OR_PRIVACY_ALERT", 4, I4);
        AI3 I5 = QR1.I(true);
        I5.t = "ST_MEMORY_LINK_ANDROID";
        Z = new EnumC6196Lfg("MEMORY_LINK", 5, I5);
        AI3 M3 = QR1.M(10);
        M3.t = "MEDIA_LINK_MAX_BATCH_UPLOAD_COUNT";
        e0 = new EnumC6196Lfg("MEDIA_LINK_MAX_BATCH_UPLOAD_COUNT", 6, M3);
        AI3 M4 = QR1.M(600);
        M4.t = "MEDIA_LINK_THUMBNAIL_HEIGHT";
        f0 = new EnumC6196Lfg("MEDIA_LINK_THUMBNAIL_HEIGHT", 7, M4);
        g0 = new EnumC6196Lfg("SOCIAL_SMS_ROUTE_TAG", 8, QR1.R(""));
        h0 = new EnumC6196Lfg("INVITE_ROUTE_TAG", 9, QR1.R(""));
        AI3 I6 = QR1.I(false);
        I6.t = "MEDIA_LINK_ENABLE_SHORT_LINKS";
        i0 = new EnumC6196Lfg("MEDIA_LINK_ENABLE_SHORT_LINKS", 10, I6);
        AI3 I7 = QR1.I(false);
        I7.t = "ST_ENABLE_SPOTLIGHT_UPSELL_ANDROID";
        j0 = new EnumC6196Lfg("ST_ENABLE_SPOTLIGHT_UPSELL_ANDROID", 11, I7);
        k0 = new EnumC6196Lfg("AST_BACKEND_RANKING", 12, QR1.I(false));
        AI3 I8 = QR1.I(false);
        I8.t = "SEND_TO_DEDUP_CONTACTS";
        l0 = new EnumC6196Lfg("DEDUP_CONTACTS_ANDROID", 13, I8);
        AI3 I9 = QR1.I(false);
        I9.t = "ENABLE_ALL_CONTACTS_AST";
        m0 = new EnumC6196Lfg("ENABLE_ALL_CONTACTS_AST", 14, I9);
        AI3 I10 = QR1.I(false);
        I10.t = "ENABLE_EXTRA_TIMESTAMPS_AST";
        n0 = new EnumC6196Lfg("ENABLE_EXTRA_TIMESTAMPS_AST", 15, I10);
        AI3 I11 = QR1.I(false);
        I11.t = "ANDROID_DO_PREVIEW_COMPUTATION_AST";
        o0 = new EnumC6196Lfg("DO_PREVIEW_COMPUTATION_AST", 16, I11);
        AI3 I12 = QR1.I(false);
        I12.t = "ANDROID_DISABLE_TOP_GROUPS_SECTION";
        p0 = new EnumC6196Lfg("DISABLE_TOP_GROUPS_SECTION", 17, I12);
        AI3 I13 = QR1.I(false);
        I13.t = "ANDROID_ENABLE_UNIDIRECTIONAL_FRIENDS";
        q0 = new EnumC6196Lfg("ENABLE_UNIDIRECTIONAL_FRIENDS", 18, I13);
        AI3 I14 = QR1.I(false);
        I14.t = "ANDROID_DISABLE_PRELOADING_ON_REPLY_CAMERA";
        r0 = new EnumC6196Lfg("DISABLE_PRELOADING_ON_REPLY_CAMERA", 19, I14);
        AI3 I15 = QR1.I(false);
        I15.t = "PERFORM_ON_DEMAND_REQUEST_AST";
        s0 = new EnumC6196Lfg("PERFORM_ON_DEMAND_REQUEST_AST", 20, I15);
        AI3 M5 = QR1.M(0);
        M5.t = "ST_SEARCH_MIN_STORIES_QUERY_LEN";
        t0 = new EnumC6196Lfg("ST_SEARCH_MIN_STORIES_QUERY_LEN", 21, M5);
        AI3 I16 = QR1.I(false);
        I16.t = "ST_SEARCH_QUERY_ENABLE_SPACE";
        u0 = new EnumC6196Lfg("ST_SEARCH_QUERY_ENABLE_SPACE", 22, I16);
        AI3 R = QR1.R("is_imp_cap,action_1w,action_3d,action_1d,action_6h,impression_1w,impression_3d,impression_1d,impression_6h,p_view,is_ria,lastInteractionTimestamp,lastInteractionAge,lastTurnInteractionTimestamp,lastSnapSendByOtherParticipantAge,lastSnapViewByUserAge,lastChatSendByOtherParticipantAge,lastChatViewByUserAge,streakCount,isStreakExpiring,groupSize,joinedAge,isLensUsed,isMentioned,snapSource,p_view_ab");
        R.t = "SEND_TO_RANKING_LOGGABLE_FEATURE_KEYS";
        v0 = new EnumC6196Lfg("SEND_TO_RANKING_LOGGABLE_FEATURE_KEYS", 23, R);
        AI3 R3 = QR1.R("https://cf-st.sc-cdn.net/d/msx3WAh7nKgvsPi12EdY2?bo=EhMaABoAMgIEfUgCUAhaAwiOC2AB&uc=8");
        R3.t = "SEND_TO_RANKING_RECENTS_MODEL";
        w0 = new EnumC6196Lfg("AST_PROTO_LINK", 24, R3);
        AI3 R4 = QR1.R("");
        R4.t = "SEND_TO_RANKING_RERANKING_RECENTS_MODEL";
        x0 = new EnumC6196Lfg("AST_RERANKER_PROTO_LINK", 25, R4);
        AI3 R5 = QR1.R("");
        R5.t = "SEND_TO_RANKING_FILTERING_RECENTS_MODEL";
        y0 = new EnumC6196Lfg("AST_FILTER_PROTO_LINK", 26, R5);
        AI3 ai3 = new AI3(new C31149mf2(), C31149mf2.class);
        ai3.t = "SEND_TO_RANKING_FEATURES_GLOBAL";
        z0 = new EnumC6196Lfg("AST_COF_FEATURES", 27, ai3);
        A0 = new EnumC6196Lfg("STORIES", 28, QR1.I(false));
        B0 = new EnumC6196Lfg("ADDRESS_BOOK_CONTACTS", 29, QR1.I(false));
        AI3 I17 = QR1.I(false);
        I17.t = "SNAP_ANYONE_SENDER_ANDROID";
        C0 = new EnumC6196Lfg("SNAP_ANYONE_SENDER", 30, I17);
        AI3 I18 = QR1.I(false);
        I18.t = "SNAP_ANYONE_PUBLIC_CONTENT_ANDROID";
        D0 = new EnumC6196Lfg("SNAP_ANYONE_FOR_PUBLIC_CONTENT", 31, I18);
        AI3 I19 = QR1.I(false);
        I19.e0 = 640;
        E0 = new EnumC6196Lfg("HAS_SEEN_SNAP_ANYONE_PRIVACY_ALERT", 32, I19);
        AI3 M6 = QR1.M(3000);
        M6.t = "ST_EXPORTED_MEMORIES_LINK_FALLBACK_IN_MS_ANDROID";
        F0 = new EnumC6196Lfg("EXPORTED_MEDIA_LINK_FALLBACK_MS", 33, M6);
        AI3 ai32 = new AI3("[\"AT\", \"BE\", \"BG\", \"BR\", \"HR\", \"CY\", \"CZ\", \"DK\", \"EE\", \"FI\", \"FR\", \"DE\", \"GR\", \"HU\", \"IS\", \"IE\", \"IT\", \"LV\", \"LI\", \"LT\", \"LU\", \"MT\", \"NL\", \"NO\", \"PL\", \"PT\", \"RO\", \"SK\", \"SI\", \"ES\", \"SE\", \"CH\", \"GB\"]", new PWi<Set<String>>() { // from class: Dfg
        }.b);
        ai32.t = "ST_PHONE_COUNTRY_SMS_METRIC_BLOCKLIST_ARRAY";
        G0 = new EnumC6196Lfg("ST_PHONE_COUNTRY_SMS_METRIC_BLOCKLIST", 34, ai32);
        AI3 ai33 = new AI3("[\"US\", \"CA\", \"MX\", \"PR\", \"AG\", \"LC\", \"VI\", \"AI\", \"AW\", \"BB\", \"BL\", \"BM\", \"BQ\", \"BS\", \"BZ\", \"CR\", \"CU\", \"CW\", \"DM\", \"DO\", \"GD\", \"GL\", \"GP\", \"GT\", \"HN\", \"HT\", \"JM\", \"KN\", \"KY\", \"MF\", \"MQ\", \"MS\", \"NI\", \"PA\", \"PM\", \"SV\", \"SX\", \"TC\", \"TT\", \"VC\", \"VG\", \"BR\", \"CO\", \"CL\", \"PY\", \"FR\", \"GB\", \"TR\", \"PL\", \"MK\", \"LT\", \"AT\", \"DE\", \"RO\", \"NL\", \"BG\", \"IT\", \"BE\", \"ES\", \"GR\", \"SE\", \"NO\", \"CZ\", \"DK\", \"HU\", \"HR\", \"FI\", \"PT\", \"SK\", \"IE\", \"LV\", \"EE\", \"LU\", \"IS\", \"CY\", \"MT\", \"GL\", \"CH\", \"ME\", \"JE\", \"SI\", \"BA\", \"RS\", \"AL\", \"MD\", \"PH\", \"HK\", \"TW\", \"SG\", \"KR\", \"TH\", \"JP\", \"BN\", \"AU\", \"NZ\", \"FJ\", \"SB\", \"ZA\", \"MU\", \"NA\", \"KE\", \"QA\", \"IN\", \"SA\", \"EG\", \"NP\", \"PK\", \"PS\", \"LB\", \"AE\", \"KW\", \"TN\", \"IQ\", \"IL\", \"JO\", \"LY\", \"SO\", \"MA\", \"DZ\", \"NG\", \"SN\", \"GH\", \"EC\", \"CI\", \"AR\", \"PE\", \"BO\", \"SL\", \"BH\", \"BD\", \"ID\", \"MY\", \"OM\"]", new PWi<Set<String>>() { // from class: Efg
        }.b);
        ai33.t = "ST_PHONE_COUNTRY_SMS_RECIPIENT_ALLOWLIST";
        H0 = new EnumC6196Lfg("ST_PHONE_COUNTRY_SMS_RECIPIENT_ALLOWLIST", 35, ai33);
        AI3 I20 = QR1.I(false);
        I20.t = "ST_ALL_CONTACTS_ON_SNAPCHAT_ANDROID";
        I0 = new EnumC6196Lfg("VIEW_MORE_CONTACTS_ON_SNAPCHAT_SECTION", 36, I20);
        AI3 I21 = QR1.I(false);
        I21.t = "ST_ALL_CONTACTS_ENABLE_TWILIO_INVITE_ANDROID";
        J0 = new EnumC6196Lfg("ENABLE_TWILIO_NON_SNAPCHATTER", 37, I21);
        AI3 I22 = QR1.I(false);
        I22.t = "ST_PUBLIC_LINK_SNAP_STAR_ANDROID";
        K0 = new EnumC6196Lfg("ST_PUBLIC_LINK_SNAP_STAR_ANDROID", 38, I22);
        AI3 I23 = QR1.I(false);
        I23.t = "ST_PUBLIC_LINK_DISCOVER_STORIES_ANDROID";
        L0 = new EnumC6196Lfg("ST_PUBLIC_LINK_DISCOVER_STORIES_ANDROID", 39, I23);
        AI3 I24 = QR1.I(false);
        I24.t = "ST_PUBLIC_LINK_PUBLISHER_PROFILE_ANDROID";
        M0 = new EnumC6196Lfg("ST_PUBLIC_LINK_PUBLISHER_PROFILE_ANDROID", 40, I24);
        AI3 I25 = QR1.I(false);
        I25.t = "ST_PUBLIC_LINK_LENS_ANDROID";
        N0 = new EnumC6196Lfg("ST_PUBLIC_LINK_LENS_ANDROID", 41, I25);
        AI3 I26 = QR1.I(false);
        I26.t = "ST_PUBLIC_LINK_MAP_STORIES_ANDROID";
        O0 = new EnumC6196Lfg("ST_PUBLIC_LINK_MAP_STORIES_ANDROID", 42, I26);
        AI3 I27 = QR1.I(false);
        I27.t = "ST_PUBLIC_LINK_PUBLIC_STORIES_ANDROID";
        P0 = new EnumC6196Lfg("ST_PUBLIC_LINK_PUBLIC_STORIES_ANDROID", 43, I27);
        AI3 I28 = QR1.I(false);
        I28.t = "ST_PUBLIC_LINK_SPOTLIGHT_ANDROID";
        Q0 = new EnumC6196Lfg("ST_PUBLIC_LINK_SPOTLIGHT_ANDROID", 44, I28);
        AI3 I29 = QR1.I(false);
        I29.t = "ST_PUBLIC_LINK_FRIEND_PROFILE_ANDROID";
        R0 = new EnumC6196Lfg("ST_PUBLIC_LINK_FRIEND_PROFILE_ANDROID", 45, I29);
        AI3 I30 = QR1.I(false);
        I30.t = "RTUS_PRODUCT_ENABLED_SEND_TO";
        S0 = new EnumC6196Lfg("ST_RTUS_FOR_SEND_TO_RANKING_ENABLED", 46, I30);
        T0 = new EnumC6196Lfg("SEND_TO_PRELOADS", 47, QR1.I(false));
        AI3 I31 = QR1.I(false);
        I31.t = "ANDROID_AVOID_VIEW_PRELOADING_AS_BLOCKING_STEP";
        U0 = new EnumC6196Lfg("AVOID_VIEW_PRELOADING_AS_BLOCKING_STEP", 48, I31);
        AI3 I32 = QR1.I(false);
        I32.t = "ANDROID_FRIENDS_IN_THIS_SNAP_ABOVE_BEST_FRIENDS";
        V0 = new EnumC6196Lfg("FRIENDS_IN_THIS_SNAP_ABOVE_BEST_FRIENDS", 49, I32);
        W0 = new EnumC6196Lfg("PRELOAD_STRATEGY", 50, QR1.K(BLd.a));
        AI3 M7 = QR1.M(2);
        M7.t = "ST_PRELOAD_HEADER_COUNT_ANDROID";
        X0 = new EnumC6196Lfg("PRELOAD_HEADER_COUNT", 51, M7);
        AI3 M8 = QR1.M(10);
        M8.t = "ST_PRELOAD_CELL_COUNT_ANDROID";
        Y0 = new EnumC6196Lfg("PRELOAD_CELL_COUNT", 52, M8);
        AI3 M9 = QR1.M(4);
        M9.t = "ST_PRELOAD_TWIN_CELL_COUNT_ANDROID";
        Z0 = new EnumC6196Lfg("PRELOAD_TWIN_CELL_COUNT", 53, M9);
        a1 = new EnumC6196Lfg("SHORTCUTS", 54, QR1.I(false));
        AI3 I33 = QR1.I(false);
        I33.s(327);
        b1 = new EnumC6196Lfg("HAS_SEEN_LISTS_INTRO", 55, I33);
        c1 = new EnumC6196Lfg("SEND_TO_LISTS_GENERATION_MIN_SIZE", 56, QR1.M(10));
        d1 = new EnumC6196Lfg("SEND_TO_LISTS_GENERATION_MIN_RATIO", 57, QR1.L(0.03f));
        AI3 M10 = QR1.M((int) TimeUnit.HOURS.toSeconds(4L));
        M10.t = "SHORTCUTS_SYNC_INTERVAL_SECONDS";
        e1 = new EnumC6196Lfg("LISTS_SYNC_INTERVAL_SECONDS", 58, M10);
        AI3 K = QR1.K(EnumC45983xkg.a);
        K.t = "SHORTCUTS_SORT_BY";
        f1 = new EnumC6196Lfg("SHORTCUTS_SORT_BY", 59, K);
        g1 = new EnumC6196Lfg("LISTS_LAST_SYNC_TIMESTAMP", 60, QR1.N(0L));
        h1 = new EnumC6196Lfg("CONTEXTUAL_SHORTCUTS", 61, QR1.I(false));
        AI3 M11 = QR1.M(7);
        M11.t = "CONTEXTUAL_SHORTCUT_CONTACTS_RANKING_ORDER";
        i1 = new EnumC6196Lfg("CONTEXTUAL_SHORTCUT_CONTACTS_RANKING_ORDER", 62, M11);
        AI3 M12 = QR1.M(3);
        M12.t = "CONTEXTUAL_SHORTCUTS_NEW_FRIENDS_LOWER_THRESHOLD";
        j1 = new EnumC6196Lfg("CONTEXTUAL_SHORTCUTS_NEW_FRIENDS_LOWER_THRESHOLD", 63, M12);
        AI3 M13 = QR1.M(2);
        M13.t = "CONTEXTUAL_SHORTCUTS_BIRTHDAY_LOWER_THRESHOLD";
        k1 = new EnumC6196Lfg("CONTEXTUAL_SHORTCUTS_BIRTHDAY_LOWER_THRESHOLD", 64, M13);
        AI3 M14 = QR1.M(2);
        M14.t = "CONTEXTUAL_SHORTCUTS_NEARBY_LOWER_THRESHOLD";
        l1 = new EnumC6196Lfg("CONTEXTUAL_SHORTCUTS_NEARBY_LOWER_THRESHOLD", 65, M14);
        AI3 M15 = QR1.M(7);
        M15.t = "CONTEXTUAL_SHORTCUTS_NEARBY_UPPER_THRESHOLD";
        m1 = new EnumC6196Lfg("CONTEXTUAL_SHORTCUTS_NEARBY_UPPER_THRESHOLD", 66, M15);
        AI3 M16 = QR1.M(2);
        M16.t = "CONTEXTUAL_SHORTCUTS_NEW_FRIENDS_RANKING_ORDER";
        n1 = new EnumC6196Lfg("CONTEXTUAL_SHORTCUTS_NEW_FRIENDS_RANKING_ORDER", 67, M16);
        AI3 M17 = QR1.M(3);
        M17.t = "CONTEXTUAL_SHORTCUTS_BIRTHDAY_RANKING_ORDER";
        o1 = new EnumC6196Lfg("CONTEXTUAL_SHORTCUTS_BIRTHDAY_RANKING_ORDER", 68, M17);
        AI3 M18 = QR1.M(4);
        M18.t = "CONTEXTUAL_SHORTCUTS_NEARBY_RANKING_ORDER";
        p1 = new EnumC6196Lfg("CONTEXTUAL_SHORTCUTS_NEARBY_RANKING_ORDER", 69, M18);
        q1 = new EnumC6196Lfg("SHARE_SHEET", 70, QR1.I(false));
        AI3 ai34 = new AI3("[]", new PWi<Set<ShareDestination>>() { // from class: Ffg
        }.b);
        ai34.t = "DISABLED_OFF_PLATFORM_SHARE_DESTINATIONS_ANDROID";
        r1 = new EnumC6196Lfg("DISABLED_OFF_PLATFORM_SHARE_DESTINATIONS", 71, ai34);
        s1 = new EnumC6196Lfg("SEND_TO_SHARE_SHEET_INLINE", 72, QR1.I(false));
        AI3 N = QR1.N(2000L);
        N.t = "OFF_PLATFORM_DELAY_MS_ANDROID";
        t1 = new EnumC6196Lfg("OFF_PLATFORM_DELAY_MS", 73, N);
        u1 = new EnumC6196Lfg("ENABLE_BLOOPS_EXTERNAL_SHARING", 74, QR1.I(true));
        AI3 M19 = QR1.M(1);
        M19.t = "ST_POST_LENS_FAVORITING_SHARE_PROMPT_ANDROID";
        v1 = new EnumC6196Lfg("POST_LENS_FAVORITING_SHARE_PROMPT", 75, M19);
        w1 = new EnumC6196Lfg("LAST_SELECTED_OFF_PLATFORM_DESTINATION", 76, QR1.R(""));
        x1 = new EnumC6196Lfg("LAST_SELECTED_OFF_PLATFORM_DESTINATION_TIMESTAMP", 77, QR1.N(0L));
        y1 = new EnumC6196Lfg("SHORTLINKS", 78, QR1.I(false));
        AI3 I34 = QR1.I(false);
        I34.t = "SHORTEN_DEEP_LINKS_ANDROID";
        z1 = new EnumC6196Lfg("SHORTEN_DEEP_LINKS", 79, I34);
        AI3 N3 = QR1.N(5000L);
        N3.t = "SHORTEN_DEEP_LINKS_TIMEOUT_ANDROID";
        A1 = new EnumC6196Lfg("SHORTEN_DEEP_LINKS_TIMEOUT", 80, N3);
        AI3 N4 = QR1.N(5000L);
        N4.t = "UNAUTHENTICATED_SHORTEN_DEEP_LINKS_TIMEOUT_ANDROID";
        B1 = new EnumC6196Lfg("UNAUTHENTICATED_SHORTEN_DEEP_LINKS_TIMEOUT", 81, N4);
        AI3 I35 = QR1.I(true);
        I35.t = "DEEP_LINK_CALL_INVITE_SERVICE_ANDROID";
        C1 = new EnumC6196Lfg("DEEP_LINK_CALL_INVITE_SERVICE", 82, I35);
        AI3 K3 = QR1.K(EnumC16829bx.a);
        K3.t = "DEEP_LINK_ADD_FRIEND_PROMPT_TYPE_ANDROID";
        D1 = new EnumC6196Lfg("DEEP_LINK_ADD_FRIEND_PROMPT_TYPE", 83, K3);
        AI3 M20 = QR1.M(10);
        M20.t = "DEEP_LINK_ADD_FRIEND_PROMPT_MAX_OPEN_COUNT_ANDROID";
        E1 = new EnumC6196Lfg("DEEP_LINK_ADD_FRIEND_PROMPT_MAX_OPEN_COUNT", 84, M20);
        AI3 I36 = QR1.I(false);
        I36.t = "SAVE_SNAP_TO_SHOW_OPS_FROM_PREVIEW";
        F1 = new EnumC6196Lfg("SAVE_SNAP_TO_SHOW_OPS_FROM_PREVIEW", 85, I36);
        AI3 N5 = QR1.N(6000L);
        N5.t = "DEEP_LINK_ADD_FRIEND_PROMPT_DISPLAY_TIME_MS";
        G1 = new EnumC6196Lfg("DEEP_LINK_ADD_FRIEND_PROMPT_DISPLAY_TIME_MS", 86, N5);
        H1 = new EnumC6196Lfg("WATERMARKS", 87, QR1.I(false));
        AI3 ai35 = new AI3("[\"MEMORIES\"]", new PWi<Set<String>>() { // from class: Gfg
        }.b);
        ai35.t = "WATERMARK_SHARE_SOURCES_ANDROID";
        I1 = new EnumC6196Lfg("WATERMARK_SOURCES", 88, ai35);
        AI3 ai36 = new AI3("[]", new PWi<Set<String>>() { // from class: Hfg
        }.b);
        ai36.t = "WATERMARK_SHARE_DESTINATIONS_ANDROID";
        J1 = new EnumC6196Lfg("WATERMARK_DESTINATIONS", 89, ai36);
        AI3 ai37 = new AI3("[]", new PWi<Set<String>>() { // from class: Ifg
        }.b);
        ai37.t = "WATERMARK_MEMORIES_LENS_IDS";
        K1 = new EnumC6196Lfg("WATERMARK_MEMORIES_LENS_IDS", 90, ai37);
        AI3 I37 = QR1.I(false);
        I37.t = "WATERMARK_SNAPCHAT_LENSES";
        L1 = new EnumC6196Lfg("WATERMARK_SNAPCHAT_LENSES", 91, I37);
        AI3 I38 = QR1.I(false);
        I38.t = "WATERMARK_DUAL_SAVES_ANDROID";
        M1 = new EnumC6196Lfg("WATERMARK_DUAL_SAVES", 92, I38);
        AI3 I39 = QR1.I(true);
        I39.t = "WATERMARK_IMAGE_EXPORT";
        N1 = new EnumC6196Lfg("WATERMARK_IMAGES", 93, I39);
        AI3 I40 = QR1.I(true);
        I40.t = "WATERMARK_LENS_ONLY_ANDROID";
        O1 = new EnumC6196Lfg("WATERMARK_LENS_ONLY", 94, I40);
        AI3 I41 = QR1.I(false);
        I41.t = "WATERMARK_USE_DESCRIPTOR_ELIGIBILITY_ANDROID";
        P1 = new EnumC6196Lfg("WATERMARK_USE_DESCRIPTOR_ELIGIBILITY", 95, I41);
        AI3 I42 = QR1.I(true);
        I42.t = "WATERMARK_FORCE_TRANSCODE_ANDROID";
        Q1 = new EnumC6196Lfg("WATERMARK_FORCE_TRANSCODE", 96, I42);
        AI3 R6 = QR1.R("https://cf-st.sc-cdn.net/d/BTJ2V7RK3Gkfns8yfkZ3Z?bo=EhMaABoAMgIEfUgCUAhaAwikTmAB&uc=8");
        R6.t = "WATERMARK_MEMORIES_ASSET_URL";
        R1 = new EnumC6196Lfg("WATERMARK_ASSET_URL", 97, R6);
        AI3 R7 = QR1.R("https://cf-st.sc-cdn.net/d/ejur6ARcCDlSDhuW82hQV?bo=EhMaABoAMgIEfUgCUAhaAwjqJmAB&uc=8");
        R7.t = "WATERMARK_GEN_AI_ASSET_URL";
        S1 = new EnumC6196Lfg("WATERMARK_GEN_AI_ASSET_URL", 98, R7);
        AI3 I43 = QR1.I(false);
        I43.s(578);
        T1 = new EnumC6196Lfg("HAS_ACCEPTED_WATERMARK_DIALOG", 99, I43);
        AI3 I44 = QR1.I(false);
        I44.t = "OPS_SHARE_SHEET_AUTO_DISMISS_ENABLED";
        U1 = new EnumC6196Lfg("OPS_SHARE_SHEET_AUTO_DISMISS_ENABLED", 100, I44);
        AI3 M21 = QR1.M(10);
        M21.t = "OPS_SHARE_SHEET_AUTO_DISMISS_TIME_SECONDS";
        V1 = new EnumC6196Lfg("OPS_SHARE_SHEET_AUTO_DISMISS_TIME_SECONDS", 101, M21);
        AI3 I45 = QR1.I(false);
        I45.t = "OPS_SHARE_SHEET_IMPRESSION_CAP_ENABLED";
        W1 = new EnumC6196Lfg("OPS_SHARE_SHEET_IMPRESSION_CAP_ENABLED", 102, I45);
        AI3 M22 = QR1.M(3600);
        M22.t = "OPS_SHARE_SHEET_IMPRESSION_CAP_SESSION_DURATION_SECONDS";
        X1 = new EnumC6196Lfg("OPS_SHARE_SHEET_IMPRESSION_CAP_SESSION_DURATION_SECONDS", 103, M22);
        AI3 M23 = QR1.M(10);
        M23.t = "OPS_SHARE_SHEET_IMPRESSION_CAP_MAX_COUNT";
        Y1 = new EnumC6196Lfg("OPS_SHARE_SHEET_IMPRESSION_CAP_MAX_COUNT", 104, M23);
        AI3 I46 = QR1.I(false);
        I46.t = "IS_CONTACT_PHOTO_ENABLED";
        Z1 = new EnumC6196Lfg("IS_CONTACT_PHOTO_ENABLED", 105, I46);
        AI3 M24 = QR1.M(86400);
        M24.t = "ST_SPOTLIGHT_SHARE_UPSELL_PRESENTATION_TIME_INTERVAL_ANDROID";
        a2 = new EnumC6196Lfg("ST_SPOTLIGHT_SHARE_UPSELL_PRESENTATION_TIME_INTERVAL_SECS", 106, M24);
        AI3 I47 = QR1.I(false);
        I47.t = "IS_CONTACT_SYNC_NEW_FILTER_LOGIC_ENABLED_ANDROID";
        b2 = new EnumC6196Lfg("IS_CONTACT_SYNC_NEW_FILTER_LOGIC_ENABLED", 107, I47);
        AI3 N6 = QR1.N(0L);
        N6.s(680);
        c2 = new EnumC6196Lfg("AUTO_SAVE_PROMPT_LAST_SEEN_TIMESTAMP_SECONDS", 108, N6);
        AI3 N7 = QR1.N(0L);
        N7.s(1090);
        d2 = new EnumC6196Lfg("SHARING_SPOTLIGHT_SHARE_UPSELL_LAST_TIME_SEEN_TIMESTAMP_MS", Tweaks.MAX_HOURS_AFTER_STREAK_EXPIRE_TO_ENABLE_RESTORE, N7);
        AI3 M25 = QR1.M(0);
        M25.s(702);
        e2 = new EnumC6196Lfg("AUTO_SAVE_PROMPT_NUMBER_OF_TIMES_SEEN", Tweaks.ENABLE_STREAK_EDUCATION, M25);
        AI3 I48 = QR1.I(false);
        I48.s(703);
        f2 = new EnumC6196Lfg("AUTO_SAVE_PROMPT_DO_NOT_SHOW_OVERRIDE", 111, I48);
        AI3 M26 = QR1.M(11);
        M26.t = "SHARING_VIDEO_MAX_UNDER_DURATION";
        g2 = new EnumC6196Lfg("SHARING_VIDEO_MAX_UNDER_DURATION", 112, M26);
        h2 = new EnumC6196Lfg("FSN_ANNIHILATION", Tweaks.DELTA_SYNC_SQLITE_SHARED_STORAGE_CACHE_SIZE, QR1.I(false));
        AI3 ai38 = new AI3("[\"VERIFIED_PHONE\"]", new PWi<Set<String>>() { // from class: Jfg
        }.b);
        ai38.t = "SHARING_SMS_INVITE_PREREQUISITES_ANDROID";
        i2 = new EnumC6196Lfg("SMS_INVITE_PREREQUISITES", Tweaks.FAIL_DECRYPT_FOR_DUPLEX_SNAPS_TEST_ONLY, ai38);
        AI3 ai39 = new AI3("[\"ADD_FRIENDS\", \"ALL_CONTACTS\", \"FRIENDS_FEED\", \"INVITE_FRIENDS\", \"INVITE_REGISTRATION\", \"UNIVERSAL_SEARCH\", \"UNIVERSAL_SEARCH_PRETYPE\"]", new PWi<Set<SmsInviteFeature>>() { // from class: Kfg
        }.b);
        ai39.t = "SHARING_SMS_INVITE_FEATURES_ANDROID";
        j2 = new EnumC6196Lfg("ENABLED_SMS_INVITE_FEATURES", 115, ai39);
        AI3 I49 = QR1.I(false);
        I49.t = "IS_CONTACTS_SHARE_DESTINATION_ENABLED";
        k2 = new EnumC6196Lfg("IS_CONTACTS_SHARE_DESTINATION_ENABLED", 116, I49);
        AI3 I50 = QR1.I(false);
        I50.t = "SHARING_ENABLE_OFF_PLATFORM_SHARE_MY_STORY";
        l2 = new EnumC6196Lfg("ENABLE_OFF_PLATFORM_SHARE_MY_STORY", 117, I50);
        AI3 I51 = QR1.I(true);
        I51.t = "SHARING_ENABLE_BATCH_EXPORT_MEDIA_VIA_MEDIA_LINK";
        m2 = new EnumC6196Lfg("ENABLE_BATCH_EXPORT_MEDIA_VIA_MEDIA_LINK", 118, I51);
        AI3 I52 = QR1.I(false);
        I52.t = "SHARING_ENABLE_LINKTREE_ANDROID";
        n2 = new EnumC6196Lfg("ENABLE_LINKTREE", 119, I52);
        AI3 I53 = QR1.I(false);
        I53.t = "SHARING_ENABLE_TOP_LEVEL_COPY_LINK_ANDROID";
        o2 = new EnumC6196Lfg("ENABLE_TOP_LEVEL_COPY_LINK", 120, I53);
        p2 = new EnumC6196Lfg("CONTACT_RANKING_SESSION_ID", 121, QR1.R(""));
        AI3 I54 = QR1.I(true);
        I54.t = "ST_SECTION_TOP_PADDING_ENABLED_ANDROID";
        q2 = new EnumC6196Lfg("ST_SECTION_TOP_PADDING_ENABLED", 122, I54);
        AI3 I55 = QR1.I(false);
        I55.t = "SDL_BASED_HORIZONTAL_STORIES_SECTION_ENABLED_ANDROID";
        r2 = new EnumC6196Lfg("SDL_BASED_HORIZONTAL_STORIES_SECTION_ENABLED", 123, I55);
        AI3 I56 = QR1.I(false);
        I56.t = "ST_SHORTCUT_DOUBLE_TAP_FIX";
        s2 = new EnumC6196Lfg("ST_SHORTCUT_DOUBLE_TAP_FIX", 124, I56);
        AI3 I57 = QR1.I(false);
        I57.t = "ST_DISABLE_PAGE_ANIMATION";
        t2 = new EnumC6196Lfg("ST_DISABLE_PAGE_ANIMATION", 125, I57);
        AI3 I58 = QR1.I(false);
        I58.t = "ST_DISABLE_SECTION_ANIMATIONS";
        u2 = new EnumC6196Lfg("ST_DISABLE_SECTION_ANIMATIONS", 126, I58);
        AI3 I59 = QR1.I(false);
        I59.t = "ST_IS_NORMALIZED_SEARCH_DEBOUNCE_DISABLED";
        v2 = new EnumC6196Lfg("ST_IS_NORMALIZED_SEARCH_DEBOUNCE_DISABLED", 127, I59);
        AI3 I60 = QR1.I(false);
        I60.t = "SHOW_DISPLAY_NAME_FRIEND_IN_THIS_SNAP";
        w2 = new EnumC6196Lfg("SHOW_DISPLAY_NAME_FRIEND_IN_THIS_SNAP", 128, I60);
        AI3 I61 = QR1.I(false);
        I61.t = "ANDROID_AUTO_COPY_LINK_EXPORT";
        x2 = new EnumC6196Lfg("ANDROID_AUTO_COPY_LINK_EXPORT", 129, I61);
        AI3 I62 = QR1.I(false);
        I62.t = "REPLY_SECTION_GRID";
        y2 = new EnumC6196Lfg("REPLY_SECTION_GRID", 130, I62);
        AI3 I63 = QR1.I(false);
        I63.t = "AUTO_SCROLL_FOR_LAST_SNAP";
        z2 = new EnumC6196Lfg("AUTO_SCROLL_FOR_LAST_SNAP", 131, I63);
        AI3 M27 = QR1.M(0);
        M27.t = "PLACEMENT_AUTO_SCROLL";
        A2 = new EnumC6196Lfg("PLACEMENT_AUTO_SCROLL", 132, M27);
        AI3 I64 = QR1.I(false);
        I64.t = "REPLY_SECTION_AUTO_SCROLL";
        B2 = new EnumC6196Lfg("REPLY_SECTION_AUTO_SCROLL", 133, I64);
        AI3 I65 = QR1.I(false);
        I65.t = "STREAK_INFO_GET_FEATURE_REQUEST";
        C2 = new EnumC6196Lfg("STREAK_INFO_GET_FEATURE_REQUEST", 134, I65);
        AI3 I66 = QR1.I(false);
        I66.t = "POST_FRAGMENT_TRAY_SPOTLIGHT";
        D2 = new EnumC6196Lfg("POST_FRAGMENT_TRAY_SPOTLIGHT", 135, I66);
        AI3 I67 = QR1.I(false);
        I67.t = "SEND_TO_SECTION_PRELOAD_INFLATION";
        E2 = new EnumC6196Lfg("SEND_TO_SECTION_PRELOAD_INFLATION", 136, I67);
        AI3 I68 = QR1.I(false);
        I68.t = "SEND_TO_PREFETCHED_SECTION_VIEW_MAP_CLEANUP";
        F2 = new EnumC6196Lfg("SEND_TO_PREFETCHED_SECTION_VIEW_MAP_CLEANUP", 137, I68);
        AI3 I69 = QR1.I(false);
        I69.t = "SEND_TO_PREFETCHED_CONTENT_VIEW_CLEANUP";
        G2 = new EnumC6196Lfg("SEND_TO_PREFETCHED_CONTENT_VIEW_CLEANUP", 138, I69);
        AI3 I70 = QR1.I(false);
        I70.t = "SNAP_CODE_STORAGE_PERMISSION_NOTIFICATION";
        H2 = new EnumC6196Lfg("SNAP_CODE_STORAGE_PERMISSION_NOTIFICATION", 139, I70);
        AI3 I71 = QR1.I(false);
        I71.t = "SHOW_SNAPCODE_PERMISSION_SCREEN";
        I2 = new EnumC6196Lfg("SHOW_SNAPCODE_PERMISSION_SCREEN", Tweaks.SPONSORED_SNAPS_FEED_INSERT_MODE, I71);
        AI3 M28 = QR1.M(2);
        M28.t = "SEND_TO_SECTION_VIEW_PRELOAD_HEADER_COUNT";
        J2 = new EnumC6196Lfg("SEND_TO_SECTION_VIEW_PRELOAD_HEADER_COUNT", Tweaks.SPONSORED_SNAPS_USER_INPUT_MODE, M28);
        AI3 M29 = QR1.M(10);
        M29.t = "SEND_TO_SECTION_VIEW_PRELOAD_CELL_COUNT";
        K2 = new EnumC6196Lfg("SEND_TO_SECTION_VIEW_PRELOAD_CELL_COUNT", Tweaks.CALLBACK_FETCH_ON_FEED_DELEGATE, M29);
        AI3 M30 = QR1.M(4);
        M30.t = "SEND_TO_SECTION_VIEW_PRELOAD_TWIN_CELL_COUNT";
        L2 = new EnumC6196Lfg("SEND_TO_SECTION_VIEW_PRELOAD_TWIN_CELL_COUNT", Tweaks.CALLBACK_QUERY_ON_FEED_DELEGATE, M30);
        AI3 M31 = QR1.M(Integer.MAX_VALUE);
        M31.t = "SEND_TO_RANKING_RTUS_EVENT_MAX_BYTE_SIZE";
        M2 = new EnumC6196Lfg("SEND_TO_RANKING_RTUS_EVENT_MAX_BYTE_SIZE", Tweaks.CALLBACK_SYNC_ON_FEED_DELEGATE, M31);
        AI3 I72 = QR1.I(false);
        I72.t = "SEND_TO_COMPOSER_RANKING_FEATURE_ALLOWLIST_ENABLED_ANDROID";
        N2 = new EnumC6196Lfg("SEND_TO_COMPOSER_RANKING_FEATURE_ALLOWLIST_ENABLED_ANDROID", Tweaks.FEED_PAGINATION_V4_ENABLED, I72);
        AI3 I73 = QR1.I(false);
        I73.t = "ST_CREATE_POST_UPDATE_SPOTLIGHT_CELL";
        O2 = new EnumC6196Lfg("ST_CREATE_POST_UPDATE_SPOTLIGHT_CELL", Tweaks.AUTO_PAGINATE_QUERY_FEED_ENABLED, I73);
        AI3 I74 = QR1.I(false);
        I74.t = "ST_CREATE_POST_DISABLE_RESET_CELL_ON_DESELECTION";
        P2 = new EnumC6196Lfg("ST_CREATE_POST_DISABLE_RESET_CELL_ON_DESELECTION", Tweaks.AUTO_PAGINATE_QUERY_FEED_LITE_ENABLED, I74);
        AI3 I75 = QR1.I(true);
        I75.t = "SEND_TO_RANKING_SHOULD_USE_RECENTS_RANKING_SERVICE_ANDROID";
        Q2 = new EnumC6196Lfg("SEND_TO_RANKING_SHOULD_USE_RECENTS_RANKING_SERVICE_ANDROID", Tweaks.EXTENSION_DB_WAL_KILLSWITCH, I75);
        AI3 I76 = QR1.I(false);
        I76.t = "ST_SPOTLIGHT_ENABLE_MULTILINE_SUBTEXT";
        R2 = new EnumC6196Lfg("ST_SPOTLIGHT_ENABLE_MULTILINE_SUBTEXT", Tweaks.EXTENSION_FAIL_SYNC_WRITE_KILLSWITCH, I76);
        AI3 I77 = QR1.I(false);
        I77.t = "SEND_TO_STORIES_DEFAULT_FILTERING";
        S2 = new EnumC6196Lfg("SEND_TO_STORIES_DEFAULT_FILTERING", Tweaks.LOGIN_PREFETCH_MIN_ENTRIES, I77);
        AI3 I78 = QR1.I(false);
        I78.t = "ST_SPOTLIGHT_DEFAULT_NULL_THUMBNAIL";
        T2 = new EnumC6196Lfg("ST_SPOTLIGHT_DEFAULT_NULL_THUMBNAIL", Tweaks.LOGIN_PREFETCH_MAX_ENTRIES, I78);
        AI3 I79 = QR1.I(false);
        I79.t = "ST_PREVIEW_ENABLE_COPYLINK_BUTTON";
        U2 = new EnumC6196Lfg("ST_PREVIEW_ENABLE_COPYLINK_BUTTON", Tweaks.LOGIN_PREFETCH_PAGE_SIZE, I79);
        V2 = new EnumC6196Lfg[]{b, c, t, X, Y, Z, e0, f0, g0, h0, i0, j0, k0, l0, m0, n0, o0, p0, q0, r0, s0, t0, u0, v0, w0, x0, y0, z0, A0, B0, C0, D0, E0, F0, G0, H0, I0, J0, K0, L0, M0, N0, O0, P0, Q0, R0, S0, T0, U0, V0, W0, X0, Y0, Z0, a1, b1, c1, d1, e1, f1, g1, h1, i1, j1, k1, l1, m1, n1, o1, p1, q1, r1, s1, t1, u1, v1, w1, x1, y1, z1, A1, B1, C1, D1, E1, F1, G1, H1, I1, J1, K1, L1, M1, N1, O1, P1, Q1, R1, S1, T1, U1, V1, W1, X1, Y1, Z1, a2, b2, c2, d2, e2, f2, g2, h2, i2, j2, k2, l2, m2, n2, o2, p2, q2, r2, s2, t2, u2, v2, w2, x2, y2, z2, A2, B2, C2, D2, E2, F2, G2, H2, I2, J2, K2, L2, M2, N2, O2, P2, Q2, R2, S2, T2, U2};
    }

    public EnumC6196Lfg(String str, int i, AI3 ai3) {
        this.a = ai3;
    }

    public static EnumC6196Lfg valueOf(String str) {
        return (EnumC6196Lfg) Enum.valueOf(EnumC6196Lfg.class, str);
    }

    public static EnumC6196Lfg[] values() {
        return (EnumC6196Lfg[]) V2.clone();
    }

    @Override // defpackage.BI3
    public final EnumC48048zI3 e() {
        return EnumC48048zI3.Z;
    }

    @Override // defpackage.BI3
    public final String getName() {
        return name();
    }

    @Override // defpackage.BI3
    public final AI3 j() {
        return this.a;
    }
}
