package defpackage;

import com.amazon.identity.auth.map.device.AccountManagerConstants;
import com.snapchat.client.messaging.Tweaks;
import java.util.EnumSet;
import java.util.concurrent.TimeUnit;

/* JADX WARN: Enum visitor error
jadx.core.utils.exceptions.JadxRuntimeException: Init of enum field 'c' uses external variables
	at jadx.core.dex.visitors.EnumVisitor.createEnumFieldByConstructor(EnumVisitor.java:451)
	at jadx.core.dex.visitors.EnumVisitor.processEnumFieldByField(EnumVisitor.java:372)
	at jadx.core.dex.visitors.EnumVisitor.processEnumFieldByWrappedInsn(EnumVisitor.java:337)
	at jadx.core.dex.visitors.EnumVisitor.extractEnumFieldsFromFilledArray(EnumVisitor.java:322)
	at jadx.core.dex.visitors.EnumVisitor.extractEnumFieldsFromInsn(EnumVisitor.java:262)
	at jadx.core.dex.visitors.EnumVisitor.extractEnumFieldsFromInvoke(EnumVisitor.java:293)
	at jadx.core.dex.visitors.EnumVisitor.extractEnumFieldsFromInsn(EnumVisitor.java:266)
	at jadx.core.dex.visitors.EnumVisitor.convertToEnum(EnumVisitor.java:151)
	at jadx.core.dex.visitors.EnumVisitor.visit(EnumVisitor.java:100)
 */
/* JADX WARN: Failed to restore enum class, 'enum' modifier and super class removed */
/* renamed from: Aba, reason: case insensitive filesystem */
/* loaded from: classes.dex */
public final class EnumC0091Aba implements S4f {
    public static final EnumC0091Aba A0;
    public static final EnumC0091Aba A1;
    public static final EnumC0091Aba A2;
    public static final EnumC0091Aba A3;
    public static final EnumC0091Aba A4;
    public static final EnumC0091Aba A5;
    public static final EnumC0091Aba B0;
    public static final EnumC0091Aba B1;
    public static final EnumC0091Aba B2;
    public static final EnumC0091Aba B3;
    public static final EnumC0091Aba B4;
    public static final EnumC0091Aba B5;
    public static final EnumC0091Aba C0;
    public static final EnumC0091Aba C1;
    public static final EnumC0091Aba C2;
    public static final EnumC0091Aba C3;
    public static final EnumC0091Aba C4;
    public static final EnumC0091Aba C5;
    public static final EnumC0091Aba D0;
    public static final EnumC0091Aba D1;
    public static final EnumC0091Aba D2;
    public static final EnumC0091Aba D3;
    public static final EnumC0091Aba D4;
    public static final EnumC0091Aba D5;
    public static final EnumC0091Aba E0;
    public static final EnumC0091Aba E1;
    public static final EnumC0091Aba E2;
    public static final EnumC0091Aba E3;
    public static final EnumC0091Aba E4;
    public static final EnumC0091Aba E5;
    public static final EnumC0091Aba F0;
    public static final EnumC0091Aba F1;
    public static final EnumC0091Aba F2;
    public static final EnumC0091Aba F3;
    public static final EnumC0091Aba F4;
    public static final EnumC0091Aba F5;
    public static final EnumC0091Aba G0;
    public static final EnumC0091Aba G1;
    public static final EnumC0091Aba G2;
    public static final EnumC0091Aba G3;
    public static final EnumC0091Aba G4;
    public static final EnumC0091Aba G5;
    public static final EnumC0091Aba H0;
    public static final EnumC0091Aba H1;
    public static final EnumC0091Aba H2;
    public static final EnumC0091Aba H3;
    public static final EnumC0091Aba H4;
    public static final EnumC0091Aba H5;
    public static final EnumC0091Aba I0;
    public static final EnumC0091Aba I1;
    public static final EnumC0091Aba I2;
    public static final EnumC0091Aba I3;
    public static final EnumC0091Aba I4;
    public static final EnumC0091Aba I5;
    public static final EnumC0091Aba J0;
    public static final EnumC0091Aba J1;
    public static final EnumC0091Aba J2;
    public static final EnumC0091Aba J3;
    public static final EnumC0091Aba J4;
    public static final EnumC0091Aba J5;
    public static final EnumC0091Aba K0;
    public static final EnumC0091Aba K1;
    public static final EnumC0091Aba K2;
    public static final EnumC0091Aba K3;
    public static final EnumC0091Aba K4;
    public static final EnumC0091Aba K5;
    public static final EnumC0091Aba L0;
    public static final EnumC0091Aba L1;
    public static final EnumC0091Aba L2;
    public static final EnumC0091Aba L3;
    public static final EnumC0091Aba L4;
    public static final EnumC0091Aba L5;
    public static final EnumC0091Aba M0;
    public static final EnumC0091Aba M1;
    public static final EnumC0091Aba M2;
    public static final EnumC0091Aba M3;
    public static final EnumC0091Aba M4;
    public static final EnumC0091Aba M5;
    public static final EnumC0091Aba N0;
    public static final EnumC0091Aba N1;
    public static final EnumC0091Aba N2;
    public static final EnumC0091Aba N3;
    public static final EnumC0091Aba N4;
    public static final EnumC0091Aba N5;
    public static final EnumC0091Aba O0;
    public static final EnumC0091Aba O1;
    public static final EnumC0091Aba O2;
    public static final EnumC0091Aba O3;
    public static final EnumC0091Aba O4;
    public static final EnumC0091Aba O5;
    public static final EnumC0091Aba P0;
    public static final EnumC0091Aba P1;
    public static final EnumC0091Aba P2;
    public static final EnumC0091Aba P3;
    public static final EnumC0091Aba P4;
    public static final EnumC0091Aba P5;
    public static final EnumC0091Aba Q0;
    public static final EnumC0091Aba Q1;
    public static final EnumC0091Aba Q2;
    public static final EnumC0091Aba Q3;
    public static final EnumC0091Aba Q4;
    public static final EnumC0091Aba Q5;
    public static final EnumC0091Aba R0;
    public static final EnumC0091Aba R1;
    public static final EnumC0091Aba R2;
    public static final EnumC0091Aba R3;
    public static final EnumC0091Aba R4;
    public static final /* synthetic */ EnumC0091Aba[] R5;
    public static final EnumC0091Aba S0;
    public static final EnumC0091Aba S1;
    public static final EnumC0091Aba S2;
    public static final EnumC0091Aba S3;
    public static final EnumC0091Aba S4;
    public static final EnumC0091Aba T0;
    public static final EnumC0091Aba T1;
    public static final EnumC0091Aba T2;
    public static final EnumC0091Aba T3;
    public static final EnumC0091Aba T4;
    public static final EnumC0091Aba U0;
    public static final EnumC0091Aba U1;
    public static final EnumC0091Aba U2;
    public static final EnumC0091Aba U3;
    public static final EnumC0091Aba U4;
    public static final EnumC0091Aba V0;
    public static final EnumC0091Aba V1;
    public static final EnumC0091Aba V2;
    public static final EnumC0091Aba V3;
    public static final EnumC0091Aba V4;
    public static final EnumC0091Aba W0;
    public static final EnumC0091Aba W1;
    public static final EnumC0091Aba W2;
    public static final EnumC0091Aba W3;
    public static final EnumC0091Aba W4;
    public static final EnumC0091Aba X;
    public static final EnumC0091Aba X0;
    public static final EnumC0091Aba X1;
    public static final EnumC0091Aba X2;
    public static final EnumC0091Aba X3;
    public static final EnumC0091Aba X4;
    public static final EnumC0091Aba Y;
    public static final EnumC0091Aba Y0;
    public static final EnumC0091Aba Y1;
    public static final EnumC0091Aba Y2;
    public static final EnumC0091Aba Y3;
    public static final EnumC0091Aba Y4;
    public static final EnumC0091Aba Z;
    public static final EnumC0091Aba Z0;
    public static final EnumC0091Aba Z1;
    public static final EnumC0091Aba Z2;
    public static final EnumC0091Aba Z3;
    public static final EnumC0091Aba Z4;
    public static final EnumC0091Aba a1;
    public static final EnumC0091Aba a2;
    public static final EnumC0091Aba a3;
    public static final EnumC0091Aba a4;
    public static final EnumC0091Aba a5;
    public static final EnumC0091Aba b1;
    public static final EnumC0091Aba b2;
    public static final EnumC0091Aba b3;
    public static final EnumC0091Aba b4;
    public static final EnumC0091Aba b5;
    public static final EnumC0091Aba c;
    public static final EnumC0091Aba c1;
    public static final EnumC0091Aba c2;
    public static final EnumC0091Aba c3;
    public static final EnumC0091Aba c4;
    public static final EnumC0091Aba c5;
    public static final EnumC0091Aba d1;
    public static final EnumC0091Aba d2;
    public static final EnumC0091Aba d3;
    public static final EnumC0091Aba d4;
    public static final EnumC0091Aba d5;
    public static final EnumC0091Aba e0;
    public static final EnumC0091Aba e1;
    public static final EnumC0091Aba e2;
    public static final EnumC0091Aba e3;
    public static final EnumC0091Aba e4;
    public static final EnumC0091Aba e5;
    public static final EnumC0091Aba f0;
    public static final EnumC0091Aba f1;
    public static final EnumC0091Aba f2;
    public static final EnumC0091Aba f3;
    public static final EnumC0091Aba f4;
    public static final EnumC0091Aba f5;
    public static final EnumC0091Aba g0;
    public static final EnumC0091Aba g1;
    public static final EnumC0091Aba g2;
    public static final EnumC0091Aba g3;
    public static final EnumC0091Aba g4;
    public static final EnumC0091Aba g5;
    public static final EnumC0091Aba h0;
    public static final EnumC0091Aba h1;
    public static final EnumC0091Aba h2;
    public static final EnumC0091Aba h3;
    public static final EnumC0091Aba h4;
    public static final EnumC0091Aba h5;
    public static final EnumC0091Aba i0;
    public static final EnumC0091Aba i1;
    public static final EnumC0091Aba i2;
    public static final EnumC0091Aba i3;
    public static final EnumC0091Aba i4;
    public static final EnumC0091Aba i5;
    public static final EnumC0091Aba j0;
    public static final EnumC0091Aba j1;
    public static final EnumC0091Aba j2;
    public static final EnumC0091Aba j3;
    public static final EnumC0091Aba j4;
    public static final EnumC0091Aba j5;
    public static final EnumC0091Aba k0;
    public static final EnumC0091Aba k1;
    public static final EnumC0091Aba k2;
    public static final EnumC0091Aba k3;
    public static final EnumC0091Aba k4;
    public static final EnumC0091Aba k5;
    public static final EnumC0091Aba l0;
    public static final EnumC0091Aba l1;
    public static final EnumC0091Aba l2;
    public static final EnumC0091Aba l3;
    public static final EnumC0091Aba l4;
    public static final EnumC0091Aba l5;
    public static final EnumC0091Aba m0;
    public static final EnumC0091Aba m1;
    public static final EnumC0091Aba m2;
    public static final EnumC0091Aba m3;
    public static final EnumC0091Aba m4;
    public static final EnumC0091Aba m5;
    public static final EnumC0091Aba n0;
    public static final EnumC0091Aba n1;
    public static final EnumC0091Aba n2;
    public static final EnumC0091Aba n3;
    public static final EnumC0091Aba n4;
    public static final EnumC0091Aba n5;
    public static final EnumC0091Aba o0;
    public static final EnumC0091Aba o1;
    public static final EnumC0091Aba o2;
    public static final EnumC0091Aba o3;
    public static final EnumC0091Aba o4;
    public static final EnumC0091Aba o5;
    public static final EnumC0091Aba p0;
    public static final EnumC0091Aba p1;
    public static final EnumC0091Aba p2;
    public static final EnumC0091Aba p3;
    public static final EnumC0091Aba p4;
    public static final EnumC0091Aba p5;
    public static final EnumC0091Aba q0;
    public static final EnumC0091Aba q1;
    public static final EnumC0091Aba q2;
    public static final EnumC0091Aba q3;
    public static final EnumC0091Aba q4;
    public static final EnumC0091Aba q5;
    public static final EnumC0091Aba r0;
    public static final EnumC0091Aba r1;
    public static final EnumC0091Aba r2;
    public static final EnumC0091Aba r3;
    public static final EnumC0091Aba r4;
    public static final EnumC0091Aba r5;
    public static final EnumC0091Aba s0;
    public static final EnumC0091Aba s1;
    public static final EnumC0091Aba s2;
    public static final EnumC0091Aba s3;
    public static final EnumC0091Aba s4;
    public static final EnumC0091Aba s5;
    public static final EnumC0091Aba t;
    public static final EnumC0091Aba t0;
    public static final EnumC0091Aba t1;
    public static final EnumC0091Aba t2;
    public static final EnumC0091Aba t3;
    public static final EnumC0091Aba t4;
    public static final EnumC0091Aba t5;
    public static final EnumC0091Aba u0;
    public static final EnumC0091Aba u1;
    public static final EnumC0091Aba u2;
    public static final EnumC0091Aba u3;
    public static final EnumC0091Aba u4;
    public static final EnumC0091Aba u5;
    public static final EnumC0091Aba v0;
    public static final EnumC0091Aba v1;
    public static final EnumC0091Aba v2;
    public static final EnumC0091Aba v3;
    public static final EnumC0091Aba v4;
    public static final EnumC0091Aba v5;
    public static final EnumC0091Aba w0;
    public static final EnumC0091Aba w1;
    public static final EnumC0091Aba w2;
    public static final EnumC0091Aba w3;
    public static final EnumC0091Aba w4;
    public static final EnumC0091Aba w5;
    public static final EnumC0091Aba x0;
    public static final EnumC0091Aba x1;
    public static final EnumC0091Aba x2;
    public static final EnumC0091Aba x3;
    public static final EnumC0091Aba x4;
    public static final EnumC0091Aba x5;
    public static final EnumC0091Aba y0;
    public static final EnumC0091Aba y1;
    public static final EnumC0091Aba y2;
    public static final EnumC0091Aba y3;
    public static final EnumC0091Aba y4;
    public static final EnumC0091Aba y5;
    public static final EnumC0091Aba z0;
    public static final EnumC0091Aba z1;
    public static final EnumC0091Aba z2;
    public static final EnumC0091Aba z3;
    public static final EnumC0091Aba z4;
    public static final EnumC0091Aba z5;
    public final AI3 a;
    public final EnumSet b;

    static {
        AI3 l = AI3.l("");
        l.n("CONFIGS_TO_READ_ONLY_ONCE");
        EnumSet enumSet = R4f.a;
        c = new EnumC0091Aba("SINGLE_READ_CONFIGS", 0, l, enumSet);
        AI3 a = AI3.a(false);
        a.n("USE_SINGLE_READ_CONFIGS");
        t = new EnumC0091Aba("USE_SINGLE_READ_CONFIGS", 1, a, enumSet);
        AI3 a6 = AI3.a(false);
        a6.s(278);
        EnumSet enumSet2 = R4f.b;
        X = new EnumC0091Aba("CAMERA_LENSES_ACTIVATED", 2, a6, enumSet2);
        Y = new EnumC0091Aba("CAMERA_ONBOARDING_CAROUSEL_SWIPE_TOOLTIP_SHOWN", 3, AI3.a(false), enumSet2);
        Z = new EnumC0091Aba("CAMERA_ONBOARDING_CAROUSEL_CAPTURE_TOOLTIP_SHOWN", 4, AI3.a(false), enumSet2);
        AI3 a7 = AI3.a(true);
        a7.n("LENSES_ONBOARDING_TOOLTIP_ENABLED");
        e0 = new EnumC0091Aba("LENSES_ONBOARDING_TOOLTIP_ENABLED", 5, a7, enumSet);
        AI3 a8 = AI3.a(false);
        a8.s(247);
        f0 = new EnumC0091Aba("LENSES_FAVORITES_TOOLTIP_SHOWN", 6, a8, enumSet2);
        AI3 a9 = AI3.a(false);
        a9.n("GROWTH_NOTIFICATION_LENS_TRAY_ACTIONS_ENABLED");
        g0 = new EnumC0091Aba("GROWTH_NOTIFICATION_LENS_TRAY_ACTIONS_ENABLED", 7, a9, enumSet);
        AI3 d = AI3.d(EnumC23123gei.a);
        d.n("LENSES_CAROUSEL_SCHEDULE_ON_CAMERA_FLIP_ANDROID");
        h0 = new EnumC0091Aba("CAMERA_CAROUSEL_SWITCH_SCHEDULE_ON_CAMERA_FLIP_MODE", 8, d, enumSet);
        AI3 d6 = AI3.d(EnumC21159fB1.a);
        d6.n("LENSES_CAROUSEL_BUNDLED_LENS_STATUS");
        i0 = new EnumC0091Aba("CAMERA_CAROUSEL_BUNDLED_LENSES_STATUS", 9, d6, enumSet2);
        j0 = new EnumC0091Aba("CAMERA_CAROUSEL_BUNDLED_LENSES_LOADED_LENSES_THRESHOLD", 10, AI3.g(3), enumSet2);
        AI3 h = AI3.h(1000L);
        h.n("CAMERA_CAROUSEL_BUNDLED_LENSES_ON_EMPTY_TIMEOUT_MS");
        k0 = new EnumC0091Aba("CAMERA_CAROUSEL_BUNDLED_LENSES_DELAY", 11, h, enumSet2);
        l0 = new EnumC0091Aba("CAMERA_BROWSE_CAROUSEL_EXPLORER_ENTRY_POINT_ENABLED", 12, AI3.a(true), enumSet);
        m0 = new EnumC0091Aba("LENS_EXPLORER_REPLY_CAMERA_ENTRY_POINT_ENABLED", 13, AI3.a(true), enumSet);
        n0 = new EnumC0091Aba("LENS_CAROUSEL_DOWNLOAD_STATES_ANIMATION_ENABLED", 14, AI3.a(true), enumSet);
        o0 = new EnumC0091Aba("LENSES_DEBUG_MODE", 15, AI3.d(EnumC34874pR9.a), enumSet2);
        AI3 a10 = AI3.a(false);
        a10.n("LENS_STUDIO_DETAILED_CLIENT_LOGGING_ENABLED");
        p0 = new EnumC0091Aba("ENABLE_LENS_DEBUGGING_FOR_STUDIO_PREVIEW", 16, a10, enumSet);
        AI3 g = AI3.g(20);
        g.n("LensCoreBenchmarkAttempts");
        q0 = new EnumC0091Aba("LENSCORE_BENCHMARK_ATTEMPTS", 17, g, enumSet);
        r0 = new EnumC0091Aba("LENSCORE_PROFILING_METHOD", 18, AI3.d(TZ9.a), enumSet);
        AI3 d7 = AI3.d(UZ9.a);
        d7.p("LENS_PRODUCTION_CPU_PERFORMANCE_PROFILING", "profiling_mode");
        s0 = new EnumC0091Aba("LENSCORE_PROFILING_MODE", 19, d7, enumSet);
        AI3 l6 = AI3.l("");
        l6.n("LENS_FRIEND_BASED_LOCKER_CONFIG");
        t0 = new EnumC0091Aba("CAMERA_LENS_LOCKING_CONFIGURATION", 20, l6, enumSet);
        AI3 a11 = AI3.a(false);
        a11.n("LENS_FRIEND_BASED_LOCKER_CTA_COUNTDOWN");
        u0 = new EnumC0091Aba("CAMERA_LENS_LOCKING_CTA_COUNTDOWN_ENABLED", 21, a11, enumSet);
        AI3 h6 = AI3.h(0L);
        h6.s(237);
        v0 = new EnumC0091Aba("CAMERA_LENS_LOCKING_FIRST_IMPRESSION_TIMESTAMP", 22, h6, enumSet2);
        w0 = new EnumC0091Aba("CAMERA_CAROUSEL_ITEM_DEBUG_OVERLAY", 23, AI3.d(EnumC27075jc5.a), enumSet);
        AI3 d8 = AI3.d(EnumC36377qZ9.b);
        d8.n("LENS_PREFETCH_LIFECYCLE");
        x0 = new EnumC0091Aba("LENS_PREFETCH_LIFECYCLE", 24, d8, enumSet);
        AI3 b = AI3.b(new byte[0]);
        b.n("LENSES_ANDROID_SIGNUP_PREFETCH_EXTENDED");
        y0 = new EnumC0091Aba("LENSES_SIGNUP_PREFETCH", 25, b, enumSet);
        AI3 b6 = AI3.b(new byte[0]);
        b6.n("LENSES_SUSPEND_CONFIGURATION_ANDROID");
        z0 = new EnumC0091Aba("LENSES_CAMERA_SUSPEND_CONFIGURATION", 26, b6, enumSet);
        A0 = new EnumC0091Aba("EXTERNAL_PAGE_LOAD_ON_CRITICAL_SECTION", 27, AI3.a(false), enumSet);
        B0 = new EnumC0091Aba("LENS_PREFETCH_FORCE_UCO_ON_DEMAND_CONFIG", 28, AI3.a(false), enumSet);
        AI3 b7 = AI3.b(new byte[0]);
        b7.n("LENS_PREFETCH_UCO_ON_DEMAND_CONFIG");
        C0 = new EnumC0091Aba("LENS_PREFETCH_UCO_ON_DEMAND_CONFIG", 29, b7, enumSet);
        D0 = new EnumC0091Aba("LENS_PREFETCH_FORCE_PREFETCH_COMPONENET", 30, AI3.a(false), enumSet);
        E0 = new EnumC0091Aba("LENS_PREFETCH_FORCE_RESOURCE_RESOLVER", 31, AI3.a(false), enumSet);
        AI3 b8 = AI3.b(new byte[0]);
        b8.n("LENS_PREFETCH_PRIORITIZED_PAYLOAD_RESOLVER_CONFIG");
        F0 = new EnumC0091Aba("LENS_PREFETCH_PRIORITIZED_PAYLOAD_RESOLVER_CONFIG", 32, b8, enumSet);
        AI3 a12 = AI3.a(true);
        a12.n("LENS_PREFETCH_FIX_VISIBLE_LENSES_REPORTING");
        G0 = new EnumC0091Aba("LENS_PREFETCH_FIX_VISIBLE_LENSES_REPORTING", 33, a12, enumSet);
        H0 = new EnumC0091Aba("PREVIEW_CAROUSEL_CONSOLIDATION_COLLAPSIBLE_ENABLED", 34, AI3.a(true), enumSet);
        AI3 a13 = AI3.a(false);
        a13.n("LENSES_PREFETCH_USERVISIBLE_RETRIGGER");
        I0 = new EnumC0091Aba("LENS_PREFETCH_RESUBMIT_USERVISIBLE", 35, a13, enumSet);
        AI3 h7 = AI3.h(0L);
        h7.n("LENS_PREFETCH_DEBOUNCE_REQUEST_MS");
        J0 = new EnumC0091Aba("LENS_PREFETCH_DEBOUNCE_REQUEST_MS", 36, h7, enumSet);
        AI3 a14 = AI3.a(false);
        a14.n("LENS_DISPOSE_IMMEDIATELY_NON_USER_VISIBLE_REQUESTS");
        K0 = new EnumC0091Aba("LENS_DISPOSE_IMMEDIATELY_NON_USER_VISIBLE_REQUEST", 37, a14, enumSet);
        AI3 a15 = AI3.a(false);
        a15.n("LENS_DISPOSE_IMMEDIATELY_OLD_REQUESTS");
        L0 = new EnumC0091Aba("LENS_DISPOSE_IMMEDIATELY_OLD_REQUESTS", 38, a15, enumSet);
        M0 = new EnumC0091Aba("NATIVE_LOGS_ENABLED", 39, AI3.a(true), enumSet2);
        AI3 g6 = AI3.g(-1);
        g6.n("LENS_FEATURE_DEVICE_CLASS");
        N0 = new EnumC0091Aba("FEATURE_GATING_DEVICE_CLASS", 40, g6, enumSet);
        AI3 g7 = AI3.g(-1);
        g7.n("LENS_FEATURE_GPU_INDEX");
        O0 = new EnumC0091Aba("FEATURE_GATING_GPU_INDEX", 41, g7, enumSet);
        AI3 h8 = AI3.h(4123168604700L);
        h8.n("LENS_IMG_RES_PROCESSING");
        P0 = new EnumC0091Aba("PROCESSING_IMAGE_RESOLUTION", 42, h8, enumSet);
        AI3 h9 = AI3.h(4123168604700L);
        h9.n("LENS_IMG_RES_PROCESSING_V2");
        Q0 = new EnumC0091Aba("PROCESSING_IMAGE_RESOLUTION_V2", 43, h9, enumSet);
        AI3 a16 = AI3.a(false);
        a16.n("LENS_IMG_RES_PROCESSING_AB_23_10_31");
        R0 = new EnumC0091Aba("PROCESSING_IMAGE_RESOLUTION_AB", 44, a16, enumSet);
        AI3 h10 = AI3.h(8246337209400L);
        h10.n("LENS_CAPTURED_IMG_RES_PROCESSING");
        S0 = new EnumC0091Aba("PROCESSING_CAPTURED_IMAGE_RESOLUTION", 45, h10, enumSet);
        AI3 b9 = AI3.b(new byte[0]);
        b9.n("LENS_PROCESS_RESOLUTION_UPDATE_CONFIG");
        T0 = new EnumC0091Aba("LENS_PROCESS_RESOLUTION_UPDATE_CONFIG", 46, b9, enumSet);
        U0 = new EnumC0091Aba("LENS_GEO_ENABLED", 47, AI3.a(true), enumSet);
        V0 = new EnumC0091Aba("LENS_UNLOCKED_ENABLED", 48, AI3.a(true), enumSet);
        W0 = new EnumC0091Aba("SPONSORED_LENS_ENABLED", 49, AI3.a(true), enumSet);
        X0 = new EnumC0091Aba("CONNECTED_LENSES_ENABLED", 50, AI3.a(true), enumSet);
        Y0 = new EnumC0091Aba("GENERATIVE_AI_LENSES_ENABLED", 51, AI3.a(true), enumSet);
        Z0 = new EnumC0091Aba("OVERRIDE_CAPTURE_BUTTON_LENSES_ENABLED", 52, AI3.a(true), enumSet);
        a1 = new EnumC0091Aba("LENSES_WITH_ABSOLUTE_POSITION_ENABLED", 53, AI3.a(true), enumSet);
        AI3 a17 = AI3.a(false);
        a17.p("SNAP_3D_VIEWING", "Enabled");
        b1 = new EnumC0091Aba("SNAP3D_VIEWING_ENABLED", 54, a17, enumSet);
        AI3 a18 = AI3.a(false);
        a18.n("ENABLE_SNAPPABLE_METADATA_FETCHER");
        c1 = new EnumC0091Aba("ENABLE_SNAPPABLE_METADATA_FETCHER", 55, a18, enumSet);
        d1 = new EnumC0091Aba("INFO_BUTTON_FOR_ALL", 56, AI3.a(false), enumSet);
        e1 = new EnumC0091Aba("INFO_CARD_CUSTOM_SERVICE_ROUTE_TAG", 57, AI3.l(""), enumSet2);
        f1 = new EnumC0091Aba("INFO_CARD_CUSTOM_BASE_URL", 58, AI3.l(""), enumSet);
        g1 = new EnumC0091Aba("INFO_CARD_VIEW_TOPIC_ENABLED", 59, AI3.a(true), enumSet2);
        AI3 a19 = AI3.a(true);
        a19.n("LENS_EXPERIENCE_INFOCARD_REMOVE_AFTER_REPORT_ALLOWED_ANDROID");
        h1 = new EnumC0091Aba("INFO_CARD_REMOVE_LENS_AFTER_REPORT", 60, a19, enumSet2);
        i1 = new EnumC0091Aba("POST_LENS_FAVORITING_SHARE_PROMPT", 61, AI3.g(0), enumSet);
        j1 = new EnumC0091Aba("UPCOMING_MESSAGE_ENABLED", 62, AI3.a(true), enumSet);
        k1 = new EnumC0091Aba("NATIVE_PROFILER_ENABLED", 63, AI3.a(false), enumSet);
        l1 = new EnumC0091Aba("BITMOJI_POPUP_ENABLED", 64, AI3.a(true), enumSet);
        AI3 g8 = AI3.g(1);
        g8.n("LENS_EXPLORER_MEDIA_PREVIEW_FRAME_LIMIT");
        m1 = new EnumC0091Aba("LENS_EXPLORER_ANIMATED_PREVIEW_FRAME_LIMIT", 65, g8, enumSet);
        TimeUnit timeUnit = TimeUnit.DAYS;
        n1 = new EnumC0091Aba("LENS_EXPLORER_BADGE_SHOW_INTERVAL_MINUTES", 66, AI3.h(timeUnit.toMinutes(1L)), enumSet);
        o1 = new EnumC0091Aba("LENS_EXPLORER_SHOWN_FROM_ACTION_LAST_TIME_MILLIS", 67, AI3.h(0L), enumSet2);
        p1 = new EnumC0091Aba("LENS_EXPLORER_TOOLTIP_SHOWN_TIMES_MAX", 68, AI3.g(1), enumSet);
        q1 = new EnumC0091Aba("LENS_EXPLORER_AR_BAR_DEFAULT_CATEGORY", 69, AI3.l(""), enumSet2);
        r1 = new EnumC0091Aba("LENS_EXPLORER_AR_BAR_REPLY_DEFAULT_CATEGORY", 70, AI3.l(""), enumSet2);
        AI3 l7 = AI3.l("");
        l7.n("LENS_EXPLORER_AR_BAR_SNAPCHAT_PLUS_CATEGORIES_ANDROID");
        s1 = new EnumC0091Aba("LENS_EXPLORER_AR_BAR_SNAP_PLUS_CATEGORIES", 71, l7, enumSet2);
        t1 = new EnumC0091Aba("LENS_EXPLORER_HINT_ENABLED_FOR_ALL", 72, AI3.a(false), enumSet);
        AI3 a20 = AI3.a(false);
        a20.s(435);
        u1 = new EnumC0091Aba("LENS_EXPLORER_HINT_WAS_SHOWN", 73, a20, enumSet2);
        AI3 g9 = AI3.g(0);
        g9.s(244);
        v1 = new EnumC0091Aba("LENS_EXPLORER_FAVORITES_CAROUSEL_COUNTER", 74, g9, enumSet2);
        AI3 l8 = AI3.l("");
        l8.n("LENS_EXPLORER_CUSTOM_ROUTE_TAG_ANDROID");
        w1 = new EnumC0091Aba("LENS_EXPLORER_CUSTOM_LENSES_SERVICE_ROUTE_TAG", 75, l8, enumSet);
        AI3 a21 = AI3.a(false);
        a21.n("LENS_EXPLORER_GRPC_ENABLED_ANDROID");
        x1 = new EnumC0091Aba("LENS_EXPLORER_USE_GRPC", 76, a21, enumSet);
        AI3 a22 = AI3.a(false);
        a22.n("LENS_EXPERIENCE_ENABLE_LENS_EXPLORER_DATA_POOL_ANDROID");
        y1 = new EnumC0091Aba("LENS_EXPLORER_ENABLE_DATA_POOL", 77, a22, enumSet);
        AI3 l9 = AI3.l("");
        l9.n("LE_CUSTOM_BASE_URL");
        z1 = new EnumC0091Aba("LENS_EXPLORER_CUSTOM_BASE_URL", 78, l9, enumSet);
        A1 = new EnumC0091Aba("LENS_EXPLORER_CUSTOM_COUNTRY_CODE", 79, AI3.l(""), enumSet);
        B1 = new EnumC0091Aba("LENS_EXPLORER_RESPONSE_LOGGING_ENABLED", 80, AI3.a(false), enumSet);
        AI3 a23 = AI3.a(false);
        a23.p("LE_CYCLED_CAROUSEL_AND_END_ENTRYPOINT_ANDROID", "content_previews_animation_enabled");
        C1 = new EnumC0091Aba("LENS_EXPLORER_CONTENT_PREVIEWS_ANIMATION_ENABLED", 81, a23, enumSet);
        AI3 a24 = AI3.a(false);
        a24.n("LENS_EXPERIENCE_LE_CONTENT_PREVIEWS_PREFETCH_DISABLED_ANDROID");
        D1 = new EnumC0091Aba("LENS_EXPERIENCE_LE_CONTENT_PREVIEWS_PREFETCH_DISABLED", 82, a24, enumSet);
        AI3 g10 = AI3.g(Integer.MAX_VALUE);
        g10.p("LENSES_ANDROID_FAVORITES_ON_TOP", "lenses_limit");
        E1 = new EnumC0091Aba("LensesFavoritesInCarouselLimit", 83, g10, enumSet);
        F1 = new EnumC0091Aba("LENS_EXPLORER_FAKE_CATEGORY", 84, AI3.a(false), enumSet);
        G1 = new EnumC0091Aba("EXPLORER_VIA_SWIPE_IN_PREVIEW", 85, AI3.a(false), enumSet);
        H1 = new EnumC0091Aba("LENSES_BACKGROUND_PREFETCH_DELAY_MINUTES", 86, AI3.h(-1L), enumSet);
        AI3 h11 = AI3.h(5L);
        h11.n("LENSES_BACKGROUND_PREFETCH_TAKE_DELAY_SECONDS");
        I1 = new EnumC0091Aba("LENSES_BACKGROUND_PREFETCH_TAKE_DELAY_SECONDS", 87, h11, enumSet);
        J1 = new EnumC0091Aba("LENSES_CAROUSEL_FOREGROUND_PREFETCH_FORCE_DISABLED", 88, AI3.a(false), enumSet);
        AI3 a25 = AI3.a(false);
        a25.n("LENSES_CAROUSEL_UCO_REPLY_CAMERA_NAMESPACE_ENABLED_ANDROID");
        K1 = new EnumC0091Aba("LENSES_CAROUSEL_UCO_REPLY_CAMERA_NAMESPACE_ENABLED", 89, a25, enumSet);
        AI3 a26 = AI3.a(false);
        a26.n("LENSES_CAROUSEL_PLACEHOLDERS_PREWARM");
        L1 = new EnumC0091Aba("LENSES_CAROUSEL_PLACEHOLDERS_PREWARM", 90, a26, enumSet);
        AI3 a27 = AI3.a(false);
        a27.n("LENS_EXPERIENCE_DISABLE_ALL_LENSES_ANDROID");
        M1 = new EnumC0091Aba("LENS_DISABLE_LENSES", 91, a27, enumSet);
        N1 = new EnumC0091Aba("GL_VERSION_REPORTED", 92, AI3.a(false), enumSet2);
        AI3 d9 = AI3.d(EnumC0718Bfa.a);
        d9.n("LENSES_PREFETCH_PASSIVE_PREFETCH_MODE");
        O1 = new EnumC0091Aba("LENSES_PREFETCH_PASSIVE_PREFETCH_MODE", 93, d9, enumSet);
        AI3 a28 = AI3.a(false);
        a28.n("ENABLE_EDGE_CACHE_STORY_DOWNLOADS");
        P1 = new EnumC0091Aba("ENABLE_EDGE_CACHE_STORY_DOWNLOADS", 94, a28, enumSet);
        Q1 = new EnumC0091Aba("FORCE_TO_USE_SW_RECORDING", 95, AI3.a(false), enumSet);
        AI3 a29 = AI3.a(false);
        a29.p("LENS_ASSETS_INSTANT_ACCESS_ANDROID", "enabled");
        R1 = new EnumC0091Aba("LENSES_RETAIN_LENS_ASSETS", 96, a29, enumSet);
        AI3 d10 = AI3.d(TM9.a);
        d10.p("LENS_APPLY_WAIT_FOR_LOAD", "mode");
        S1 = new EnumC0091Aba("LENSES_APPLY_WAIT_FOR_LOAD", 97, d10, enumSet);
        T1 = new EnumC0091Aba("LENSES_PERSISTENT_STORE_EXPIRATION_TIME_IN_MINUTES", 98, AI3.h(timeUnit.toMinutes(60L)), enumSet);
        AI3 a30 = AI3.a(true);
        a30.p("SCAN_UTILITY_LENS_AFFORDANCES_ANDROID", "enabled");
        U1 = new EnumC0091Aba("UTILITY_LENS_TAP_ENABLED", 99, a30, enumSet);
        V1 = new EnumC0091Aba("NOTIFICATION_DISPLAY_TIME_MILLIS", 100, AI3.h(3000L), enumSet);
        W1 = new EnumC0091Aba("LENSES_SOCIAL_UNLOCK_AFTER_USE_ENABLED", 101, AI3.a(true), enumSet);
        X1 = new EnumC0091Aba("LENS_TO_UNLOCK_AFTER_USE", 102, AI3.l(""), enumSet2);
        Y1 = new EnumC0091Aba("SNAP_ID_FOR_LENS_UNLOCK", 103, AI3.l(""), enumSet2);
        Z1 = new EnumC0091Aba("UNLOCKABLES_SNAP_INFO_FOR_LENS_UNLOCK", 104, AI3.l(""), enumSet2);
        a2 = new EnumC0091Aba("UNLOCKABLES_UNLOCK_SOURCE_FOR_LENS_UNLOCK", 105, AI3.l(""), enumSet2);
        b2 = new EnumC0091Aba("LENS_NEW_INFO_CARD_SHOW_ATTRIBUTION_INFINITELY", 106, AI3.a(false), enumSet);
        c2 = new EnumC0091Aba("LENS_USE_AR_CORE_FOR_WORLD_TRACKING", 107, AI3.a(true), enumSet);
        AI3 a31 = AI3.a(false);
        a31.n("LENS_USE_ARCORE_CAMERA_ANALYZER");
        d2 = new EnumC0091Aba("LENS_USE_ARCORE_CAMERA_ANALYZER", 108, a31, enumSet);
        AI3 h12 = AI3.h(0L);
        h12.n("LENS_ARCORE_KEEP_ALIVE_SECONDS");
        e2 = new EnumC0091Aba("LENS_ARCORE_SESSION_KEEP_ALIVE_SECONDS", Tweaks.MAX_HOURS_AFTER_STREAK_EXPIRE_TO_ENABLE_RESTORE, h12, enumSet);
        f2 = new EnumC0091Aba("LENSES_BUTTON_ON_REPLY_SCREEN_ENABLED", Tweaks.ENABLE_STREAK_EDUCATION, AI3.a(true), enumSet);
        g2 = new EnumC0091Aba("LENS_USE_CT_ITEMS_FROM_MIXER", 111, AI3.a(false), enumSet);
        h2 = new EnumC0091Aba("LENS_UCO_HAS_CACHED_CT_ITEMS", 112, AI3.a(false), enumSet2);
        i2 = new EnumC0091Aba("LENSES_USE_TEST_NAMESPACE_FOR_LIVE_CAMERA", Tweaks.DELTA_SYNC_SQLITE_SHARED_STORAGE_CACHE_SIZE, AI3.a(false), enumSet);
        AI3 l10 = AI3.l("AR_test");
        l10.n("LENSES_TEST_NAMESPACE_NAME_FOR_LIVE_CAMERA");
        j2 = new EnumC0091Aba("LENSES_TEST_NAMESPACE_NAME_FOR_LIVE_CAMERA", Tweaks.FAIL_DECRYPT_FOR_DUPLEX_SNAPS_TEST_ONLY, l10, enumSet);
        k2 = new EnumC0091Aba("LENSES_USE_TEST_NAMESPACE_FOR_UCO", 115, AI3.a(false), enumSet);
        AI3 l11 = AI3.l("AR_test");
        l11.n("LENSES_TEST_NAMESPACE_NAME_FOR_UCO");
        l2 = new EnumC0091Aba("LENSES_TEST_NAMESPACE_NAME_FOR_UCO", 116, l11, enumSet);
        AI3 d11 = AI3.d(EnumC27212jia.a);
        d11.n("LENS_SCHEDULE_V3_ENDPOINT");
        m2 = new EnumC0091Aba("LENS_SCHEDULE_V3_ENDPOINT", 117, d11, enumSet);
        AI3 l12 = AI3.l("");
        l12.n("LENS_FEATURED_LENSES_ROUTING_KEY");
        n2 = new EnumC0091Aba("LENS_SCHEDULE_V3_ROUTING_TAG", 118, l12, enumSet);
        AI3 a32 = AI3.a(true);
        a32.n("LENS_MIXER_USE_OPTIMIZED_MAPPER");
        o2 = new EnumC0091Aba("LENS_MIXER_USE_OPTIMIZED_MAPPER", 119, a32, enumSet);
        AI3 h13 = AI3.h(1000L);
        h13.n("LENS_MIXER_PAGINATION_COOL_DOWN_MS");
        p2 = new EnumC0091Aba("LENS_MIXER_PAGINATION_COOL_DOWN_MS", 120, h13, enumSet);
        AI3 g11 = AI3.g(-1);
        g11.n("LENS_MIXER_CACHED_LENSES_CHECKSUMS_LENGTH");
        q2 = new EnumC0091Aba("LENS_MIXER_CACHED_LENSES_CHECKSUMS_LENGTH", 121, g11, enumSet);
        AI3 a33 = AI3.a(false);
        a33.n("LENS_MIXER_USE_NEW_BANDWIDTH_API_ANDROID");
        r2 = new EnumC0091Aba("LENS_MIXER_USE_NEW_BANDWIDTH_API", 122, a33, enumSet);
        AI3 h14 = AI3.h(2000L);
        h14.n("LENSES_MIXER_REQUEST_FOREGROUND_DEBOUNCE_TIME_MS");
        s2 = new EnumC0091Aba("LENSES_MIXER_REQUEST_FOREGROUND_DEBOUNCE_TIME_MS", 123, h14, enumSet);
        AI3 a34 = AI3.a(false);
        a34.n("LENS_CONVERT_DEVICE_DEPENDENT_ASSETS");
        t2 = new EnumC0091Aba("LENS_CONVERT_DEVICE_DEPENDENT_ASSETS", 124, a34, enumSet);
        AI3 a35 = AI3.a(false);
        a35.n("LENS_USE_FALLBACK_URL");
        u2 = new EnumC0091Aba("LENS_USE_FALLBACK_URL", 125, a35, enumSet);
        AI3 d12 = AI3.d(H87.a);
        d12.n("LENS_USE_FALLBACK_URL_OPTIMIZATION_CONFIG");
        v2 = new EnumC0091Aba("LENS_USE_FALLBACK_URL_OPTIMIZATION_CONFIG", 126, d12, enumSet);
        AI3 h15 = AI3.h(60000L);
        h15.n("LENS_USE_FALLBACK_URL_LOADED_LENSES_TTL_MS");
        w2 = new EnumC0091Aba("LENS_USE_FALLBACK_URL_LOADED_LENSES_TTL_MS", 127, h15, enumSet);
        AI3 i = AI3.i(byte[].class, new byte[0]);
        i.n("LENS_MIXER_RELOAD_CONFIGS");
        x2 = new EnumC0091Aba("LENS_MIXER_RELOAD_CONFIGS", 128, i, enumSet);
        AI3 g12 = AI3.g(0);
        g12.n("LENSES_SCHEDULE_CACHE_VERSION");
        y2 = new EnumC0091Aba("LENSES_SCHEDULE_CACHE_VERSION", 129, g12, enumSet);
        z2 = new EnumC0091Aba("LENSES_SCHEDULE_LAST_CACHE_VERSION", 130, AI3.g(0), enumSet2);
        AI3 l13 = AI3.l("");
        l13.n("LENSES_SCHEDULE_CACHE_VALID_START_DATE");
        A2 = new EnumC0091Aba("LENSES_SCHEDULE_CACHE_VALID_START_DATE", 131, l13, enumSet);
        B2 = new EnumC0091Aba("LENSES_LAST_KNOWN_COUNTRY_CODE", 132, AI3.l("ZZ"), enumSet);
        C2 = new EnumC0091Aba("LENSES_SAID", 133, AI3.l(""), enumSet);
        AI3 a36 = AI3.a(false);
        a36.n("HEXAGON_NN_SKEL_DYNAMIC_DELIVERY_ENABLED");
        D2 = new EnumC0091Aba("HEXAGON_NN_SKEL_ENABLED", 134, a36, enumSet);
        AI3 a37 = AI3.a(false);
        a37.n("TNN_DYNAMIC_DELIVERY_ENABLED");
        E2 = new EnumC0091Aba("TNN_ENABLED", 135, a37, enumSet);
        AI3 a38 = AI3.a(false);
        a38.n("EDGE_TPU_DYNAMIC_DELIVERY_ENABLED");
        F2 = new EnumC0091Aba("EDGE_TPU_ENABLED", 136, a38, enumSet);
        AI3 a39 = AI3.a(false);
        a39.n("TFLITE_MLD_DYNAMIC_DELIVERY_ENABLED");
        G2 = new EnumC0091Aba("TFLITE_MLD_ENABLED", 137, a39, enumSet);
        AI3 a40 = AI3.a(false);
        a40.n("TFLITE_DYNAMIC_DELIVERY_ENABLED");
        H2 = new EnumC0091Aba("ODIN_TFLITE_ENABLED", 138, a40, enumSet);
        AI3 a41 = AI3.a(false);
        a41.n("FASTDNN_TFLITE_DYNAMIC_DELIVERY_ENABLED");
        I2 = new EnumC0091Aba("FASTDNN_TFLITE_ENABLED", 139, a41, enumSet);
        AI3 a42 = AI3.a(true);
        a42.n("LENSES_ANDROID_LOADED_LENSES_FIRST");
        J2 = new EnumC0091Aba("LOADED_LENSES_FIRST_ENABLED", Tweaks.SPONSORED_SNAPS_FEED_INSERT_MODE, a42, enumSet);
        AI3 g13 = AI3.g(-1);
        g13.n("LENS_EXPERIENCE_LOADED_LENSES_FIRST_APPLY_COUNT_ANDROID");
        K2 = new EnumC0091Aba("LOADED_LENSES_FIRST_APPLY_COUNT", Tweaks.SPONSORED_SNAPS_USER_INPUT_MODE, g13, enumSet);
        AI3 i6 = AI3.i(byte[].class, new byte[0]);
        i6.n("LOADED_LENSES_FIRST_V2_NEW");
        L2 = new EnumC0091Aba("LOADED_LENSES_FIRST_V2_ENABLED", Tweaks.CALLBACK_FETCH_ON_FEED_DELEGATE, i6, enumSet);
        AI3 a43 = AI3.a(false);
        a43.p("CT_ANDROID_LENS_UNLOCK_REPLY_CAMERA", "enabled");
        M2 = new EnumC0091Aba("CONTEXT_CARD_LENS_UNLOCK_REPLY_CAMERA_ENABLED", Tweaks.CALLBACK_QUERY_ON_FEED_DELEGATE, a43, enumSet);
        AI3 a44 = AI3.a(false);
        a44.s(390);
        N2 = new EnumC0091Aba("LENS_COLLECTIONS_CTA_HINT_SHOWN", Tweaks.CALLBACK_SYNC_ON_FEED_DELEGATE, a44, enumSet2);
        O2 = new EnumC0091Aba("LENS_COLLECTIONS_ENABLE_CTA_TIMEOUT", Tweaks.FEED_PAGINATION_V4_ENABLED, AI3.a(true), enumSet);
        P2 = new EnumC0091Aba("LENS_COLLECTIONS_PRE_ACTIVATION_HINT_COUNTER", Tweaks.AUTO_PAGINATE_QUERY_FEED_ENABLED, AI3.g(0), enumSet2);
        Q2 = new EnumC0091Aba("LENS_COLLECTIONS_PRE_ACTIVATION_ALLOWED", Tweaks.AUTO_PAGINATE_QUERY_FEED_LITE_ENABLED, AI3.a(false), enumSet2);
        AI3 b10 = AI3.b(new byte[0]);
        b10.n("ANDROID_UCO_SCHEDULE_V3");
        R2 = new EnumC0091Aba("LENS_UCO_SCHEDULE_V3_CONFIG", Tweaks.EXTENSION_DB_WAL_KILLSWITCH, b10, enumSet);
        S2 = new EnumC0091Aba("LENS_COLLECTIONS_CUSTOM_SERVICE_ROUTE_TAG", Tweaks.EXTENSION_FAIL_SYNC_WRITE_KILLSWITCH, AI3.l(""), enumSet);
        T2 = new EnumC0091Aba("LENS_COLLECTIONS_CUSTOM_BASE_URL", Tweaks.LOGIN_PREFETCH_MIN_ENTRIES, AI3.l(""), enumSet);
        AI3 a45 = AI3.a(true);
        a45.n("LENSES_ALLOW_EXTERNAL_FACE_DETECTOR_FOR_CORE");
        U2 = new EnumC0091Aba("ALLOW_EXTERNAL_FACE_DETECTOR_FOR_CORE", Tweaks.LOGIN_PREFETCH_MAX_ENTRIES, a45, enumSet);
        AI3 a46 = AI3.a(false);
        a46.n("LENS_CAROUSEL_GREEN_SCREEN_ANDROID");
        V2 = new EnumC0091Aba("MEDIA_PICKER_PICK_FROM_GALLERY_ENABLED", Tweaks.LOGIN_PREFETCH_PAGE_SIZE, a46, enumSet);
        W2 = new EnumC0091Aba("MEDIA_PICKER_FORCE_SHOW_ALL_MEDIAS", 153, AI3.a(false), enumSet);
        X2 = new EnumC0091Aba("MEDIA_PICKER_FILTER_AFTER_APP_START", Tweaks.ENABLE_LOGIN_PREFETCH, AI3.a(false), enumSet);
        Y2 = new EnumC0091Aba("MEDIA_PICKER_ALWAYS_ON_ENABLED", Tweaks.ENABLE_POST_SYNC_QUERY, AI3.a(false), enumSet);
        AI3 l14 = AI3.l("https://us-central1-gcp.api.snapchat.com/adtracker/v2/track/");
        l14.n("third_party_ad_track_v2_lens_url");
        Z2 = new EnumC0091Aba("LENS_AD_TRACK_URL", Tweaks.ENABLE_MEDIA_PREFETCH_IGNORE_DOWNLOAD_STATUS, l14, enumSet);
        AI3 a47 = AI3.a(false);
        a47.n("ARADS_3P_AD_TRACK_ON_PREVIEW_EXIT_ENABLED");
        a3 = new EnumC0091Aba("ARADS_3P_AD_TRACK_ON_PREVIEW_EXIT_ENABLED", Tweaks.ENABLE_FEED_SYNC_V4_CORRECTION, a47, enumSet);
        AI3 a48 = AI3.a(false);
        a48.n("LENS_CAROUSEL_VIDEO_EDITOR_ENABLED_ANDROID");
        b3 = new EnumC0091Aba("LENS_VIDEO_EDITOR_ENABLED", Tweaks.EEL_GROUP_CONFIG_COF_OVERRIDE64, a48, enumSet);
        AI3 a49 = AI3.a(false);
        a49.n("LENSES_EGL_CONTEXT_CHECK_ENABLED_ANDROID");
        c3 = new EnumC0091Aba("LENSES_EGL_CONTEXT_CHECK_ENABLED", Tweaks.ENABLE_RETRY_POST_SYNC_PREFETCH, a49, enumSet);
        d3 = new EnumC0091Aba("SHOPPING_LENS_PRODUCT_PICKER_DISABLED", Tweaks.ENABLE_PUBLIC_GROUPS, AI3.a(false), enumSet);
        e3 = new EnumC0091Aba("SHOPPING_LENS_PREFETCH_ENABLED", Tweaks.ENABLE_AD_SYNC_ON_P2R, AI3.a(false), enumSet);
        f3 = new EnumC0091Aba("SHOPPING_LENS_PREFETCH_COUNT", Tweaks.ENABLE_STREAK_SETTINGS, AI3.g(5), enumSet);
        g3 = new EnumC0091Aba("SHOPPING_LENS_ASSET_PREFETCH_COUNT", 163, AI3.g(5), enumSet);
        AI3 l15 = AI3.l("59215890905");
        l15.n("forma_photoshoot_lens_id");
        h3 = new EnumC0091Aba("PHOTOSHOOT_LENS_ID", 164, l15, enumSet);
        i3 = new EnumC0091Aba("SCAN_FROM_LENS_ONBOARDED", 165, AI3.a(false), enumSet2);
        AI3 a50 = AI3.a(true);
        a50.n("LE_CACHE_BATCH_RESPONSE_ENABLED");
        j3 = new EnumC0091Aba("LENS_EXPLORER_CACHE_BATCH_RESPONSE", 166, a50, enumSet);
        AI3 a51 = AI3.a(false);
        a51.n("ads_mushroom_enable_lens_lfv_bolt_url");
        k3 = new EnumC0091Aba("ENABLE_LONGFORM_VIDEO_ATTACHMENT_VIDEO_URL", 167, a51, enumSet);
        l3 = new EnumC0091Aba("REMOTE_API_SERVICE_ROUTE_TAG", 168, AI3.l(""), enumSet);
        AI3 a52 = AI3.a(false);
        a52.n("REMOTE_API_STACKED_LENSES_SUPPORT_ANDROID");
        m3 = new EnumC0091Aba("REMOTE_API_URI_HANDLER_ENABLE_STACKED_LENSES_SUPPORT", 169, a52, enumSet);
        AI3 a53 = AI3.a(false);
        a53.n("LENSES_REMOTE_MEDIA_ALLOW_EXTERNAL_URL");
        n3 = new EnumC0091Aba("REMOTE_MEDIA_ASSET_DOWNLOAD_ALLOW_EXTERNAL_URL", 170, a53, enumSet);
        AI3 l16 = AI3.l("");
        l16.n("LENS_SNAP_SERVICE_REMOTE_HOST_ALLOWLIST");
        o3 = new EnumC0091Aba("REMOTE_MEDIA_ASSET_DOWNLOAD_HOSTNAME_ALLOWLIST", 171, l16, enumSet);
        AI3 i7 = AI3.i(byte[].class, new byte[0]);
        i7.n("LENSES_PROGRESSIVE_DOWNLOAD_CONFIGURATION");
        p3 = new EnumC0091Aba("LENSES_PROGRESSIVE_DOWNLOAD_CONFIGURATION", 172, i7, enumSet);
        AI3 i8 = AI3.i(byte[].class, new byte[0]);
        i8.n("DEVICE_DEPENDENT_ASSET_RESOLVER_MODE_CONFIG");
        q3 = new EnumC0091Aba("DEVICE_DEPENDENT_ASSET_RESOLVER_MODE_CONFIG", 173, i8, enumSet);
        AI3 a54 = AI3.a(false);
        a54.n("LENSES_ANDROID_USE_CM_FILE_DESCRIPTOR");
        r3 = new EnumC0091Aba("LENSES_USE_CM_FILE_DESCRIPTOR", 174, a54, enumSet);
        AI3 a55 = AI3.a(false);
        a55.n("LENSES_UCO_FIX_SWIPE_REPORTING");
        s3 = new EnumC0091Aba("LENSES_UCO_FIX_SWIPE_REPORTING", 175, a55, enumSet);
        AI3 a56 = AI3.a(false);
        a56.n("LENSES_UCO_FIX_ACTION_REPORTING");
        t3 = new EnumC0091Aba("LENSES_UCO_FIX_ACTION_REPORTING", 176, a56, enumSet);
        AI3 f = AI3.f(0.0f);
        f.n("LENSES_UCO_FIX_SPLIT_RENDER_REPORTING_FRACTION");
        u3 = new EnumC0091Aba("LENSES_UCO_FIX_SPLIT_RENDER_REPORTING_FRACTION", 177, f, enumSet);
        AI3 a57 = AI3.a(false);
        a57.n("LENSES_SKIP_FULL_SCREEN_ZONES_UPDATE");
        v3 = new EnumC0091Aba("LENSES_SKIP_FULL_SCREEN_ZONES_UPDATE", 178, a57);
        AI3 a58 = AI3.a(true);
        a58.n("LENSES_UCO_TOUCH_SUPPORT_ENABLED");
        w3 = new EnumC0091Aba("LENSES_UCO_TOUCH_SUPPORT_ENABLED", 179, a58, enumSet);
        AI3 a59 = AI3.a(true);
        a59.n("LENSES_UCO_KEYBOARD_SUPPORT_ENABLED");
        x3 = new EnumC0091Aba("LENSES_UCO_KEYBOARD_SUPPORT_ENABLED", 180, a59, enumSet);
        AI3 a60 = AI3.a(false);
        a60.n("LENSES_UCO_SCREEN_ZONES_SUPPORT_ENABLED");
        y3 = new EnumC0091Aba("LENSES_UCO_SCREEN_ZONES_SUPPORT_ENABLED", 181, a60, enumSet);
        AI3 g14 = AI3.g(0);
        g14.n("LENSES_UCO_NUMBER_OF_WARMUP_FRAMES");
        z3 = new EnumC0091Aba("LENSES_UCO_TRANSCODING_WARM_UP_FRAME_COUNT", 182, g14, enumSet);
        AI3 d13 = AI3.d(UUe.a);
        d13.n("LENSES_UCO_REPLACE_COLOR_FILTERS");
        A3 = new EnumC0091Aba("LENSES_UCO_REPLACE_COLOR_FILTERS", 183, d13, enumSet);
        AI3 a61 = AI3.a(false);
        a61.n("LENSES_UCO_SHOW_INFO_CARD_FOR_BUNDLED");
        B3 = new EnumC0091Aba("LENSES_UCO_SHOW_INFO_CARD_FOR_BUNDLED", 184, a61, enumSet);
        AI3 a62 = AI3.a(false);
        a62.n("LENSES_TRANSCODING_ALWAYS_APPLY_COLOR_FILTERS");
        C3 = new EnumC0091Aba("LENSES_TRANSCODING_ALWAYS_APPLY_COLOR_FILTERS", 185, a62, enumSet);
        AI3 a63 = AI3.a(false);
        a63.n("PREVIEW_CT_LENS_USE_DESCRIPTOR_FOR_POST_CAPTURE_TOUCH_SUPPORT");
        D3 = new EnumC0091Aba("ENABLE_UCO_TOUCH_BY_LENS_DESCRIPTOR", 186, a63);
        AI3 a64 = AI3.a(true);
        a64.n("CAMERA_ANDROID_LENS_BRIGHTNESS_HANDLER_ENABLED");
        E3 = new EnumC0091Aba("LENSES_CAMERA_LIGHT_CONDITION", 187, a64, enumSet);
        AI3 a65 = AI3.a(false);
        a65.n("LE_SNAPCHAT_WEB_LINK_ENABLED_ANDROID");
        F3 = new EnumC0091Aba("LENS_EXPLORER_SNAPCHAT_WEB_LINK_ENABLED", 188, a65, enumSet);
        AI3 a66 = AI3.a(false);
        a66.n("LENS_COLLECTION_DEEPLINK_ENABLED_ANDROID");
        G3 = new EnumC0091Aba("LENS_COLLECTION_DEEPLINK_ENABLED", 189, a66, enumSet);
        AI3 a67 = AI3.a(false);
        a67.s(517);
        H3 = new EnumC0091Aba("VOICE_ML_LENSES_ACCEPTED_FTUE_PROMPT", 190, a67, enumSet2);
        AI3 g15 = AI3.g(0);
        g15.s(568);
        I3 = new EnumC0091Aba("VOICE_ML_LENS_VOICE_CONTROL_ONBOARDING_BANNER_SEEN_COUNT", 191, g15, enumSet2);
        AI3 d14 = AI3.d(ROj.a);
        d14.n("ANDROID_LENS_VOICEML_LENS_UX_TYPE");
        J3 = new EnumC0091Aba("VOICE_ML_LENS_UX_VERSION", 192, d14, enumSet2);
        K3 = new EnumC0091Aba("VOICE_ML_LENS_SHOULD_RESET_FTEU", 193, AI3.a(false), enumSet);
        AI3 a68 = AI3.a(false);
        a68.n("ANDROID_VOICEML_LENS_HINTS_PRIORITIZATION");
        L3 = new EnumC0091Aba("VOICEML_LENS_HINTS_PRIORITIZATION", 194, a68, enumSet);
        M3 = new EnumC0091Aba("VOICE_ML_ENDPOINT", 195, AI3.d(KNj.PRODUCTION), enumSet);
        N3 = new EnumC0091Aba("LENS_CAROUSEL_ABOVE_ACTIONS_ENABLED", 196, AI3.a(false), enumSet);
        AI3 i9 = AI3.i(byte[].class, new byte[0]);
        i9.n("LENS_FASTER_CAROUSEL");
        O3 = new EnumC0091Aba("LENS_FASTER_CAROUSEL_CONFIG", 197, i9, enumSet);
        P3 = new EnumC0091Aba("LENS_FASTER_CAROUSEL_ENABLED", 198, AI3.a(false), enumSet);
        Q3 = new EnumC0091Aba("LENS_DRAG_APPLICATION_DELAY", 199, AI3.h(-1L), enumSet);
        R3 = new EnumC0091Aba("LENS_DRAG_SKIP_DELAY_FOR_SPONSORED_LENSES", AccountManagerConstants.AP_CONFIRM_CREDENTIAL_REQUEST_CODE, AI3.a(false), enumSet);
        S3 = new EnumC0091Aba("LENS_DRAG_SKIP_NON_SPONSORED_LENSES", 201, AI3.a(false), enumSet);
        T3 = new EnumC0091Aba("LENS_FAST_APPLY_FIRST_LENS_CONFIG", 202, AI3.b(new byte[0]), enumSet);
        AI3 d15 = AI3.d(EnumC7499Nq2.a);
        d15.n("LENSES_CAROUSEL_SCROLL_ZONE_MODE_ANDROID");
        U3 = new EnumC0091Aba("LENS_CAROUSEL_SCROLL_ZONE_MODE", 203, d15, enumSet);
        V3 = new EnumC0091Aba("LENS_CTA_OBSERVES_CAROUSEL_SELECTIONS", 204, AI3.a(false), enumSet);
        W3 = new EnumC0091Aba("LENS_ATTACHMENT_CTA_INTERCEPT_SWIPE_UP", 205, AI3.a(false), enumSet);
        X3 = new EnumC0091Aba("SPONSORED_LENS_SCREEN_TAP_TRACKER_ENABLED", 206, AI3.a(false), enumSet);
        Y3 = new EnumC0091Aba("SPONSORED_LENS_VIEWPORT_TAP_TRACKER_ENABLED", 207, AI3.a(false), enumSet);
        AI3 h16 = AI3.h(-1L);
        h16.n("LENS_DRAG_APPLY_PIPELINE_DELAY");
        Z3 = new EnumC0091Aba("LENS_DRAG_APPLY_PIPELINE_DELAY", 208, h16, enumSet);
        a4 = new EnumC0091Aba("LENS_FLING_APPLICATION_ENABLED", 209, AI3.a(false), enumSet);
        b4 = new EnumC0091Aba("LENS_FLING_VELOCITY_FACTOR", 210, AI3.c(1.0d), enumSet);
        c4 = new EnumC0091Aba("LENS_CENTER_CAROUSEL_ITEM_ON_FLING", 211, AI3.a(false), enumSet);
        d4 = new EnumC0091Aba("LENS_PREVIEW_IMPRESSION_DELAY_MILLIS", 212, AI3.h(-1L), enumSet);
        e4 = new EnumC0091Aba("LENS_PREVIEW_REPORT_SWIPES", 213, AI3.a(false), enumSet);
        AI3 a69 = AI3.a(false);
        a69.n("LENS_CAROUSEL_AD_CAMERA_TYPE_BASED_POSITION_ENABLED");
        f4 = new EnumC0091Aba("LENS_CAROUSEL_AD_CAMERA_TYPE_BASED_POSITION_ENABLED", 214, a69, enumSet);
        AI3 i10 = AI3.i(byte[].class, new byte[0]);
        i10.n("LENS_MIXER_LOCATION_CONFIGURATION");
        g4 = new EnumC0091Aba("LENS_MIXER_LOCATION_CONFIGURATION", 215, i10, enumSet);
        h4 = new EnumC0091Aba("LENS_MIXER_ERROR_COUNTER", 216, AI3.g(0), enumSet2);
        AI3 a70 = AI3.a(false);
        a70.n("LENS_SEQUENTIAL_VIDEO_STREAM_USE_SOFTWARE_DECODER");
        i4 = new EnumC0091Aba("LENS_SEQUENTIAL_VIDEO_STREAM_SOFTWARE_DECODING_ENABLED", 217, a70, enumSet);
        j4 = new EnumC0091Aba("PREVIEW_MAGIC_ERASER_LENS_ID", 218, AI3.l(""), enumSet);
        k4 = new EnumC0091Aba("PREVIEW_AI_MODE_LENS_ID", 219, AI3.l(""), enumSet);
        l4 = new EnumC0091Aba("PREVIEW_AI_MODE_ENABLED_FOR_EVERYONE", 220, AI3.a(false), enumSet);
        m4 = new EnumC0091Aba("PREVIEW_FILTER_CAROUSEL_LENS_ID_FOR_TESTING", 221, AI3.l(""), enumSet);
        AI3 a71 = AI3.a(false);
        a71.n("LENS_ICON_IMPRESSION_ENABLED");
        n4 = new EnumC0091Aba("LENS_CAROUSEL_LENS_ICON_IMPRESSION_ENABLED", 222, a71, enumSet);
        AI3 a72 = AI3.a(false);
        a72.n("LENSES_DISABLE_GCS_COF_BASED_ASSETS");
        o4 = new EnumC0091Aba("LENSES_DISABLE_GCS_COF_BASED_ASSETS", 223, a72, enumSet);
        AI3 a73 = AI3.a(false);
        a73.n("LENSES_ENABLE_HDR_TO_SDR_TONE_MAPPING");
        p4 = new EnumC0091Aba("LENSES_ENABLE_HDR_TO_SDR_TONE_MAPPING", 224, a73, enumSet);
        AI3 l17 = AI3.l("63566930876");
        l17.n("BITMOJI_OFFSCREEN_RENDERING_LENS");
        q4 = new EnumC0091Aba("BITMOJI_OFFSCREEN_RENDERING_LENS", 225, l17, enumSet);
        AI3 l18 = AI3.l("688225636838127");
        l18.n("BITMOJI_AVATAR_VIEWER_LENS");
        r4 = new EnumC0091Aba("BITMOJI_AVATAR_VIEWER_LENS", 226, l18, enumSet);
        AI3 g16 = AI3.g(-1);
        g16.n("BITMOJI_AVATAR_VIEWER_LENS_FPS");
        s4 = new EnumC0091Aba("BITMOJI_AVATAR_VIEWER_LENS_FPS", 227, g16, enumSet);
        t4 = new EnumC0091Aba("BITMOJI_USE_STAGING_HOST", 228, AI3.a(false), enumSet);
        AI3 i11 = AI3.i(byte[].class, new byte[0]);
        i11.n("ANDROID_LENSES_DEACTIVATION_V2");
        u4 = new EnumC0091Aba("LENSES_DEACTIVATION_CONFIG", 229, i11, enumSet);
        v4 = new EnumC0091Aba("PRIORITY_LENS_SCROLL_TAP_BIAS", 230, AI3.f(0.0f), enumSet);
        w4 = new EnumC0091Aba("LENS_NOTIFICATION_BIG_PICTURE_TIMEOUT_MILLIS", 231, AI3.h(3500L), enumSet);
        AI3 b11 = AI3.b(new byte[0]);
        b11.n("LENS_CAROUSEL_FUNNEL_CONFIG");
        x4 = new EnumC0091Aba("LENS_CAROUSEL_FUNNEL_REPORTING_CONFIG", 232, b11, enumSet);
        AI3 a74 = AI3.a(false);
        a74.n("LENSES_ANDROID_SWIPE_FUNNEL");
        y4 = new EnumC0091Aba("LENS_FUNNEL_SWIPE_ENABLED", 233, a74, enumSet);
        z4 = new EnumC0091Aba("LENS_WARM_UP_PROCESSING_FORCE_ENABLED", 234, AI3.a(false), enumSet);
        AI3 b12 = AI3.b(new byte[0]);
        b12.n("LENS_PROCESSING_WARMUP_CONFIG");
        A4 = new EnumC0091Aba("LENS_WARM_UP_PROCESSING_CONFIG", 235, b12, enumSet);
        AI3 h17 = AI3.h(-1L);
        h17.n("LENSES_ANDROID_AUTO_SELECT_LENS_NUX_DELAY");
        B4 = new EnumC0091Aba("LENSES_AUTO_SELECT_LENS_NUX_DELAY", 236, h17, enumSet);
        AI3 a75 = AI3.a(false);
        a75.s(862);
        C4 = new EnumC0091Aba("LENSES_AUTO_SELECT_LENS_NUX_SHOWN", 237, a75, enumSet2);
        AI3 d16 = AI3.d(N3a.a);
        d16.n("LENS_TOP_ACTIONS_SPONSORED_LENSES_MODE_ANDROID");
        D4 = new EnumC0091Aba("LENSES_TOP_ACTIONS_SPONSORED_LENS_MODE", 238, d16, enumSet);
        AI3 a76 = AI3.a(false);
        a76.n("LENS_EXPERIENCE_TOP_ACTION_BAR_LENS_VIEWS_DISABLED_ANDROID");
        E4 = new EnumC0091Aba("LENS_EXPERIENCE_TOP_ACTION_BAR_LENS_VIEWS_DISABLED", 239, a76, enumSet);
        AI3 a77 = AI3.a(false);
        a77.n("LENS_LENSVIEW_OPEN_TOPICS_ANDROID");
        F4 = new EnumC0091Aba("LENS_LENSVIEW_OPEN_TOPICS", 240, a77, enumSet);
        G4 = new EnumC0091Aba("NEW_LENS_INFO_BUTTON_HIDE_ATTRIBUTION_DELAY", 241, AI3.h(2000L), enumSet);
        AI3 i12 = AI3.i(byte[].class, new byte[0]);
        i12.n("LENS_EXPERIENCE_CAROUSEL_PAGINATION_ANDROID");
        H4 = new EnumC0091Aba("MAIN_CAROUSEL_PAGINATION_CONFIG", 242, i12, enumSet2);
        AI3 h18 = AI3.h(500L);
        h18.n("LENS_EXPERIENCE_CAROUSEL_REQUEST_INTERVAL");
        I4 = new EnumC0091Aba("MAIN_CAROUSEL_PAGINATION_REQUEST_INTERVAL", 243, h18, enumSet);
        AI3 i13 = AI3.i(byte[].class, new byte[0]);
        i13.n("LENS_EXPERIENCE_AR_BAR_CAROUSEL_PAGINATION_ANDROID");
        J4 = new EnumC0091Aba("AR_BAR_CAROUSEL_PAGINATION_CONFIG", 244, i13, enumSet2);
        AI3 d17 = AI3.d(E40.a);
        d17.n("LENSES_AR_BAR_VISIBLE_PREFETCH_MODE_ANDROID");
        K4 = new EnumC0091Aba("LENSES_AR_BAR_VISIBLE_PREFETCH_MODE", 245, d17, enumSet);
        AI3 a78 = AI3.a(false);
        a78.n("LENSES_AR_BAR_ALWAYS_ON_REPLY_ENABLED_ANDROID");
        L4 = new EnumC0091Aba("LENSES_AR_BAR_ALWAYS_ON_REPLY_ENABLED", 246, a78, enumSet);
        AI3 l19 = AI3.l("");
        l19.n("LENSES_AR_BAR_FRESHNESS_FEED_IDS_ANDROID");
        M4 = new EnumC0091Aba("LENSES_AR_BAR_FRESHNESS_FEED_IDS", 247, l19, enumSet);
        AI3 l20 = AI3.l("");
        l20.n("LENSES_AR_BAR_LE_ENTRY_POINT_FEED_IDS_ANDROID");
        N4 = new EnumC0091Aba("LENSES_AR_BAR_LE_ENTRY_POINT_FEED_IDS", 248, l20, enumSet);
        AI3 i14 = AI3.i(byte[].class, new byte[0]);
        i14.n("LENS_EXPLORER_PREVIEW_TILES");
        O4 = new EnumC0091Aba("LENSES_EXPLORER_PREVIEW_TILES", 249, i14, enumSet);
        AI3 i15 = AI3.i(byte[].class, new byte[0]);
        i15.n("LC_INTERACTION_HISTORY");
        P4 = new EnumC0091Aba("LENSES_INTERACTION_HISTORY_CONFIG", 250, i15, enumSet);
        AI3 a79 = AI3.a(false);
        a79.n("RTUS_PRODUCT_ENABLED_LENS_RANKING");
        Q4 = new EnumC0091Aba("LENSES_RTUS_FOR_LENS_RANKING_ENABLED", 251, a79, enumSet);
        AI3 a80 = AI3.a(false);
        a80.n("CAMERA_SKIP_LENS_DRIVEN_AE");
        R4 = new EnumC0091Aba("CAMERA_SKIP_LENS_DRIVEN_AE", 252, a80, enumSet);
        AI3 a81 = AI3.a(false);
        a81.n("LENSES_UCO_GEN_AI_CTA_ENABLED");
        S4 = new EnumC0091Aba("LENSES_PREVIEW_GEN_AI_BUTTON", 253, a81, enumSet);
        AI3 h19 = AI3.h(0L);
        h19.n("FETCH_IS_GEN_AI_TIMEOUT");
        T4 = new EnumC0091Aba("FETCH_IS_GEN_AI_TIMEOUT", 254, h19, enumSet);
        AI3 a82 = AI3.a(false);
        a82.n("LENSES_CAMERA_MODES_MANAGER_INCREASE_DOWNLOAD_PRIORITY");
        U4 = new EnumC0091Aba("COMBINE_CAMERA_MODES_PRIORITY", 255, a82, enumSet);
        V4 = new EnumC0091Aba("LENSES_LENS_CORE_REFACTORED_LIFECYCLE_MODE_V2", 256, AI3.d(FQ9.a), enumSet);
        W4 = new EnumC0091Aba("LENSES_FORCE_LENS_WARMUP_ID", 257, AI3.l(""), enumSet);
        AI3 l21 = AI3.l("");
        l21.n("LENSES_LENS_WARMUP_IDS_BLOCKLIST");
        X4 = new EnumC0091Aba("LENSES_LENS_WARMUP_IDS_BLOCKLIST", 258, l21, enumSet);
        AI3 i16 = AI3.i(byte[].class, new byte[0]);
        i16.n("LENS_CORE_REFACTORED_LIFECYCLE");
        Y4 = new EnumC0091Aba("LENSES_LENS_CORE_REFACTORED_LIFECYCLE", 259, i16, enumSet);
        AI3 a83 = AI3.a(false);
        a83.n("LENS_CORE_INIT_DISPOSE_ON_EXCEPTION");
        Z4 = new EnumC0091Aba("LENS_CORE_INIT_DISPOSE_ON_EXCEPTION", 260, a83, enumSet);
        a5 = new EnumC0091Aba("ENABLE_BIRTHDAY_LENS", 261, AI3.a(true), enumSet);
        b5 = new EnumC0091Aba("LENSES_LAST_SEEN_BIRTHDAYS_UPDATE_TIME_MILLIS", 262, AI3.h(-1L), enumSet2);
        c5 = new EnumC0091Aba("LENSES_LAST_SEEN_BIRTHDAYS", 263, AI3.l(""), enumSet2);
        AI3 l22 = AI3.l("");
        l22.n("LENS_EXPERIENCE_BIRTHDAY_LENS_ID_ANDROID");
        d5 = new EnumC0091Aba("LENSES_BIRTHDAY_LENS_ID", 264, l22, enumSet);
        e5 = new EnumC0091Aba("LENS_CAMERA_SWITCHER_CONFIG", 265, AI3.i(byte[].class, new byte[0]), enumSet);
        AI3 a84 = AI3.a(false);
        a84.n("LENSES_CAROUSEL_AS_ACTION_DRAIN");
        f5 = new EnumC0091Aba("LENSES_CAROUSEL_AS_ACTION_DRAIN", 266, a84, enumSet);
        g5 = new EnumC0091Aba("COLLAGE_LENS_OVERRIDE_LAUNCH_TIME_ENABLED", 267, AI3.a(true), enumSet);
        h5 = new EnumC0091Aba("LENSES_PUBLIC_ILC_LENSES_ENABLED", 268, AI3.a(false), enumSet);
        AI3 a85 = AI3.a(true);
        a85.n("LENSES_WAIT_FOR_DOWNLOAD_STATUS_ON_SELECTION_ANDROID");
        i5 = new EnumC0091Aba("LENSES_WAIT_FOR_DOWNLOAD_STATUS_ON_SELECTION_ANDROID", 269, a85, enumSet);
        AI3 h20 = AI3.h(5000L);
        h20.n("COLLAGE_WARMUP_ASYNC_LENS_QUERY_TIMEOUT_MS");
        j5 = new EnumC0091Aba("COLLAGE_WARMUP_ASYNC_LENS_QUERY_TIMEOUT_MS", 270, h20, enumSet);
        AI3 h21 = AI3.h(30000L);
        h21.n("COLLAGE_LENS_PREPARE_TIMEOUT_MS");
        k5 = new EnumC0091Aba("COLLAGE_LENS_PREPARE_TIMEOUT_MS", 271, h21, enumSet);
        AI3 h22 = AI3.h(100L);
        h22.n("COLLAGE_LENS_PREPARE_LOOP_MS");
        l5 = new EnumC0091Aba("COLLAGE_LENS_PREPARE_LOOP_MS", 272, h22, enumSet);
        AI3 g17 = AI3.g(0);
        g17.n("LENS_EXPERIENCE_INTO_LENS_TINSEL_LIMIT_ANDROID");
        m5 = new EnumC0091Aba("LENSES_INTO_LENS_TINSEL_LIMIT", 273, g17, enumSet);
        AI3 h23 = AI3.h(2000L);
        h23.n("LENSES_DYNAMIC_ASSETS_LATCH_TIMEOUT_MS");
        n5 = new EnumC0091Aba("LENSES_DYNAMIC_ASSETS_LATCH_TIMEOUT_MS", 274, h23, enumSet);
        o5 = new EnumC0091Aba("LENSES_ANDROID_APPLY_MODE", 275, AI3.d(SM9.a), enumSet);
        AI3 a86 = AI3.a(true);
        a86.n("LENSES_UCO_FIX_APPLICABLE_CONTEXT");
        p5 = new EnumC0091Aba("LENSES_UCO_FIX_APPLICABLE_CONTEXT", 276, a86, enumSet);
        AI3 g18 = AI3.g(0);
        g18.n("LENSES_CAROUSEL_THREADING");
        q5 = new EnumC0091Aba("LENSES_CAROUSEL_THREADING", 277, g18, enumSet);
        r5 = new EnumC0091Aba("LENS_EXPERIENCE_LEADERBOARD_SKIP_DATA_USAGE_PERMISSION", 278, AI3.a(false), enumSet);
        AI3 a87 = AI3.a(false);
        a87.n("ANDROID_LENSES_LEADERBOARD_ALLOW_TOUCH_BEHIND_DIALOG");
        s5 = new EnumC0091Aba("LEADERBOARD_ALLOW_TOUCH_BEHIND_DIALOG", 279, a87, enumSet);
        AI3 a88 = AI3.a(false);
        a88.n("ANDROID_ATTEMPT_TO_LOAD_CACHED_P2D_LENSES_FOR_SOCIAL_UNLOCK");
        t5 = new EnumC0091Aba("ATTEMPT_TO_LOAD_CACHED_P2D_LENSES_FOR_SOCIAL_UNLOCK", 280, a88, enumSet);
        AI3 h24 = AI3.h(-1L);
        h24.n("LENSES_SELECT_TO_SNAPPABLE_CRITICAL_WORK");
        u5 = new EnumC0091Aba("LENSES_SELECT_TO_SNAPPABLE_CRITICAL_WORK", 281, h24, enumSet);
        AI3 a89 = AI3.a(false);
        a89.n("LENSES_CHECK_CONTEXT_BEFORE_CORE_MANAGER");
        v5 = new EnumC0091Aba("LENSES_CHECK_CONTEXT_BEFORE_CORE_MANAGER", 282, a89, enumSet);
        w5 = new EnumC0091Aba("LENSES_ENABLE_TOUCHES_VIDEOCALLING", 283, AI3.a(true), enumSet);
        AI3 a90 = AI3.a(false);
        a90.n("LENS_RENDERED_SWIPE_MIGRATION_ENABLED");
        x5 = new EnumC0091Aba("LENSES_RENDERED_SWIPE_ON_TEXTURE_DRAWN", 284, a90, enumSet);
        AI3 a91 = AI3.a(false);
        a91.n("LENSES_SHARED_LENS_CORE_IMAGE_POST_CAPTURE");
        y5 = new EnumC0091Aba("LENSES_SHARED_LENS_CORE_IMAGE_POST_CAPTURE", 285, a91, enumSet);
        AI3 a92 = AI3.a(false);
        a92.n("LENSES_SHARED_LENS_CORE_VIDEO_POST_CAPTURE");
        z5 = new EnumC0091Aba("LENSES_SHARED_LENS_CORE_VIDEO_POST_CAPTURE", 286, a92, enumSet);
        AI3 a93 = AI3.a(false);
        a93.n("LENSES_SHARED_LENS_CORE_LOOPER");
        A5 = new EnumC0091Aba("LENSES_SHARED_LENS_CORE_LOOPER", 287, a93, enumSet);
        AI3 a94 = AI3.a(false);
        a94.n("LENSES_EXCLUSIVE_UPSELL_ANY_ACTION_ENABLED");
        B5 = new EnumC0091Aba("LENSES_EXCLUSIVE_UPSELL_ANY_ACTION_ENABLED", 288, a94, enumSet);
        AI3 d18 = AI3.d(HT6.PLATINUM);
        d18.n("EXCLUSIVE_LENSES_TIER_TYPE");
        C5 = new EnumC0091Aba("EXCLUSIVE_LENSES_TIER_TYPE", 289, d18, enumSet);
        AI3 a95 = AI3.a(true);
        a95.n("LENS_PLUS_UPSELL_PRESENT_MANAGEMENT_PAGE");
        D5 = new EnumC0091Aba("EXCLUSIVE_LENSES_PRESENT_MANAGEMENT_PAGE", 290, a95, enumSet);
        AI3 a96 = AI3.a(false);
        a96.n("LENSES_REPORT_PERFORMANCE_EVENTS");
        E5 = new EnumC0091Aba("LENSES_REPORT_PERFORMANCE_EVENTS", 291, a96, enumSet);
        AI3 a97 = AI3.a(false);
        a97.n("VENUE_LENS_ENABLE_PREFETCH_ON_PREVIEW");
        F5 = new EnumC0091Aba("ENABLE_VENUE_DATA_PREFETCH_ON_PREVIEW", 292, a97, enumSet);
        AI3 a98 = AI3.a(false);
        a98.n("LENSES_DISABLE_EXTERNAL_EXCEPTION_HANDLER");
        G5 = new EnumC0091Aba("LENSES_DISABLE_EXTERNAL_EXCEPTION_HANDLER", 293, a98, enumSet);
        AI3 d19 = AI3.d(EnumC31642n1a.a);
        d19.n("LENSES_SIDEEFFECT_MODE");
        H5 = new EnumC0091Aba("LENSES_SIDEEFFECT_MODE", 294, d19, enumSet);
        AI3 a99 = AI3.a(false);
        a99.n("LENSES_ENABLE_HANDLED_EXCEPTION_REPORTING_FIX");
        I5 = new EnumC0091Aba("LENSES_ENABLE_HANDLED_EXCEPTION_REPORTING_FIX", 295, a99, enumSet);
        J5 = new EnumC0091Aba("LENSES_PUBLIC_PROMPT_LENSES_TURN_BY_TURN_ENABLED", 296, AI3.a(false), enumSet);
        AI3 a100 = AI3.a(false);
        a100.n("LENSES_DISABLE_ASYNC_TRACKING_ON_POST_CAPTURE");
        K5 = new EnumC0091Aba("LENSES_DISABLE_ASYNC_TRACKING_ON_POST_CAPTURE", 297, a100);
        AI3 a101 = AI3.a(false);
        a101.n("FF_SMART_CTA_ALWAYS_SHOW_BIRTHDAY_CTA");
        L5 = new EnumC0091Aba("LENSES_SMART_CTA_ALWAYS_SHOW_BIRTHDAY_CTA", 298, a101);
        AI3 a102 = AI3.a(false);
        a102.n("LENSES_SKIP_TRANSCODING_EXCEPTION_ON_FAILED_ASSET");
        M5 = new EnumC0091Aba("LENSES_SKIP_TRANSCODING_EXCEPTION_ON_FAILED_ASSET", 299, a102);
        AI3 g19 = AI3.g(0);
        g19.n("BITMOJI_CTA_UI_VARIANT");
        N5 = new EnumC0091Aba("LENSES_CREATE_BITMOJI_CTA", 300, g19, enumSet);
        AI3 d20 = AI3.d(EnumC20573eka.a);
        d20.n("LENSES_UPDATE_BITMOJI_CTA");
        O5 = new EnumC0091Aba("LENSES_UPDATE_BITMOJI_CTA", 301, d20, enumSet);
        AI3 l23 = AI3.l("CAT_3");
        l23.n("LENSES_UPDATE_BITMOJI_CTA_DISALLOWED_TAXONOMIES");
        P5 = new EnumC0091Aba("LENSES_UPDATE_BITMOJI_CTA_DISALLOWED_TAXONOMIES", 302, l23, enumSet);
        AI3 a103 = AI3.a(false);
        a103.n("LENSES_DISABLE_HANDLED_EXCEPTION_STACKTRACE_FIX");
        Q5 = new EnumC0091Aba("LENSES_DISABLE_HANDLED_EXCEPTION_STACKTRACE_FIX", 303, a103);
        R5 = a();
    }

    public EnumC0091Aba(String str, int i, AI3 ai3, EnumSet enumSet) {
        this.a = ai3;
        this.b = enumSet;
    }

    public static /* synthetic */ EnumC0091Aba[] a() {
        return new EnumC0091Aba[]{c, t, X, Y, Z, e0, f0, g0, h0, i0, j0, k0, l0, m0, n0, o0, p0, q0, r0, s0, t0, u0, v0, w0, x0, y0, z0, A0, B0, C0, D0, E0, F0, G0, H0, I0, J0, K0, L0, M0, N0, O0, P0, Q0, R0, S0, T0, U0, V0, W0, X0, Y0, Z0, a1, b1, c1, d1, e1, f1, g1, h1, i1, j1, k1, l1, m1, n1, o1, p1, q1, r1, s1, t1, u1, v1, w1, x1, y1, z1, A1, B1, C1, D1, E1, F1, G1, H1, I1, J1, K1, L1, M1, N1, O1, P1, Q1, R1, S1, T1, U1, V1, W1, X1, Y1, Z1, a2, b2, c2, d2, e2, f2, g2, h2, i2, j2, k2, l2, m2, n2, o2, p2, q2, r2, s2, t2, u2, v2, w2, x2, y2, z2, A2, B2, C2, D2, E2, F2, G2, H2, I2, J2, K2, L2, M2, N2, O2, P2, Q2, R2, S2, T2, U2, V2, W2, X2, Y2, Z2, a3, b3, c3, d3, e3, f3, g3, h3, i3, j3, k3, l3, m3, n3, o3, p3, q3, r3, s3, t3, u3, v3, w3, x3, y3, z3, A3, B3, C3, D3, E3, F3, G3, H3, I3, J3, K3, L3, M3, N3, O3, P3, Q3, R3, S3, T3, U3, V3, W3, X3, Y3, Z3, a4, b4, c4, d4, e4, f4, g4, h4, i4, j4, k4, l4, m4, n4, o4, p4, q4, r4, s4, t4, u4, v4, w4, x4, y4, z4, A4, B4, C4, D4, E4, F4, G4, H4, I4, J4, K4, L4, M4, N4, O4, P4, Q4, R4, S4, T4, U4, V4, W4, X4, Y4, Z4, a5, b5, c5, d5, e5, f5, g5, h5, i5, j5, k5, l5, m5, n5, o5, p5, q5, r5, s5, t5, u5, v5, w5, x5, y5, z5, A5, B5, C5, D5, E5, F5, G5, H5, I5, J5, K5, L5, M5, N5, O5, P5, Q5};
    }

    public static EnumC0091Aba valueOf(String str) {
        return (EnumC0091Aba) Enum.valueOf(EnumC0091Aba.class, str);
    }

    public static EnumC0091Aba[] values() {
        return (EnumC0091Aba[]) R5.clone();
    }

    @Override // defpackage.BI3
    public final EnumC48048zI3 e() {
        return EnumC48048zI3.L0;
    }

    @Override // defpackage.BI3
    public final String getName() {
        return name();
    }

    @Override // defpackage.BI3
    public final AI3 j() {
        return this.a;
    }

    @Override // defpackage.S4f
    public final EnumSet o2() {
        return this.b;
    }

    public EnumC0091Aba(String str, int i, AI3 ai3) {
        this(str, i, ai3, R4f.a);
    }

    @Override // defpackage.S4f
    public final BI3 T0() {
        return this;
    }
}
