package defpackage;

import java.util.Locale;

/* renamed from: xth, reason: case insensitive filesystem */
/* loaded from: classes.dex */
public enum EnumC46182xth implements R1g {
    PROCESS_CREATED(null),
    PLATFORM_G2_END(null),
    CAMERA_PREPARE_TRIGGERED(EnumC7231Nd7.CAMERA_ANDROID_PREPARE_TRIGGERED),
    CAMERA_PREPARE_COMPLETE(EnumC7231Nd7.CAMERA_ANDROID_PREPARE_COMPLETED),
    CAMERA_OPEN_TRIGGERED(EnumC7231Nd7.CAMERA_ANDROID_SERVICE_OPEN_TRIGGERED),
    CAMERA_OPENED(EnumC7231Nd7.CAMERA_ANDROID_SERVICE_OPEN_COMPLETED),
    CAMERA_FEATURE_READY(null),
    SHARED_SURFACE_CREATED(null),
    FIRST_UI_RENDERED(null),
    FIRST_STABLE_UI_RENDERED(null),
    CAPTURE_BUTTON_CLICKABLE(EnumC7231Nd7.CAMERA_ANDROID_CAPTURE_BUTTON_CLICKABLE),
    ENABLE_STREAMING_TRIGGERED(EnumC7231Nd7.CAMERA_ANDROID_ENABLE_STREAMING_TRIGGERED),
    START_PREVIEW_TRIGGERED(EnumC7231Nd7.CAMERA_ANDROID_START_PREVIEW_TRIGGERED),
    START_PREVIEW_BG_THREAD_COMPLETE(EnumC7231Nd7.CAMERA_ANDROID_START_PREVIEW_BG_THREAD_COMPLETED),
    FIRST_PREVIEW_FRAME_RECEIVED(EnumC7231Nd7.CAMERA_FIRST_PREVIEW_FRAME_RECEIVED),
    FIRST_PREVIEW_FRAME_RENDERED(EnumC7231Nd7.CAMERA_FIRST_PREVIEW_FRAME_RENDERED),
    START_PREVIEW_UI_THREAD_COMPLETE(EnumC7231Nd7.CAMERA_ANDROID_START_PREVIEW_MAIN_THREAD_COMPLETED);

    public final EnumC7231Nd7 a;

    EnumC46182xth(EnumC7231Nd7 enumC7231Nd7) {
        this.a = enumC7231Nd7;
    }

    @Override // defpackage.Q1g
    public final String a() {
        return "startup:".concat(name().toLowerCase(Locale.ROOT));
    }

    @Override // defpackage.Q1g
    public final String b() {
        return name();
    }
}
