package defpackage;

import com.snapchat.client.messaging.Tweaks;
import java.util.concurrent.TimeUnit;

/* JADX WARN: Enum visitor error
jadx.core.utils.exceptions.JadxRuntimeException: Init of enum field 'e0' uses external variables
	at jadx.core.dex.visitors.EnumVisitor.createEnumFieldByConstructor(EnumVisitor.java:451)
	at jadx.core.dex.visitors.EnumVisitor.processEnumFieldByField(EnumVisitor.java:372)
	at jadx.core.dex.visitors.EnumVisitor.processEnumFieldByWrappedInsn(EnumVisitor.java:337)
	at jadx.core.dex.visitors.EnumVisitor.extractEnumFieldsFromFilledArray(EnumVisitor.java:322)
	at jadx.core.dex.visitors.EnumVisitor.extractEnumFieldsFromInsn(EnumVisitor.java:262)
	at jadx.core.dex.visitors.EnumVisitor.convertToEnum(EnumVisitor.java:151)
	at jadx.core.dex.visitors.EnumVisitor.visit(EnumVisitor.java:100)
 */
/* JADX WARN: Failed to restore enum class, 'enum' modifier and super class removed */
/* renamed from: Rud, reason: case insensitive filesystem */
/* loaded from: classes.dex */
public final class EnumC9768Rud implements BI3 {
    public static final EnumC9768Rud A0;
    public static final EnumC9768Rud A1;
    public static final EnumC9768Rud A2;
    public static final EnumC9768Rud B0;
    public static final EnumC9768Rud B1;
    public static final EnumC9768Rud B2;
    public static final EnumC9768Rud C0;
    public static final EnumC9768Rud C1;
    public static final EnumC9768Rud C2;
    public static final EnumC9768Rud D0;
    public static final EnumC9768Rud D1;
    public static final EnumC9768Rud D2;
    public static final EnumC9768Rud E0;
    public static final EnumC9768Rud E1;
    public static final EnumC9768Rud E2;
    public static final EnumC9768Rud F0;
    public static final EnumC9768Rud F1;
    public static final EnumC9768Rud F2;
    public static final EnumC9768Rud G0;
    public static final EnumC9768Rud G1;
    public static final EnumC9768Rud G2;
    public static final EnumC9768Rud H0;
    public static final EnumC9768Rud H1;
    public static final EnumC9768Rud H2;
    public static final EnumC9768Rud I0;
    public static final EnumC9768Rud I1;
    public static final EnumC9768Rud I2;
    public static final EnumC9768Rud J0;
    public static final EnumC9768Rud J1;
    public static final EnumC9768Rud J2;
    public static final EnumC9768Rud K0;
    public static final EnumC9768Rud K1;
    public static final EnumC9768Rud K2;
    public static final EnumC9768Rud L0;
    public static final EnumC9768Rud L1;
    public static final EnumC9768Rud L2;
    public static final EnumC9768Rud M0;
    public static final EnumC9768Rud M1;
    public static final EnumC9768Rud M2;
    public static final EnumC9768Rud N0;
    public static final EnumC9768Rud N1;
    public static final EnumC9768Rud N2;
    public static final EnumC9768Rud O0;
    public static final EnumC9768Rud O1;
    public static final EnumC9768Rud O2;
    public static final EnumC9768Rud P0;
    public static final EnumC9768Rud P1;
    public static final EnumC9768Rud P2;
    public static final EnumC9768Rud Q0;
    public static final EnumC9768Rud Q1;
    public static final EnumC9768Rud Q2;
    public static final EnumC9768Rud R0;
    public static final EnumC9768Rud R1;
    public static final EnumC9768Rud R2;
    public static final EnumC9768Rud S0;
    public static final EnumC9768Rud S1;
    public static final EnumC9768Rud S2;
    public static final EnumC9768Rud T0;
    public static final EnumC9768Rud T1;
    public static final EnumC9768Rud T2;
    public static final EnumC9768Rud U0;
    public static final EnumC9768Rud U1;
    public static final EnumC9768Rud U2;
    public static final EnumC9768Rud V0;
    public static final EnumC9768Rud V1;
    public static final EnumC9768Rud V2;
    public static final EnumC9768Rud W0;
    public static final EnumC9768Rud W1;
    public static final EnumC9768Rud W2;
    public static final EnumC9768Rud X0;
    public static final EnumC9768Rud X1;
    public static final EnumC9768Rud X2;
    public static final EnumC9768Rud Y0;
    public static final EnumC9768Rud Y1;
    public static final /* synthetic */ EnumC9768Rud[] Y2;
    public static final EnumC9768Rud Z0;
    public static final EnumC9768Rud Z1;
    public static final EnumC9768Rud a1;
    public static final EnumC9768Rud a2;
    public static final EnumC9768Rud b1;
    public static final EnumC9768Rud b2;
    public static final EnumC9768Rud c1;
    public static final EnumC9768Rud c2;
    public static final EnumC9768Rud d1;
    public static final EnumC9768Rud d2;
    public static final EnumC9768Rud e0;
    public static final EnumC9768Rud e1;
    public static final EnumC9768Rud e2;
    public static final EnumC9768Rud f0;
    public static final EnumC9768Rud f1;
    public static final EnumC9768Rud f2;
    public static final EnumC9768Rud g0;
    public static final EnumC9768Rud g1;
    public static final EnumC9768Rud g2;
    public static final EnumC9768Rud h0;
    public static final EnumC9768Rud h1;
    public static final EnumC9768Rud h2;
    public static final EnumC9768Rud i0;
    public static final EnumC9768Rud i1;
    public static final EnumC9768Rud i2;
    public static final EnumC9768Rud j0;
    public static final EnumC9768Rud j1;
    public static final EnumC9768Rud j2;
    public static final EnumC9768Rud k0;
    public static final EnumC9768Rud k1;
    public static final EnumC9768Rud k2;
    public static final EnumC9768Rud l0;
    public static final EnumC9768Rud l1;
    public static final EnumC9768Rud l2;
    public static final EnumC9768Rud m0;
    public static final EnumC9768Rud m1;
    public static final EnumC9768Rud m2;
    public static final EnumC9768Rud n0;
    public static final EnumC9768Rud n1;
    public static final EnumC9768Rud n2;
    public static final EnumC9768Rud o0;
    public static final EnumC9768Rud o1;
    public static final EnumC9768Rud o2;
    public static final EnumC9768Rud p0;
    public static final EnumC9768Rud p1;
    public static final EnumC9768Rud p2;
    public static final EnumC9768Rud q0;
    public static final EnumC9768Rud q1;
    public static final EnumC9768Rud q2;
    public static final EnumC9768Rud r0;
    public static final EnumC9768Rud r1;
    public static final EnumC9768Rud r2;
    public static final EnumC9768Rud s0;
    public static final EnumC9768Rud s1;
    public static final EnumC9768Rud s2;
    public static final EnumC9768Rud t0;
    public static final EnumC9768Rud t1;
    public static final EnumC9768Rud t2;
    public static final EnumC9768Rud u0;
    public static final EnumC9768Rud u1;
    public static final EnumC9768Rud u2;
    public static final EnumC9768Rud v0;
    public static final EnumC9768Rud v1;
    public static final EnumC9768Rud v2;
    public static final EnumC9768Rud w0;
    public static final EnumC9768Rud w1;
    public static final EnumC9768Rud w2;
    public static final EnumC9768Rud x0;
    public static final EnumC9768Rud x1;
    public static final EnumC9768Rud x2;
    public static final EnumC9768Rud y0;
    public static final EnumC9768Rud y1;
    public static final EnumC9768Rud y2;
    public static final EnumC9768Rud z0;
    public static final EnumC9768Rud z1;
    public static final EnumC9768Rud z2;
    public final AI3 a;
    public static final EnumC9768Rud b = new EnumC9768Rud("BANDWIDTH_LOG_VIEWER", 0, QR1.I(true));
    public static final EnumC9768Rud c = new EnumC9768Rud("MEMORY_LOG_VIEWER", 1, QR1.I(true));
    public static final EnumC9768Rud t = new EnumC9768Rud("KERNEL_MEMORY_LOG_VIEWER", 2, QR1.I(false));
    public static final EnumC9768Rud X = new EnumC9768Rud("CPU_GPU_LOG_VIEWER", 3, QR1.I(false));
    public static final EnumC9768Rud Y = new EnumC9768Rud("TIMBER_LOGCAT_IMMEDIATELY", 4, QR1.I(false));
    public static final EnumC9768Rud Z = new EnumC9768Rud("STARTUP_MODE", 5, QR1.K(EnumC40836tth.a));

    static {
        AI3 I = QR1.I(false);
        AI3.r(I, "finish_activity_on_back", "enabled", 4);
        e0 = new EnumC9768Rud("FINISH_ACTIVITY_ON_BACK", 6, I);
        AI3 I3 = QR1.I(false);
        I3.t = "EXTEND_NAV_BAR_TAP_TARGET_FULL_HEIGHT";
        f0 = new EnumC9768Rud("EXTEND_NAV_BAR_TAP_TARGET_FULL_HEIGHT", 7, I3);
        g0 = new EnumC9768Rud("USERNAME_V2_DECORATE_IF_DIFFERENT", 8, QR1.I(false));
        h0 = new EnumC9768Rud("USERNAME_V2_DECORATE_DISPLAY", 9, QR1.I(false));
        i0 = new EnumC9768Rud("LOW_END_DEVICE_MODE", 10, QR1.I(false));
        j0 = new EnumC9768Rud("TAB_NAVIGATION_MODE", 11, QR1.I(false));
        AI3 I4 = QR1.I(false);
        AI3.r(I4, "LOW_END_DEVICE_NO_ANIMATION_AB", "ENABLED", 4);
        k0 = new EnumC9768Rud("NO_ANIMATION_MODE", 12, I4);
        AI3 R = QR1.R("");
        AI3.r(R, "DECK_PAGE_PURGE_CLIENT", "BACKGROUND_PURGE_PAGE_TYPES", 4);
        l0 = new EnumC9768Rud("DECK_PAGE_BACKGROUND_PURGE_PAGE_TYPES", 13, R);
        AI3 R3 = QR1.R("");
        AI3.r(R3, "DECK_PAGE_LOW_MEMORY_PURGE", "LOW_MEMORY_PURGE_PAGE_TYPES", 4);
        m0 = new EnumC9768Rud("DECK_PAGE_LOW_MEMORY_PURGE_PAGE_TYPES", 14, R3);
        n0 = new EnumC9768Rud("FEATURE_CONFIG_SYNCED_TOOLTIPS", 15, QR1.I(false));
        AI3 M = QR1.M(0);
        M.t = "display-notch-height";
        o0 = new EnumC9768Rud("DISPLAY_NOTCH_HEIGHT", 16, M);
        AI3 K = QR1.K(EnumC9224Qud.a);
        K.t = "device_has_soft_nav_bar";
        p0 = new EnumC9768Rud("HAS_SOFT_NAV_BAR", 17, K);
        q0 = new EnumC9768Rud("NGS_MODE", 18, QR1.M(5));
        AI3 M3 = QR1.M(30);
        M3.t = "NEW_USER_SHOW_LABEL_DAYS";
        r0 = new EnumC9768Rud("NV_SHOW_LABEL_DAYS", 19, M3);
        AI3 I5 = QR1.I(false);
        I5.t = "SHOULD_DISPLAY_NAVIGATION_LABEL";
        s0 = new EnumC9768Rud("SHOULD_DISPLAY_NAVIGATION_LABEL", 20, I5);
        AI3 I6 = QR1.I(false);
        I6.t = "DISABLE_LOCAL_30_DAY_LABEL_CHECK";
        t0 = new EnumC9768Rud("DISABLE_LOCAL_LABEL_CHECK", 21, I6);
        u0 = new EnumC9768Rud("NV_NEW_CAMERA_BADGE_AVAILABLE_DAYS", 22, QR1.M(14));
        AI3 I7 = QR1.I(false);
        AI3.r(I7, "CONNECTIVITY_STATUS_INDICATOR", "ENABLED", 4);
        v0 = new EnumC9768Rud("CONNECTIVITY_STATUS_INDICATOR", 23, I7);
        AI3 M4 = QR1.M(-1);
        M4.t = "platform_main_thread_stuck_detector_threshold_ms";
        w0 = new EnumC9768Rud("MAIN_THREAD_STUCK_DETECTOR_THRESHOLD_MS", 24, M4);
        AI3 N = QR1.N(0L);
        N.t = "RUN_ACTIVITY_OBSERVERS_IN_BACKGROUND";
        x0 = new EnumC9768Rud("RUN_ACTIVITY_OBSERVERS_IN_BACKGROUND", 25, N);
        AI3 M5 = QR1.M(40);
        M5.t = "BACKGROUND_ACTIVITY_OBSERVERS_BUFFER_SIZE";
        y0 = new EnumC9768Rud("BACKGROUND_ACTIVITY_OBSERVERS_BUFFER_SIZE", 26, M5);
        AI3 I8 = QR1.I(false);
        I8.t = "USE_MULTIBIND_ACTIVITY_OBSERVERS";
        z0 = new EnumC9768Rud("USE_MULTIBIND_ACTIVITY_OBSERVERS", 27, I8);
        A0 = new EnumC9768Rud("SIG_APP_APPEARANCE_CONFIG", 28, QR1.M(2));
        AI3 I9 = QR1.I(false);
        I9.t = "ANDROID_CLEAN_PAGE_FACTORY_ON_NAV_HOST_DESTROY";
        B0 = new EnumC9768Rud("CLEAN_PAGE_FACTORY_ON_NAV_HOST_DESTROY", 29, I9);
        AI3 I10 = QR1.I(false);
        I10.t = "SIG_ANDROID_APP_APPEARANCE_USE_ACTIVITY_RESTART";
        C0 = new EnumC9768Rud("SIG_APP_APPEARANCE_USE_ACTIVITY_RESTART", 30, I10);
        AI3 I11 = QR1.I(false);
        I11.t = "ANDROID_APP_UPGRADE_FLEXIBLE_ELIGIBLE";
        D0 = new EnumC9768Rud("APP_UPGRADE_FLEXIBLE_ELIGIBLE", 31, I11);
        AI3 N3 = QR1.N(TimeUnit.DAYS.toMillis(3L));
        N3.t = "ANDROID_APP_UPGRADE_FLEXIBLE_PROMPT_COOLDOWN";
        E0 = new EnumC9768Rud("APP_UPGRADE_FLEXIBLE_PROMPT_COOLDOWN", 32, N3);
        F0 = new EnumC9768Rud("APP_UPDATE_ELIGIBILITY_CHECK", 33, QR1.I(true));
        G0 = new EnumC9768Rud("APP_UPDATE_ELIGIBILITY_SET_TIMESTAMP_MS", 34, QR1.N(0L));
        AI3 N4 = QR1.N(2592000000L);
        N4.t = "ANDROID_APP_UPDATE_ELIGIBILITY_EXPIRY_MS";
        H0 = new EnumC9768Rud("APP_UPDATE_ELIGIBILITY_EXPIRY_MS", 35, N4);
        AI3 I12 = QR1.I(false);
        I12.t = "CRITICAL_WORK_PAUSE_DURABLE_JOBS";
        I0 = new EnumC9768Rud("CRITICAL_WORK_PAUSE_DURABLE_JOBS", 36, I12);
        AI3 I13 = QR1.I(true);
        I13.t = "CRITICAL_WORK_PAUSE_NON_CRITICAL_DURABLE_JOBS";
        J0 = new EnumC9768Rud("CRITICAL_WORK_PAUSE_NON_CRITICAL_DURABLE_JOBS", 37, I13);
        AI3 I14 = QR1.I(false);
        I14.t = "CRITICAL_WORK_PAGE_TRANSITIONS";
        K0 = new EnumC9768Rud("CRITICAL_WORK_PAGE_TRANSITIONS", 38, I14);
        AI3 N5 = QR1.N(4000L);
        N5.t = "critical_work_main_activity_startup_critical_section_timeout_ms";
        L0 = new EnumC9768Rud("CRITICAL_WORK_MAIN_ACTIVITY_STARTUP_CRITICAL_SECTION_TIMEOUT_MS", 39, N5);
        AI3 I15 = QR1.I(false);
        I15.t = "delay_non_critical_startup_acitivty_observer_after_critical_section";
        M0 = new EnumC9768Rud("DELAY_NON_CRITICAL_STARTUP_ACTIVITY_OBSERVER_AFTER_CRITICAL_SECTION", 40, I15);
        AI3 I16 = QR1.I(false);
        I16.t = "delay_non_critical_startup_activity_observer_on_idle_scheduler";
        N0 = new EnumC9768Rud("DELAY_NON_CRITICAL_STARTUP_ACTIVITY_OBSERVER_ON_IDLE_SCHEDULER", 41, I16);
        AI3 I17 = QR1.I(false);
        I17.t = "page_load_signal_on_critical_section";
        O0 = new EnumC9768Rud("PAGE_LOAD_SIGNAL_ON_CRITICAL_SECTION", 42, I17);
        AI3 I18 = QR1.I(true);
        I18.t = "UPDATE_SCHEDULERS_CONFIGS_VIA_DURABLE_JOB";
        P0 = new EnumC9768Rud("UPDATE_SCHEDULERS_CONFIGS_VIA_DURABLE_JOB", 43, I18);
        AI3 N6 = QR1.N(4000L);
        N6.t = "page_load_signal_critical_section_timeout_ms";
        Q0 = new EnumC9768Rud("PAGE_LOAD_SIGNAL_CRITICAL_SECTION_TIMEOUT_MS", 44, N6);
        R0 = new EnumC9768Rud("HISTORICAL_EXIT_REASONS_LAST_PID", 45, QR1.M(0));
        AI3 I19 = QR1.I(false);
        I19.t = "PLATFORM_COF_LOCALIZATION_PSEUDOLOCALE_ENABLED";
        S0 = new EnumC9768Rud("PLATFORM_COF_LOCALIZATION_PSEUDOLOCALE_ENABLED", 46, I19);
        AI3 R4 = QR1.R("UNSET");
        R4.t = "PLATFORM_COF_LOCALIZATION_OVERRIDE_LOCALE";
        T0 = new EnumC9768Rud("PLATFORM_COF_LOCALIZATION_OVERRIDE_LOCALE", 47, R4);
        AI3 I20 = QR1.I(false);
        I20.t = "PLATFORM_COF_ENABLE_L10N_ISSUE_DETECTORS";
        U0 = new EnumC9768Rud("PLATFORM_COF_ENABLE_L10N_ISSUE_DETECTORS", 48, I20);
        V0 = new EnumC9768Rud("LOCALIZATION_RTL_PSEUDOLOCALE_ENABLED", 49, QR1.I(false));
        AI3 I21 = QR1.I(false);
        AI3.r(I21, "PROCESS_RESTART_JOB", "ENABLE_PROCESS_RESTART_JOB", 4);
        W0 = new EnumC9768Rud("ENABLE_PROCESS_RESTART_JOB", 50, I21);
        AI3 M6 = QR1.M(29);
        AI3.r(M6, "PROCESS_RESTART_JOB", "PROCESS_RESTART_MAX_ANDROID_VERSION", 4);
        X0 = new EnumC9768Rud("PROCESS_RESTART_MAX_ANDROID_VERSION", 51, M6);
        AI3 N7 = QR1.N(10L);
        AI3.r(N7, "PROCESS_RESTART_JOB", "DEVICE_MEMORY_MAX_THRESHOLD_GB", 4);
        Y0 = new EnumC9768Rud("DEVICE_MEMORY_MAX_THRESHOLD_GB", 52, N7);
        AI3 N8 = QR1.N(800L);
        AI3.r(N8, "PROCESS_RESTART_JOB", "OOM_SCORE_MIN_THRESHOLD", 4);
        Z0 = new EnumC9768Rud("OOM_SCORE_MIN_THRESHOLD", 53, N8);
        AI3 N9 = QR1.N(35L);
        AI3.r(N9, "PROCESS_RESTART_JOB", "PROCESS_RESTART_JOB_RECURRING_DELAY_MINS", 4);
        a1 = new EnumC9768Rud("PROCESS_RESTART_JOB_RECURRING_DELAY_MINS", 54, N9);
        DI3 di3 = DI3.c;
        AI3 ai3 = new AI3(di3, (Object) 30L);
        AI3.r(ai3, "PROCESS_RESTART_JOB", "PROCESS_TIME_MIN_THRESHOLD_MINS", 4);
        b1 = new EnumC9768Rud("PROCESS_TIME_MIN_THRESHOLD_MINS", 55, ai3);
        AI3 ai32 = new AI3(di3, (Object) 30L);
        AI3.r(ai32, "PROCESS_RESTART_JOB", "ACTIVE_USER_TIME_MIN_THRESHOLD_MINS", 4);
        c1 = new EnumC9768Rud("ACTIVE_USER_TIME_MIN_THRESHOLD_MINS", 56, ai32);
        AI3 N10 = QR1.N(1440L);
        AI3.r(N10, "PROCESS_RESTART_JOB", "BACKGROUND_TIME_MIN_THRESHOLD_MINS", 4);
        d1 = new EnumC9768Rud("BACKGROUND_TIME_MIN_THRESHOLD_MINS", 57, N10);
        e1 = new EnumC9768Rud("ACTIVE_USER_TIME_MS", 58, QR1.N(0L));
        AI3 I22 = QR1.I(true);
        I22.t = "android_s_content_capture_enabled";
        f1 = new EnumC9768Rud("ANDROID_S_CONTENT_CAPTURE_ENABLED", 59, I22);
        AI3 I23 = QR1.I(false);
        I23.t = "android_best_friends_widget_force_enabled";
        g1 = new EnumC9768Rud("ANDROID_BEST_FRIENDS_WIDGET_FORCE_ENABLED", 60, I23);
        AI3 I24 = QR1.I(false);
        I24.t = "android_best_friends_widget_force_disabled";
        h1 = new EnumC9768Rud("ANDROID_BEST_FRIENDS_WIDGET_FORCE_DISABLED", 61, I24);
        AI3 I25 = QR1.I(false);
        I25.s(584);
        i1 = new EnumC9768Rud("CAMERA_LOCKSCREEN_IS_PRIVACY_DISCLAIMER_ACCEPTED", 62, I25);
        j1 = new EnumC9768Rud("CAMERA_LOCKSCREEN_FORCE_IS_PRIVACY_DISCLAIMER_ACCEPTED", 63, QR1.I(false));
        AI3 N11 = QR1.N(0L);
        N11.s(585);
        k1 = new EnumC9768Rud("CAMERA_LOCKSCREEN_ENROLLMENT_PROMPT_LAST_SEEN", 64, N11);
        AI3 M7 = QR1.M(0);
        M7.s(586);
        l1 = new EnumC9768Rud("CAMERA_LOCKSCREEN_ENROLLMENT_PROMPT_SEEN_COUNT", 65, M7);
        m1 = new EnumC9768Rud("CAMERA_LOCKSCREEN_ENROLLMENT_PROMPT_SEEN_DEVICE_LIST_SIZE_LIMIT", 66, QR1.M(3));
        AI3 R5 = QR1.R("");
        R5.s(876);
        n1 = new EnumC9768Rud("CAMERA_LOCKSCREEN_ENROLLMENT_PROMPT_SEEN_DEVICE_LIST", 67, R5);
        AI3 I26 = QR1.I(false);
        I26.t = "camera_enable_lock_screen_mode";
        o1 = new EnumC9768Rud("CAMERA_LOCKSCREEN_TO_CAMERA_ENABLED", 68, I26);
        AI3 I27 = QR1.I(false);
        I27.t = "camera_quick_tap_to_camera_switch_processor_enabled";
        p1 = new EnumC9768Rud("CAMERA_LOCKSCREEN_TO_CAMERA_SWITCH_PROCESSOR_ENABLED", 69, I27);
        q1 = new EnumC9768Rud("CAMERA_LOCKSCREEN_TO_CAMERA_FORCE_ENABLED", 70, QR1.I(false));
        r1 = new EnumC9768Rud("CAMERA_LOCKSCREEN_TO_CAMERA_SERVICE_TYPE", 71, QR1.K(EnumC8680Pud.a));
        AI3 I28 = QR1.I(false);
        I28.t = "camera_quick_tap_to_camera_allow_deeplink_override_tweak";
        s1 = new EnumC9768Rud("CAMERA_LOCKSCREEN_TO_CAMERA_DEEPLINK_OVERRIDE_ALLOWED", 72, I28);
        t1 = new EnumC9768Rud("CAMERA_LOCKSCREEN_TO_CAMERA_DEEPLINK_OVERRIDE", 73, QR1.I(false));
        u1 = new EnumC9768Rud("CAMERA_LOCKSCREEN_UNLOCK_TO_CAMERA_STATUS_RESPONSE", 74, QR1.K(EnumC7592Nud.a));
        v1 = new EnumC9768Rud("CAMERA_LOCKSCREEN_UNLOCK_TO_CAMERA_TARGET_RESPONSE", 75, QR1.K(EnumC8136Oud.a));
        AI3 M8 = QR1.M(3);
        M8.t = "camera_android_quick_tap_promo_max_views";
        w1 = new EnumC9768Rud("CAMERA_LOCKSCREEN_UNLOCK_TO_CAMERA_PROMPT_MAX_VIEWS", 76, M8);
        x1 = new EnumC9768Rud("CAMERA_LOCKSCREEN_PENDING_ON_TARGET_RESPONSE", 77, QR1.I(false));
        y1 = new EnumC9768Rud("DISPOSABLE_RELEASER_VIOLATION_ENABLED", 78, QR1.I(false));
        AI3 M9 = QR1.M(240);
        M9.t = "PLATFORM_BG_DATA_SYNC";
        z1 = new EnumC9768Rud("PLATFORM_BG_DATA_SYNC_MINS", 79, M9);
        AI3 I29 = QR1.I(false);
        I29.t = "PLATFORM_DATA_SYNC_ON_NAV";
        A1 = new EnumC9768Rud("PLATFORM_DATA_SYNC_ON_NAV", 80, I29);
        AI3 I30 = QR1.I(false);
        I30.t = "STARTUP_SYNCERS_RUN_IN_PARALLEL";
        B1 = new EnumC9768Rud("STARTUP_SYNCERS_RUN_IN_PARALLEL", 81, I30);
        AI3 M10 = QR1.M(7);
        M10.t = "PARALLEL_SYNCERS_CONCURRENCY_LIMIT";
        C1 = new EnumC9768Rud("PARALLEL_SYNCERS_CONCURRENCY_LIMIT", 82, M10);
        AI3 I31 = QR1.I(false);
        I31.t = "STARTUP_NAVIGATE_EARLY";
        D1 = new EnumC9768Rud("STARTUP_NAVIGATE_EARLY", 83, I31);
        AI3 M11 = QR1.M(10);
        M11.t = "MAX_IO_CONCURRENT_TASKS";
        E1 = new EnumC9768Rud("MAX_IO_CONCURRENT_TASKS", 84, M11);
        AI3 M12 = QR1.M(4);
        M12.t = "IO_THREAD_POOL_PRIORITY";
        F1 = new EnumC9768Rud("IO_THREAD_POOL_PRIORITY", 85, M12);
        AI3 M13 = QR1.M(10);
        M13.t = "CPU_THREAD_POOL_PRIORITY";
        G1 = new EnumC9768Rud("CPU_THREAD_POOL_PRIORITY", 86, M13);
        AI3 L = QR1.L(1.0f);
        L.t = "UI_BG_THREAD_POOL_SIZE_MULTIPLIER";
        H1 = new EnumC9768Rud("UI_BG_THREAD_POOL_SIZE_MULTIPLIER", 87, L);
        AI3 L3 = QR1.L(1.0f);
        L3.t = "CPU_THREAD_POOL_SIZE_MULTIPLIER";
        I1 = new EnumC9768Rud("CPU_THREAD_POOL_SIZE_MULTIPLIER", 88, L3);
        AI3 M14 = QR1.M(5);
        M14.t = "DB_QUERIES_THREAD_POOL_SIZE";
        J1 = new EnumC9768Rud("DB_QUERIES_THREAD_POOL_SIZE", 89, M14);
        AI3 I32 = QR1.I(false);
        I32.t = "IDLE_SCHEDULER_USE_CPU_POOL";
        K1 = new EnumC9768Rud("IDLE_SCHEDULER_USE_CPU_POOL", 90, I32);
        AI3 I33 = QR1.I(false);
        I33.t = "UI_BG_SCHEDULER_USE_CPU_POOL";
        L1 = new EnumC9768Rud("UI_BG_SCHEDULER_USE_CPU_POOL", 91, I33);
        AI3 I34 = QR1.I(false);
        I34.t = "BLIZZARD_SCHEDULER_ENABLED";
        M1 = new EnumC9768Rud("BLIZZARD_SCHEDULER_ENABLED", 92, I34);
        AI3 M15 = QR1.M(2);
        M15.t = "BLIZZARD_THREAD_POOL_SIZE";
        N1 = new EnumC9768Rud("BLIZZARD_THREAD_POOL_SIZE", 93, M15);
        AI3 M16 = QR1.M(10);
        M16.t = "BLIZZARD_THREAD_PRIORITY";
        O1 = new EnumC9768Rud("BLIZZARD_THREAD_PRIORITY", 94, M16);
        AI3 N12 = QR1.N(5000L);
        N12.t = "LEAK_CANARY_HEAPDUMP_DELAY_MS";
        P1 = new EnumC9768Rud("LEAK_CANARY_HEAPDUMP_DELAY_MS", 95, N12);
        AI3 b3 = AI3.b(new byte[0]);
        b3.t = "SNAP_PRIORITY_QUEUE_CONFIG";
        Q1 = new EnumC9768Rud("SNAP_PRIORITY_QUEUE_CONFIG", 96, b3);
        AI3 b4 = AI3.b(new byte[0]);
        b4.t = "SNAP_UI_AWARE_QUEUE_CONFIG";
        R1 = new EnumC9768Rud("SNAP_UI_AWARE_QUEUE_CONFIG", 97, b4);
        AI3 I35 = QR1.I(false);
        I35.t = "SNAP_SCHEDULERS_USE_ASER_V2";
        S1 = new EnumC9768Rud("SNAP_SCHEDULERS_USE_ASER_V2", 98, I35);
        AI3 I36 = QR1.I(false);
        I36.t = "ANDROID_GROWTH_METRICS_REPORTING";
        T1 = new EnumC9768Rud("GROWTH_METRICS_REPORTING", 99, I36);
        AI3 I37 = QR1.I(false);
        I37.t = "cam_screen_param_async_update";
        U1 = new EnumC9768Rud("CAMERA_SCREEN_PARAM_ASYNC_UPDATE", 100, I37);
        AI3 I38 = QR1.I(true);
        I38.t = "COMPLETABLE_SUBSCRIBE_SAFE_ALLOWLISTED";
        V1 = new EnumC9768Rud("COMPLETABLE_SUBSCRIBE_SAFE_ALLOWLISTED", 101, I38);
        W1 = new EnumC9768Rud("CACHED_SURFACE_VIEW_LAYOUT_PARAMS", 102, QR1.N(0L));
        AI3 I39 = QR1.I(false);
        I39.t = "ANDROID_ENABLE_FALLBACK_PAGE_FOR_NON_FIXED_PAGES";
        X1 = new EnumC9768Rud("ENABLE_FALLBACK_PAGE_FOR_NON_FIXED_PAGES", 103, I39);
        AI3 I40 = QR1.I(false);
        I40.t = "G2X_ENABLE_NAV_DEST_SIGNALER_ON_LOGIN_ACTIVITY";
        Y1 = new EnumC9768Rud("G2X_ENABLE_NAV_DEST_SIGNALER_ON_LOGIN_ACTIVITY", 104, I40);
        AI3 N13 = QR1.N(0L);
        N13.t = "G2X_REQUIRE_NON_JANK_FRAMES";
        Z1 = new EnumC9768Rud("G2X_REQUIRE_NON_JANK_FRAMES", 105, N13);
        AI3 L4 = QR1.L(2.0f);
        L4.t = "UI_JANK_HEURISTIC_MULTIPLIER";
        a2 = new EnumC9768Rud("UI_JANK_HEURISTIC_MULTIPLIER", 106, L4);
        AI3 I41 = QR1.I(false);
        I41.t = "CRASH_ON_LARGE_BITMAPS";
        b2 = new EnumC9768Rud("CRASH_ON_LARGE_BITMAPS", 107, I41);
        AI3 I42 = QR1.I(false);
        I42.t = "LOG_LARGE_BITMAPS";
        c2 = new EnumC9768Rud("LOG_LARGE_BITMAPS", 108, I42);
        AI3 I43 = QR1.I(false);
        I43.t = "REPORT_NON_FATAL_ON_HOT_PHONE";
        d2 = new EnumC9768Rud("REPORT_NON_FATAL_ON_HOT_PHONE", Tweaks.MAX_HOURS_AFTER_STREAK_EXPIRE_TO_ENABLE_RESTORE, I43);
        AI3 M17 = QR1.M(0);
        M17.t = "HOT_PHONE_NON_FATAL_REPORTING_SAMPLING_RATE";
        e2 = new EnumC9768Rud("HOT_PHONE_NON_FATAL_REPORTING_SAMPLING_RATE", Tweaks.ENABLE_STREAK_EDUCATION, M17);
        AI3 I44 = QR1.I(false);
        I44.t = "HIGH_CPU_USAGE_DETECTION_ENABLED";
        f2 = new EnumC9768Rud("HIGH_CPU_USAGE_DETECTION_ENABLED", 111, I44);
        AI3 M18 = QR1.M(10);
        M18.t = "THREAD_CPU_USAGE_POLLING_FREQUENCY_SECONDS";
        g2 = new EnumC9768Rud("THREAD_CPU_USAGE_POLLING_FREQUENCY_SECONDS", 112, M18);
        AI3 M19 = QR1.M(2);
        M19.t = "PROCESS_CPU_USAGE_POLLING_FREQUENCY_SECONDS";
        h2 = new EnumC9768Rud("PROCESS_CPU_USAGE_POLLING_FREQUENCY_SECONDS", Tweaks.DELTA_SYNC_SQLITE_SHARED_STORAGE_CACHE_SIZE, M19);
        AI3 M20 = QR1.M(10);
        M20.t = "HIGH_CPU_NON_FATAL_SAMPLING_RATE";
        i2 = new EnumC9768Rud("HIGH_CPU_NON_FATAL_SAMPLING_RATE", Tweaks.FAIL_DECRYPT_FOR_DUPLEX_SNAPS_TEST_ONLY, M20);
        AI3 M21 = QR1.M(180);
        M21.t = "HIGH_CPU_USAGE_DETECTION_TIME_WINDOW_SECONDS";
        j2 = new EnumC9768Rud("HIGH_CPU_USAGE_DETECTION_TIME_WINDOW_SECONDS", 115, M21);
        AI3 M22 = QR1.M(25);
        M22.t = "HIGH_CPU_USAGE_DETECTION_PERCENTAGE_THRESHOLD";
        k2 = new EnumC9768Rud("HIGH_CPU_USAGE_DETECTION_PERCENTAGE_THRESHOLD", 116, M22);
        AI3 M23 = QR1.M(25);
        M23.t = "CPU_USAGE_THRESHOLD_CPU_AWARE_SCHEDULER";
        l2 = new EnumC9768Rud("CPU_USAGE_THRESHOLD_CPU_AWARE_SCHEDULER", 117, M23);
        AI3 M24 = QR1.M(0);
        M24.t = "BITMAP_ANALYSIS_SAMPLING_RATE";
        m2 = new EnumC9768Rud("BITMAP_ANALYSIS_SAMPLING_RATE", 118, M24);
        AI3 I45 = QR1.I(false);
        I45.t = "PLATFORM_HOVA_AVATAR_BADGE_USE_UPDATE_STRATEGY";
        n2 = new EnumC9768Rud("PLATFORM_HOVA_AVATAR_BADGE_USE_UPDATE_STRATEGY", 119, I45);
        AI3 I46 = QR1.I(false);
        I46.t = "PLATFORM_HOVA_ADD_FRIENDS_BADGE_USE_UPDATE_STRATEGY";
        o2 = new EnumC9768Rud("PLATFORM_HOVA_ADD_FRIENDS_BADGE_USE_UPDATE_STRATEGY", 120, I46);
        AI3 K3 = QR1.K(EnumC7048Mud.a);
        K3.t = "PLATFORM_DELAY_HOVA_COMPONENT_UPDATE_STRATEGY";
        p2 = new EnumC9768Rud("PLATFORM_HOVA_COMPONENT_UPDATE_STRATEGY", 121, K3);
        q2 = new EnumC9768Rud("ENABLE_SCREENSHOT_DETECTION", 122, QR1.I(true));
        AI3 I47 = QR1.I(false);
        I47.t = "SCHEDULER_METRICS_REPORTING_ENABLED";
        r2 = new EnumC9768Rud("SCHEDULER_METRICS_REPORTING_ENABLED", 123, I47);
        AI3 N14 = QR1.N(2000L);
        N14.t = "SCHEDULER_METRICS_POLLING_INTERVAL_MS";
        s2 = new EnumC9768Rud("SCHEDULER_METRICS_POLLING_INTERVAL_MS", 124, N14);
        AI3 I48 = QR1.I(false);
        I48.t = "DELAY_NGS_NAV_BAR_BADGE_NON_CRITICAL";
        t2 = new EnumC9768Rud("DELAY_NGS_NAV_BAR_BADGE_NON_CRITICAL", 125, I48);
        u2 = new EnumC9768Rud("LAST_UPDATE_TIME", 126, QR1.N(-1L));
        v2 = new EnumC9768Rud("LAST_UPDATE_VERSION", 127, QR1.R(""));
        AI3 I49 = QR1.I(false);
        I49.t = "STARTUP_ENABLE_BG_APP_CREATION_REPORTING";
        w2 = new EnumC9768Rud("STARTUP_ENABLE_BG_APP_CREATION_REPORTING", 128, I49);
        AI3 I50 = QR1.I(false);
        I50.t = "CPU_FREQUENCY_METRICS_COLLECTOR_PAGE_ENABLED";
        x2 = new EnumC9768Rud("CPU_FREQUENCY_METRICS_COLLECTOR_PAGE_ENABLED", 129, I50);
        AI3 I51 = QR1.I(false);
        I51.t = "CHECK_TOS_ON_APP_START";
        y2 = new EnumC9768Rud("CHECK_TOS_ON_APP_START", 130, I51);
        AI3 I52 = QR1.I(false);
        I52.t = "STARTUP_ENABLE_STARTUP_MISCLASSIFICATION_REPORTING";
        z2 = new EnumC9768Rud("STARTUP_ENABLE_STARTUP_MISCLASSIFICATION_REPORTING", 131, I52);
        AI3 I53 = QR1.I(false);
        I53.t = "STATE_COMPLIANCE_REQUIRED";
        A2 = new EnumC9768Rud("STATE_COMPLIANCE_REQUIRED", 132, I53);
        AI3 I54 = QR1.I(false);
        I54.t = "AVOID_XML_INFLATION_FOR_SPLASH_FRAGMENT";
        B2 = new EnumC9768Rud("AVOID_XML_INFLATION_FOR_SPLASH_FRAGMENT", 133, I54);
        AI3 I55 = QR1.I(false);
        I55.t = "NAVIGATION_USE_NAVIGATION_REQUEST";
        C2 = new EnumC9768Rud("NAVIGATION_USE_NAVIGATION_REQUEST", 134, I55);
        AI3 I56 = QR1.I(false);
        I56.t = "SIG_ANDROID_DEEP_LINK_DYNAMIC_RESOLUTION_PRIORITY_ENABLED";
        D2 = new EnumC9768Rud("SIG_ANDROID_DEEP_LINK_DYNAMIC_RESOLUTION_PRIORITY_ENABLED", 135, I56);
        AI3 I57 = QR1.I(false);
        I57.t = "STARTUP_GET_PAGE_FROM_INTENT_USE_DESCRIPTOR";
        E2 = new EnumC9768Rud("STARTUP_GET_PAGE_FROM_INTENT_USE_DESCRIPTOR", 136, I57);
        AI3 I58 = QR1.I(false);
        I58.t = "STARTUP_INTENT_PAGE_TYPE_USE_DESCRIPTOR";
        F2 = new EnumC9768Rud("STARTUP_INTENT_PAGE_TYPE_USE_DESCRIPTOR", 137, I58);
        AI3 I59 = QR1.I(false);
        I59.t = "STARTUP_PRELOADER_MAPPING_UNLOCK_TO_CAMERA";
        G2 = new EnumC9768Rud("STARTUP_PRELOADER_MAPPING_UNLOCK_TO_CAMERA", 138, I59);
        AI3 N15 = QR1.N(0L);
        N15.t = "STARTUP_AVOID_CAMERA_BY_PAGE_TYPE";
        H2 = new EnumC9768Rud("STARTUP_AVOID_CAMERA_BY_PAGE_TYPE", 139, N15);
        AI3 I60 = QR1.I(false);
        I60.t = "STARTUP_AVOID_INCEPTION_FOR_NON_CAMERA_STARTUP";
        I2 = new EnumC9768Rud("STARTUP_AVOID_INCEPTION_FOR_NON_CAMERA_STARTUP", Tweaks.SPONSORED_SNAPS_FEED_INSERT_MODE, I60);
        AI3 I61 = QR1.I(false);
        I61.t = "STARTUP_AVOID_CAMERA_WORK_ON_NON_CAMERA_RESUME";
        J2 = new EnumC9768Rud("STARTUP_AVOID_CAMERA_WORK_ON_NON_CAMERA_RESUME", Tweaks.SPONSORED_SNAPS_USER_INPUT_MODE, I61);
        AI3 I62 = QR1.I(false);
        I62.t = "STARTUP_ALLOW_EARLY_CRITICAL_AO_FOR_NON_CAMERA";
        K2 = new EnumC9768Rud("STARTUP_ALLOW_EARLY_CRITICAL_AO_FOR_NON_CAMERA", Tweaks.CALLBACK_FETCH_ON_FEED_DELEGATE, I62);
        AI3 I63 = QR1.I(false);
        I63.t = "PROPAGATE_PAGE_LOAD_END";
        L2 = new EnumC9768Rud("PROPAGATE_PAGE_LOAD_END", Tweaks.CALLBACK_QUERY_ON_FEED_DELEGATE, I63);
        AI3 I64 = QR1.I(false);
        I64.t = "SHOULD_DELAY_PROPERTY_EXECUTION";
        M2 = new EnumC9768Rud("SHOULD_DELAY_PROPERTY_EXECUTION", Tweaks.CALLBACK_SYNC_ON_FEED_DELEGATE, I64);
        AI3 I65 = QR1.I(false);
        I65.t = "CAMERA_COLLECT_UI_LAYOUT_EVENT";
        N2 = new EnumC9768Rud("CAMERA_COLLECT_UI_LAYOUT_EVENT", Tweaks.FEED_PAGINATION_V4_ENABLED, I65);
        AI3 I66 = QR1.I(false);
        I66.t = "BEGIN_RECORDING_FIX";
        O2 = new EnumC9768Rud("BEGIN_RECORDING_FIX", Tweaks.AUTO_PAGINATE_QUERY_FEED_ENABLED, I66);
        AI3 M25 = QR1.M(0);
        M25.t = "CRITICAL_OBSERVER_TUNING";
        P2 = new EnumC9768Rud("CRITICAL_OBSERVER_TUNING", Tweaks.AUTO_PAGINATE_QUERY_FEED_LITE_ENABLED, M25);
        AI3 I67 = QR1.I(false);
        I67.t = "GESTURE_LOGGING";
        Q2 = new EnumC9768Rud("GESTURE_LOGGING", Tweaks.EXTENSION_DB_WAL_KILLSWITCH, I67);
        AI3 I68 = QR1.I(false);
        I68.t = "DELAY_FM_INIT";
        R2 = new EnumC9768Rud("DELAY_FM_INIT", Tweaks.EXTENSION_FAIL_SYNC_WRITE_KILLSWITCH, I68);
        AI3 I69 = QR1.I(false);
        I69.t = "POST_NOTIFY_GESTURE_FINISHED_WHEN_NO_ANIMATION_AUTO";
        S2 = new EnumC9768Rud("POST_NOTIFY_GESTURE_FINISHED_WHEN_NO_ANIMATION_AUTO", Tweaks.LOGIN_PREFETCH_MIN_ENTRIES, I69);
        AI3 I70 = QR1.I(false);
        I70.t = "POST_NOTIFY_GESTURE_FINISHED_WHEN_NO_ANIMATION_MANUAL";
        T2 = new EnumC9768Rud("POST_NOTIFY_GESTURE_FINISHED_WHEN_NO_ANIMATION_MANUAL", Tweaks.LOGIN_PREFETCH_MAX_ENTRIES, I70);
        AI3 I71 = QR1.I(false);
        I71.t = "SURFACE_VIEW_MANAGER_ASYNC_RELEASE_SURFACE";
        U2 = new EnumC9768Rud("SURFACE_VIEW_MANAGER_ASYNC_RELEASE_SURFACE", Tweaks.LOGIN_PREFETCH_PAGE_SIZE, I71);
        AI3 M26 = QR1.M(0);
        M26.t = "ANDROID_UNIFY_TAB_HEADER_ICON_STYLE";
        V2 = new EnumC9768Rud("UNIFY_TAB_HEADER_ICON_STYLE", 153, M26);
        AI3 M27 = QR1.M(0);
        M27.t = "INIT_MEM_AND_BAT_MONITORS_IN_MAIN_ACTIVITY";
        W2 = new EnumC9768Rud("INIT_MEM_AND_BAT_MONITORS_IN_MAIN_ACTIVITY", Tweaks.ENABLE_LOGIN_PREFETCH, M27);
        AI3 I72 = QR1.I(false);
        I72.t = "BAT_MONITOR_USE_COMPUTATION_SCHEDULER";
        X2 = new EnumC9768Rud("BAT_MONITOR_USE_COMPUTATION_SCHEDULER", Tweaks.ENABLE_POST_SYNC_QUERY, I72);
        Y2 = new EnumC9768Rud[]{b, c, t, X, Y, Z, e0, f0, g0, h0, i0, j0, k0, l0, m0, n0, o0, p0, q0, r0, s0, t0, u0, v0, w0, x0, y0, z0, A0, B0, C0, D0, E0, F0, G0, H0, I0, J0, K0, L0, M0, N0, O0, P0, Q0, R0, S0, T0, U0, V0, W0, X0, Y0, Z0, a1, b1, c1, d1, e1, f1, g1, h1, i1, j1, k1, l1, m1, n1, o1, p1, q1, r1, s1, t1, u1, v1, w1, x1, y1, z1, A1, B1, C1, D1, E1, F1, G1, H1, I1, J1, K1, L1, M1, N1, O1, P1, Q1, R1, S1, T1, U1, V1, W1, X1, Y1, Z1, a2, b2, c2, d2, e2, f2, g2, h2, i2, j2, k2, l2, m2, n2, o2, p2, q2, r2, s2, t2, u2, v2, w2, x2, y2, z2, A2, B2, C2, D2, E2, F2, G2, H2, I2, J2, K2, L2, M2, N2, O2, P2, Q2, R2, S2, T2, U2, V2, W2, X2};
    }

    public EnumC9768Rud(String str, int i, AI3 ai3) {
        this.a = ai3;
    }

    public static EnumC9768Rud valueOf(String str) {
        return (EnumC9768Rud) Enum.valueOf(EnumC9768Rud.class, str);
    }

    public static EnumC9768Rud[] values() {
        return (EnumC9768Rud[]) Y2.clone();
    }

    @Override // defpackage.BI3
    public final EnumC48048zI3 e() {
        return EnumC48048zI3.a;
    }

    @Override // defpackage.BI3
    public final String getName() {
        return name();
    }

    @Override // defpackage.BI3
    public final AI3 j() {
        return this.a;
    }
}
