package defpackage;

/* renamed from: aBd, reason: case insensitive filesystem */
/* loaded from: classes8.dex */
public enum EnumC14479aBd implements InterfaceC22815gQ6 {
    PIN_BEST_FRIEND(0),
    GHOST_TRAILS(1),
    PROFILE_BADGE(2),
    EXCLUSIVE_PROFILE_BACKGROUNDS(3),
    NOTIFICATION_SOUNDS(4),
    CHAT_WALLPAPERS(5),
    STORY_BOOST(6),
    GENERATIVE_PROFILE_BACKGROUNDS(7),
    PRIORITY_STORY_REPLIES(8),
    MERLIN(9),
    STORY_REWATCH(10),
    STORY_TIMER(11),
    GENERATIVE_CHAT_WALLPAPERS(12),
    APP_THEME(13),
    MERLIN_BIO(14),
    MAP_APPEARANCE(15),
    CUSTOM_APP_ICON(16),
    POST_VIEW_EMOJI(17),
    DARK_MODE(18),
    REPLAY_AGAIN(19),
    FREE_STREAK_RESTORE(20),
    GENERATIVE_AI_CROP_TOOL(21),
    CLOSEST_FRIEND_SCORE(22),
    DEFAULT_TAB(23),
    EXTENDED_BEST_FRIENDS(24),
    CHAT_EFFECTS(25),
    MERLIN_UPGRADE(26),
    GENERATIVE_AI_MAGIC_CAPTION(28),
    CUSTOM_CHAT_COLORS(29),
    FREE_DREAMS(30),
    DREAMS_EARLY_ACCESS(31),
    DREAMS_SKIP_WAITLIST(32),
    STREAK_REMINDERS(33),
    PEEK_A_PEEK(34),
    AI_CAMERA_MODE(35),
    SNAPSCORE_MULTIPLIER(36),
    EXCLUSIVE_LENSES(37),
    TINY_SNAPS(38),
    EDIT_CHAT(39),
    CUSTOM_STICKERS(40),
    STORY_TIMESTAMPS(41),
    STORY_VIEWER_NOTIFICATIONS(42),
    THREE_TAB(43),
    PETS_IN_PRESENCE(44),
    BEST_FRIEND_POSES(45),
    GENERATIVE_AI_STORY_REPLY(46),
    CHAT_CUSTOM_EMOJI_REACTIONS(47),
    LIGHTNING_SNAPS(48),
    FRIEND_REFERRALS(49),
    PRESENCE_HINTS(50),
    CUSTOM_RINGTONE(51),
    AI_CHAT_STICKERS(52),
    MAP_FOOTSTEPS(53),
    REPLAY_OWN_SNAP(54),
    MAP_HOMES(55),
    INSTANT_STREAKS(56),
    CHAT_NEW_BITMOJI_REACTIONS(57),
    SNAP_MODES(58),
    BUDDY_PASS(59),
    BITMOJI_FASHION(60);

    public final int a;

    EnumC14479aBd(int i) {
        this.a = i;
    }

    @Override // defpackage.InterfaceC22815gQ6
    public final int a() {
        return this.a;
    }
}
