package defpackage;

import com.snapchat.client.messaging.Tweaks;

/* JADX WARN: Enum visitor error
jadx.core.utils.exceptions.JadxRuntimeException: Init of enum field 'c' uses external variables
	at jadx.core.dex.visitors.EnumVisitor.createEnumFieldByConstructor(EnumVisitor.java:451)
	at jadx.core.dex.visitors.EnumVisitor.processEnumFieldByField(EnumVisitor.java:372)
	at jadx.core.dex.visitors.EnumVisitor.processEnumFieldByWrappedInsn(EnumVisitor.java:337)
	at jadx.core.dex.visitors.EnumVisitor.extractEnumFieldsFromFilledArray(EnumVisitor.java:322)
	at jadx.core.dex.visitors.EnumVisitor.extractEnumFieldsFromInsn(EnumVisitor.java:262)
	at jadx.core.dex.visitors.EnumVisitor.convertToEnum(EnumVisitor.java:151)
	at jadx.core.dex.visitors.EnumVisitor.visit(EnumVisitor.java:100)
 */
/* JADX WARN: Failed to restore enum class, 'enum' modifier and super class removed */
/* loaded from: classes.dex */
public final class IV3 implements BI3 {
    public static final IV3 A0;
    public static final IV3 A1;
    public static final IV3 B0;
    public static final IV3 B1;
    public static final IV3 C0;
    public static final IV3 C1;
    public static final IV3 D0;
    public static final IV3 D1;
    public static final IV3 E0;
    public static final IV3 E1;
    public static final IV3 F0;
    public static final IV3 F1;
    public static final IV3 G0;
    public static final IV3 G1;
    public static final IV3 H0;
    public static final IV3 H1;
    public static final IV3 I0;
    public static final IV3 I1;
    public static final IV3 J0;
    public static final IV3 J1;
    public static final IV3 K0;
    public static final IV3 K1;
    public static final IV3 L0;
    public static final IV3 L1;
    public static final IV3 M0;
    public static final IV3 M1;
    public static final IV3 N0;
    public static final IV3 N1;
    public static final IV3 O0;
    public static final IV3 O1;
    public static final IV3 P0;
    public static final IV3 P1;
    public static final IV3 Q0;
    public static final IV3 Q1;
    public static final IV3 R0;
    public static final IV3 R1;
    public static final IV3 S0;
    public static final IV3 S1;
    public static final IV3 T0;
    public static final IV3 T1;
    public static final IV3 U0;
    public static final IV3 U1;
    public static final IV3 V0;
    public static final IV3 V1;
    public static final IV3 W0;
    public static final IV3 W1;
    public static final IV3 X;
    public static final IV3 X0;
    public static final IV3 X1;
    public static final IV3 Y;
    public static final IV3 Y0;
    public static final IV3 Y1;
    public static final IV3 Z;
    public static final IV3 Z0;
    public static final IV3 Z1;
    public static final IV3 a1;
    public static final IV3 a2;
    public static final IV3 b = new IV3("ACTIONBAR", 0, QR1.I(false));
    public static final IV3 b1;
    public static final IV3 b2;
    public static final IV3 c;
    public static final IV3 c1;
    public static final IV3 c2;
    public static final IV3 d1;
    public static final IV3 d2;
    public static final IV3 e0;
    public static final IV3 e1;
    public static final IV3 e2;
    public static final IV3 f0;
    public static final IV3 f1;
    public static final /* synthetic */ IV3[] f2;
    public static final IV3 g0;
    public static final IV3 g1;
    public static final IV3 h0;
    public static final IV3 h1;
    public static final IV3 i0;
    public static final IV3 i1;
    public static final IV3 j0;
    public static final IV3 j1;
    public static final IV3 k0;
    public static final IV3 k1;
    public static final IV3 l0;
    public static final IV3 l1;
    public static final IV3 m0;
    public static final IV3 m1;
    public static final IV3 n0;
    public static final IV3 n1;
    public static final IV3 o0;
    public static final IV3 o1;
    public static final IV3 p0;
    public static final IV3 p1;
    public static final IV3 q0;
    public static final IV3 q1;
    public static final IV3 r0;
    public static final IV3 r1;
    public static final IV3 s0;
    public static final IV3 s1;
    public static final IV3 t;
    public static final IV3 t0;
    public static final IV3 t1;
    public static final IV3 u0;
    public static final IV3 u1;
    public static final IV3 v0;
    public static final IV3 v1;
    public static final IV3 w0;
    public static final IV3 w1;
    public static final IV3 x0;
    public static final IV3 x1;
    public static final IV3 y0;
    public static final IV3 y1;
    public static final IV3 z0;
    public static final IV3 z1;
    public final AI3 a;

    static {
        AI3 N = QR1.N(0L);
        N.t = "CONTEXT_UAB_ANIMATION_DURATION";
        c = new IV3("CONTEXT_UAB_ANIMATION_DURATION", 1, N);
        AI3 I = QR1.I(false);
        I.t = "CONTEXT_UAB_QSI";
        t = new IV3("CONTEXT_ENABLE_QSI_UAB", 2, I);
        AI3 I2 = QR1.I(false);
        AI3.r(I2, "CONTEXT_SOUNDS_WAVEFORM_ANDROID", "enabled", 4);
        X = new IV3("CONTEXT_SOUNDS_WAVEFORM_ANDROID", 3, I2);
        AI3 M = QR1.M(48);
        M.t = "CONSISTENT_ACTION_BAR_HEIGHT_DP";
        Y = new IV3("CONSISTENT_ACTION_BAR_HEIGHT", 4, M);
        Z = new IV3("CARDS", 5, QR1.I(false));
        AI3 I3 = QR1.I(true);
        I3.t = "CONTEXT_FILTER_CARDS_ABOVE_KEYBOARD";
        e0 = new IV3("CONTEXT_FILTER_CARDS_ABOVE_KEYBOARD", 6, I3);
        AI3 I4 = QR1.I(false);
        AI3.r(I4, "CONTEXT_LENS_URL_ANDROID", "enabled", 4);
        f0 = new IV3("LENS_DEEPLINKING", 7, I4);
        AI3 I5 = QR1.I(false);
        I5.t = "AI_CAMERA_MODE_CONTEXT_CARD";
        g0 = new IV3("AI_CAMERA_MODE_CONTEXT_CARD", 8, I5);
        AI3 I6 = QR1.I(false);
        I6.t = "AI_MODE_DEEPLINK_ENABLED";
        h0 = new IV3("AI_CAMERA_MODE_DEEPLINK_ENABLED", 9, I6);
        AI3 I7 = QR1.I(false);
        AI3.r(I7, "CONTEXT_SEE_TAPPABLE_ELEMENTS_ANDROID", "CAPTION_TOOLTIP", 4);
        i0 = new IV3("SEE_TAPPABLE_CAPTION_TOOLTIP", 10, I7);
        AI3 N2 = QR1.N(5000L);
        AI3.r(N2, "CONTEXT_SEE_TAPPABLE_ELEMENTS_ANDROID", "IMPRESSION_TIME_MS", 4);
        j0 = new IV3("TAPPABLE_CAPTION_TOOLTIP_MIN_IMPRESSION_TIME_MS", 11, N2);
        AI3 I8 = QR1.I(false);
        I8.e0 = 411;
        k0 = new IV3("TAPPABLE_CAPTION_TOOLTIP_HAS_BEEN_IMPRESSED", 12, I8);
        l0 = new IV3("ENABLE_BITMOJI_STICKER_UNLOCK", 13, QR1.I(true));
        AI3 I9 = QR1.I(false);
        I9.t = "CONTEXT_USE_MEDIA_ASPECT_RATIO_FOR_SNAP_CONNECT_TE_ANDROID";
        m0 = new IV3("ENABLE_MEDIA_ASPECT_RATIO_FOR_SNAP_CONNECT_TE", 14, I9);
        AI3 I10 = QR1.I(false);
        AI3.r(I10, "CAMERA_ANDROID_TIMELINE_CONTEXT_CARD", "enabled_in_spotlight", 4);
        n0 = new IV3("CONTEXT_TIMELINE_IN_SPOTLIGHT_ENABLED", 15, I10);
        AI3 I11 = QR1.I(false);
        AI3.r(I11, "CAMERA_ANDROID_TIMELINE_CONTEXT_CARD", "enabled_in_stories", 4);
        o0 = new IV3("CONTEXT_TIMELINE_IN_STORIES_ENABLED", 16, I11);
        AI3 I12 = QR1.I(false);
        AI3.r(I12, "CAMERA_ANDROID_TIMELINE_CONTEXT_CARD", "enabled_in_snaps", 4);
        p0 = new IV3("CONTEXT_TIMELINE_IN_SNAPS_ENABLED", 17, I12);
        q0 = new IV3("CHAT", 18, QR1.I(false));
        AI3 I13 = QR1.I(true);
        I13.t = "CONTEXT_QUOTED_REPLY_FULL_SCREEN_MEDIA_SENDER";
        r0 = new IV3("CONTEXT_QUOTED_REPLY_FULL_SCREEN_MEDIA_SENDER", 19, I13);
        s0 = new IV3("PROFILE", 20, QR1.I(false));
        AI3 I14 = QR1.I(false);
        I14.t = "CONTEXT_PROFILE_FRIENDSHIP_FLASHBACKS_REMIX";
        t0 = new IV3("CONTEXT_PROFILE_FRIENDSHIP_FLASHBACKS_REMIX", 21, I14);
        u0 = new IV3("POST_SNAP_ACTIONS", 22, QR1.I(false));
        AI3 M2 = QR1.M(1440);
        M2.t = "CONTEXT_TEAM_SNAPCHAT_PSA_DURATION_MIN";
        v0 = new IV3("CONTEXT_TEAM_SNAPCHAT_PSA_DURATION", 23, M2);
        AI3 I15 = QR1.I(false);
        I15.t = "CONTEXT_RENDER_CHAT_PSA_ASYNC";
        w0 = new IV3("RENDER_CHAT_PSA_ASYNC", 24, I15);
        AI3 I16 = QR1.I(false);
        I16.t = "SET_IMAGE_HINT_FOR_CONTEXT_ICONS";
        x0 = new IV3("SET_IMAGE_HINT_FOR_CONTEXT_ICONS", 25, I16);
        AI3 I17 = QR1.I(true);
        I17.t = "COF_SENDER_SIDE_PSA";
        y0 = new IV3("SENDER_SIDE_PSA_ENABLED", 26, I17);
        AI3 I18 = QR1.I(true);
        I18.t = "CONTEXT_ANDROID_LENS_PSA_STORIES";
        z0 = new IV3("CONTEXT_ANDROID_LENS_PSA_STORIES", 27, I18);
        AI3 I19 = QR1.I(true);
        I19.t = "CONTEXT_ANDROID_SAVE_PSA_ON_VIEW";
        A0 = new IV3("CONTEXT_ANDROID_SAVE_PSA_ON_VIEW", 28, I19);
        B0 = new IV3("PSA_MAX_VISIBLE_ACTIONS", 29, QR1.M(1));
        C0 = new IV3("PSA_PERSIST_TIME_MIN", 30, QR1.M(60));
        D0 = new IV3("PSA_GROUP_PERSIST_TIME_MIN", 31, QR1.M(5));
        E0 = new IV3("PSA_MENTION_PERSIST_TIME_MIN", 32, QR1.M(1440));
        F0 = new IV3("CONTEXT_PSA_FEED_MULTIPLE_ITEMS_WITH_QUICK_SNAP", 33, QR1.M(15));
        G0 = new IV3("TAPPABLES", 34, QR1.I(false));
        AI3 I20 = QR1.I(false);
        AI3.r(I20, "CONTEXT_SEE_TAPPABLE_ELEMENTS_ANDROID", "APPROXIMATE_SHIMMER", 4);
        H0 = new IV3("CAPTION_APPROXIMATE_SHIMMER", 35, I20);
        AI3 I21 = QR1.I(false);
        AI3.r(I21, "CONTEXT_SEE_TAPPABLE_ELEMENTS_ANDROID", "REPLACES_PRIMARY_CONTEXT", 4);
        I0 = new IV3("TAPPABLE_ELEMENT_REPLACE_PRIMARY_CONTEXT", 36, I21);
        J0 = new IV3("TAP_AREA_OUTLINE", 37, QR1.I(false));
        K0 = new IV3("TAPPABLE_BLUR", 38, QR1.I(true));
        AI3 I22 = QR1.I(false);
        AI3.r(I22, "CONTEXT_SEE_TAPPABLE_ELEMENTS_ANDROID", "INFINITE_SHIMMER", 4);
        L0 = new IV3("INFINITE_SHIMMER", 39, I22);
        M0 = new IV3("SHIMMER_REPEAT_COUNT", 40, QR1.M(0));
        N0 = new IV3("SHIMMER_DELAY", 41, QR1.N(750L));
        O0 = new IV3("SHIMMER_REPEAT_DELAY", 42, QR1.N(500L));
        P0 = new IV3("SHIMMER_OPACITY", 43, QR1.L(0.05f));
        Q0 = new IV3("SHIMMER_DURATION", 44, QR1.N(550L));
        R0 = new IV3("ACTION_MENU", 45, QR1.I(false));
        S0 = new IV3("BITMOJI_QUICK_REPLY_SECONDARY_CONTEXT", 46, QR1.I(true));
        T0 = new IV3("TAP_AND_HOLD_ENABLED", 47, QR1.I(true));
        U0 = new IV3("ENABLE_TAP_AND_HOLD_SWIPE_UP_VIEW", 48, QR1.I(true));
        V0 = new IV3("PLATFORM", 49, QR1.I(false));
        AI3 I23 = QR1.I(false);
        I23.e0 = 387;
        W0 = new IV3("MUSIC_LINKFIRE_DISCLAIMER_ACKNOWLEDGED", 50, I23);
        AI3 I24 = QR1.I(false);
        I24.t = "MUSIC_ANDROID_SPOTLIGHT_CARD_ORDER";
        X0 = new IV3("MUSIC_ANDROID_SPOTLIGHT_CARD_ORDER", 51, I24);
        AI3 I25 = QR1.I(false);
        I25.t = "MUSIC_ANDROID_MINI_CARD_ALBUM_ART";
        Y0 = new IV3("MUSIC_ANDROID_MINI_CARD_ALBUM_ART", 52, I25);
        AI3 I26 = QR1.I(false);
        I26.e0 = 551;
        Z0 = new IV3("INTERACTIONS_POLL_VOTING_ACKNOWLEDGED", 53, I26);
        AI3 R = QR1.R("");
        AI3.r(R, "CONTEXT_BIDIRECTIONAL_STORY_PRIORITY_RULES_ANDROID", "PRIORITY_TREATMENT", 4);
        a1 = new IV3("STORY_PRIORITY_RULES", 54, R);
        AI3 M3 = QR1.M(5);
        AI3.r(M3, "CONTEXT_BIDIRECTIONAL_STORY_PRIORITY_RULES_ANDROID", "LOW_FRIEND_COUNT_THRESHOLD", 4);
        b1 = new IV3("BIDIRECTIONAL_LOW_FRIEND_COUNT_THRESHOLD", 55, M3);
        AI3 R2 = QR1.R("");
        AI3.r(R2, "CONTEXT_DIRECT_SNAP_PRIORITY_RULES_ANDROID", "PRIORITY_TREATMENT", 4);
        c1 = new IV3("DIRECT_SNAP_PRIORITY_RULES", 56, R2);
        d1 = new IV3("COMPOSER", 57, QR1.I(false));
        AI3 I27 = QR1.I(false);
        AI3.r(I27, "CONTEXT_COMPOSER_TWEAKS", "disableViewReuse", 4);
        e1 = new IV3("COMPOSER_DISABLE_VIEW_REUSE", 58, I27);
        AI3 I28 = QR1.I(false);
        AI3.r(I28, "CONTEXT_COMPOSER_TWEAKS", "keepViewAlive", 4);
        f1 = new IV3("COMPOSER_KEEP_VIEW_ALIVE_ON_DESTROY", 59, I28);
        AI3 I29 = QR1.I(false);
        AI3.r(I29, "CONTEXT_COMPOSER_TWEAKS", "delayDestroy", 4);
        g1 = new IV3("COMPOSER_DELAY_DESTROY", 60, I29);
        AI3 I30 = QR1.I(false);
        AI3.r(I30, "CONTEXT_COMPOSER_TWEAKS", "recreateImages", 4);
        h1 = new IV3("COMPOSER_RECREATE_IMAGES", 61, I30);
        AI3 I31 = QR1.I(false);
        AI3.r(I31, "CONTEXT_COMPOSER_TWEAKS", "performActionsOnMainThread", 4);
        i1 = new IV3("COMPOSER_PERFORM_ACTIONS_ON_MAIN_THREAD", 62, I31);
        AI3 I32 = QR1.I(false);
        AI3.r(I32, "CONTEXT_COMPOSER_TWEAKS", "disableBoxShadow", 4);
        j1 = new IV3("COMPOSER_DISABLE_BOX_SHADOW", 63, I32);
        AI3 I33 = QR1.I(false);
        AI3.r(I33, "CONTEXT_COMPOSER_TWEAKS", "disableSlowClipping", 4);
        k1 = new IV3("COMPOSER_DISABLE_SLOW_CLIPPING", 64, I33);
        AI3 I34 = QR1.I(false);
        AI3.r(I34, "CONTEXT_COMPOSER_TWEAKS", "checkForIsDestroyed", 4);
        l1 = new IV3("COMPOSER_CHECK_FOR_IS_DESTROYED", 65, I34);
        AI3 I35 = QR1.I(false);
        AI3.r(I35, "CONTEXT_COMPOSER_TWEAKS", "disableAnimatingAfterLoadingImage", 4);
        m1 = new IV3("COMPOSER_DISABLE_ANIMATING_AFTER_LOADING_IMAGE", 66, I35);
        n1 = new IV3("NETWORK", 67, QR1.I(false));
        SN6 sn6 = SN6.a;
        o1 = new IV3("CONTEXT_CARDS_ENDPOINT", 68, QR1.K(sn6));
        p1 = new IV3("CONTEXT_CARDS_CACHE_ENABLED", 69, QR1.I(true));
        q1 = new IV3("CONTEXT_CARDS_CUSTOM_ENDPOINT", 70, QR1.R(""));
        AI3 R3 = QR1.R("https://aws.api.snapchat.com/context/");
        R3.t = "context_standard_endpoint";
        r1 = new IV3("COF_DEFAULT_ENDPOINT", 71, R3);
        AI3 R4 = QR1.R("https://aws.api.snapchat.com/context/");
        R4.t = "context_spotlight_endpoint";
        s1 = new IV3("COF_SPOTLIGHT_ENDPOINT", 72, R4);
        AI3 I36 = QR1.I(false);
        AI3.r(I36, "CONTEXT_NEW_USER_SERVICE_ANDROID", "enabled", 4);
        t1 = new IV3("CONTEXT_MESH_BACKEND_ENABLED", 73, I36);
        u1 = new IV3("Remix", 74, QR1.I(false));
        AI3 I37 = QR1.I(false);
        AI3.r(I37, "CONTEXT_MENTION_URL_ANDROID", "enabled", 4);
        v1 = new IV3("MENTION_URL", 75, I37);
        AI3 N3 = QR1.N(57207040904L);
        AI3.r(N3, "CONTEXT_REMIX_ANDROID", "REMIX_LENS_ID", 4);
        w1 = new IV3("REMIX_LENS_ID", 76, N3);
        AI3 R5 = QR1.R("https://www.snapchat.com/unlock/?type=SNAPCODE&uuid=47b85c80a75049d5ba2a871fecde3df9&metadata=01");
        AI3.r(R5, "CONTEXT_REMIX_ANDROID", "REMIX_LENS_DEEPLINK", 4);
        x1 = new IV3("REMIX_LENS_DEEPLINK", 77, R5);
        C30801mOe c30801mOe = new C30801mOe();
        c30801mOe.a();
        c30801mOe.b();
        AI3 ai3 = new AI3(c30801mOe, C30801mOe.class);
        ai3.t = "CONTEXT_REMIX_LENS_CONFIGURATION";
        y1 = new IV3("REMIX_LENS_CONFIG", 78, ai3);
        z1 = new IV3("FORCE_ENABLE_REMIX_FRIEND_STORIES", 79, QR1.I(false));
        A1 = new IV3("POLLS", 80, QR1.I(false));
        B1 = new IV3("POLLS_BACKEND_ENDPOINT", 81, QR1.K(sn6));
        C1 = new IV3("POLLS_FORCE_NUX_DIALOG", 82, QR1.I(false));
        AI3 R6 = QR1.R(Grk.l());
        R6.t = "CONTEXT_POLLS_ANDROID_EMOJI_FAVORITES";
        D1 = new IV3("POLLS_EMOJI_FAVORITES", 83, R6);
        AI3 I38 = QR1.I(false);
        I38.t = "CONTEXT_MEMORIES_ACTION_MENU_ICONS";
        E1 = new IV3("CONTEXT_MEMORIES_ACTION_MENU_ICONS", 84, I38);
        AI3 I39 = QR1.I(false);
        I39.t = "ENABLE_SHARED_STORIES_REMIX";
        F1 = new IV3("ENABLE_SHARED_STORIES_REMIX", 85, I39);
        AI3 I40 = QR1.I(false);
        I40.t = "ENABLE_COMMUNITY_REMIX";
        G1 = new IV3("ENABLE_COMMUNITY_REMIX", 86, I40);
        AI3 I41 = QR1.I(false);
        I41.t = "REMIX_TO_GROUP_CHATS";
        H1 = new IV3("REMIX_TO_GROUP_CHATS", 87, I41);
        AI3 I42 = QR1.I(false);
        I42.e0 = 729;
        I1 = new IV3("HAS_SEEN_SHARED_STORY_REMIX_PROMPT", 88, I42);
        AI3 I43 = QR1.I(false);
        I43.t = "CONTEXT_ENABLE_CONTEXT_SSF_SUPPORT";
        J1 = new IV3("ENABLE_CONTEXT_SSF_SUPPORT", 89, I43);
        K1 = new IV3("ENABLE_CONTEXT_SSF_DEBUG_AREA_LOCALLY", 90, QR1.I(false));
        AI3 I44 = QR1.I(false);
        I44.e0 = 769;
        L1 = new IV3("CONTEXT_GROUP_CREATION_MULTI_MENTION_POPUP_SEEN_ANDROID", 91, I44);
        AI3 I45 = QR1.I(false);
        I45.t = "DISCOVER_STICKER_DEEPLINK";
        M1 = new IV3("DF_STICKER_REMIX_MMVP", 92, I45);
        AI3 I46 = QR1.I(false);
        I46.t = "DISCOVER_ADS_STICKER_DEEPLINK";
        N1 = new IV3("DF_AD_STICKER_REMIX_MMVP", 93, I46);
        AI3 I47 = QR1.I(false);
        I47.t = "CONTEXT_MINI_CARDS_IN_STORIES_ANDROID";
        O1 = new IV3("CONTEXT_MINI_CARDS_IN_STORIES", 94, I47);
        AI3 I48 = QR1.I(false);
        I48.t = "CONTEXT_MINI_CARDS_IN_DIRECT_SNAPS_ANDROID";
        P1 = new IV3("CONTEXT_MINI_CARDS_IN_DIRECT_SNAPS_ANDROID", 95, I48);
        AI3 R7 = QR1.R("14");
        R7.t = "CONTEXT_MINI_CARDS_ACTION_CASES_ANDROID";
        Q1 = new IV3("CONTEXT_MINI_CARDS_ACTION_CASES", 96, R7);
        AI3 I49 = QR1.I(false);
        I49.t = "CONTEXT_LIMIT_ANIMATION_TO_TRAY";
        R1 = new IV3("LIMIT_ANIMATION_TO_TRAY", 97, I49);
        AI3 I50 = QR1.I(false);
        I50.t = "CONTEXT_SNAPADS_HIDE_UAT_REMIX_BUTTON";
        S1 = new IV3("HIDE_UAT_ADS_REMIX_BUTTON", 98, I50);
        AI3 M4 = QR1.M(15);
        M4.t = "CONTEXT_PSA_FEED_LENS_PERSISTENCE_TIME_ANDROID";
        T1 = new IV3("CONTEXT_PSA_FEED_LENS_PERSISTENCE_TIME_MINUTES", 99, M4);
        AI3 I51 = QR1.I(false);
        I51.t = "context_opera_header_aif_fof_stories_add_poster";
        U1 = new IV3("SHOW_ADD_POSTER_BUTTON_ON_FOF", 100, I51);
        AI3 ai32 = new AI3(new C17999cp9(), C17999cp9.class);
        ai32.t = "CONTEXT_ORGANIC_SSF_CONFIG_ANDROID";
        V1 = new IV3("CONTEXT_ORGANIC_SSF_CONFIG", 101, ai32);
        AI3 M5 = QR1.M(0);
        M5.t = "VOPERA_SWIPE_LEFT_HINT_DISTANCE_ANDROID";
        W1 = new IV3("CONTEXT_VOPERA_SWIPE_LEFT_HINT_DISTANCE", 102, M5);
        AI3 I52 = QR1.I(false);
        I52.t = "CONTEXT_HOPERA_HIDE_CONTEXT_UX_ANDROID";
        X1 = new IV3("CONTEXT_HOPERA_HIDE_CONTEXT_UX", 103, I52);
        AI3 ai33 = new AI3(new byte[0], byte[].class);
        ai33.t = "CONTEXT_ATTACHED_EXPERIMENTS_ANDROID";
        Y1 = new IV3("CONTEXT_ATTACHED_EXPERIMENTS", 104, ai33);
        AI3 I53 = QR1.I(false);
        I53.t = "REPOST_CTA_REDESIGN";
        Z1 = new IV3("REPOST_CTA_REDESIGN", 105, I53);
        AI3 I54 = QR1.I(false);
        I54.t = "CONTEXT_ENABLE_TOP_LEVEL_BITMOJI_REPLY";
        a2 = new IV3("CONTEXT_ENABLE_TOP_LEVEL_BITMOJI_REPLY", 106, I54);
        AI3 I55 = QR1.I(false);
        I55.t = "CONTEXT_ENABLE_TOP_LEVEL_BITMOJI_TRAY";
        b2 = new IV3("CONTEXT_ENABLE_TOP_LEVEL_BITMOJI_TRAY", 107, I55);
        AI3 I56 = QR1.I(false);
        I56.t = "CONTEXT_MOVE_SEND_TOP_LEVEL_BITMOJI_REPLY";
        c2 = new IV3("CONTEXT_MOVE_SEND_ACTION_TOP_LEVEL_BITMOJI", 108, I56);
        AI3 I57 = QR1.I(false);
        I57.t = "MODERATION_TRANSPARENCY";
        IV3 iv3 = new IV3("MODERATION_TRANSPARENCY", Tweaks.MAX_HOURS_AFTER_STREAK_EXPIRE_TO_ENABLE_RESTORE, I57);
        d2 = iv3;
        AI3 M6 = QR1.M(3);
        M6.t = "CONTEXT_TOP_LEVEL_BITMOJI_REPLY_ICON_COUNT";
        IV3 iv32 = new IV3("CONTEXT_TOP_LEVEL_BITMOJI_REPLY_ICON_COUNT", Tweaks.ENABLE_STREAK_EDUCATION, M6);
        e2 = iv32;
        f2 = new IV3[]{b, c, t, X, Y, Z, e0, f0, g0, h0, i0, j0, k0, l0, m0, n0, o0, p0, q0, r0, s0, t0, u0, v0, w0, x0, y0, z0, A0, B0, C0, D0, E0, F0, G0, H0, I0, J0, K0, L0, M0, N0, O0, P0, Q0, R0, S0, T0, U0, V0, W0, X0, Y0, Z0, a1, b1, c1, d1, e1, f1, g1, h1, i1, j1, k1, l1, m1, n1, o1, p1, q1, r1, s1, t1, u1, v1, w1, x1, y1, z1, A1, B1, C1, D1, E1, F1, G1, H1, I1, J1, K1, L1, M1, N1, O1, P1, Q1, R1, S1, T1, U1, V1, W1, X1, Y1, Z1, a2, b2, c2, iv3, iv32};
    }

    public IV3(String str, int i, AI3 ai3) {
        this.a = ai3;
    }

    public static IV3 valueOf(String str) {
        return (IV3) Enum.valueOf(IV3.class, str);
    }

    public static IV3[] values() {
        return (IV3[]) f2.clone();
    }

    @Override // defpackage.BI3
    public final EnumC48048zI3 e() {
        return EnumC48048zI3.y1;
    }

    @Override // defpackage.BI3
    public final String getName() {
        return name();
    }

    @Override // defpackage.BI3
    public final AI3 j() {
        return this.a;
    }
}
