package defpackage;

/* loaded from: classes.dex */
public enum KZ7 {
    TEXT(2),
    CHAT_MEDIA(3),
    AUDIO_NOTE(6),
    SNAPDOC(11),
    TEXT_STORY_REPLY(7, 11),
    INCLUDED_STICKER(4, 1),
    CUSTOM_STICKER(4, 2),
    EMOJI_STICKER(4, 3),
    CREATIVE_TOOLS_ITEM(14),
    USER_SHARE(5, 7),
    STORY_SHARE(5, 5),
    SAVED_STORY_SHARE(5, 24),
    MAP_SHARE_SNAP(5, 1),
    MAP_SHARE_STORY(5, 10),
    SEARCH_SHARE_SNAP(5, 6),
    SEARCH_SHARE_STORY(5, 3),
    DISCOVER_SHARE_PUBLISHER_STORY_SNAP(5, 8),
    AD_SHARE(5, 15),
    AD_SHARE_v2(5, 26),
    MEMORIES_STORY(5, 11),
    SNAP_PRO_PROFILE_SHARE(5, 13),
    SNAP_PRO_PROFILE_SNAP_SHARE(5, 14),
    SPOTLIGHT_STORY_SHARE(5, 16),
    BITMOJI_OUTFIT_SHARE(5, 17),
    BLOOPS_STORY_SHARE(5, 22),
    LOCATION_SHARE(9, 2),
    LOCATION_REQUEST(9, 1),
    LIVE_LOCATION_SHARE(13),
    SCREENSHOT(8, 1),
    ERASED_MESSAGE(8, 5),
    GROUP_NAME_CHANGE_MESSAGE(8, 4),
    GROUP_PARTICIPANT_CHANGE_MESSAGE(8, 3),
    GROUP_CHAT_CREATED_MESSAGE(8, 6),
    SAVE_TO_CAMERA_ROLL_MESSAGE(8, 7),
    INVITE_LINK_STATUS(8, 10),
    RETENTION_POLICY_CHANGE(8, 8),
    LIVE_LOCATION_TERMINATED(8, 13);

    public static final C6980Mr7 b = new C6980Mr7(4);
    public static final C12718Xfi c = new C12718Xfi(LR5.x0);
    public final C12718Xfi a;

    KZ7(int... iArr) {
        this.a = new C12718Xfi(new C21185fC6(15, iArr));
    }
}
