package defpackage;

import com.snapchat.client.messaging.Tweaks;

/* JADX WARN: Enum visitor error
jadx.core.utils.exceptions.JadxRuntimeException: Init of enum field 'EF0' uses external variables
	at jadx.core.dex.visitors.EnumVisitor.createEnumFieldByConstructor(EnumVisitor.java:451)
	at jadx.core.dex.visitors.EnumVisitor.processEnumFieldByRegister(EnumVisitor.java:395)
	at jadx.core.dex.visitors.EnumVisitor.extractEnumFieldsFromFilledArray(EnumVisitor.java:324)
	at jadx.core.dex.visitors.EnumVisitor.extractEnumFieldsFromInsn(EnumVisitor.java:262)
	at jadx.core.dex.visitors.EnumVisitor.convertToEnum(EnumVisitor.java:151)
	at jadx.core.dex.visitors.EnumVisitor.visit(EnumVisitor.java:100)
 */
/* JADX WARN: Failed to restore enum class, 'enum' modifier and super class removed */
/* loaded from: classes.dex */
public final class QAd implements BI3 {
    public static final QAd A0;
    public static final QAd A1;
    public static final QAd A2;
    public static final QAd B0;
    public static final QAd B1;
    public static final QAd B2;
    public static final QAd C0;
    public static final QAd C1;
    public static final QAd C2;
    public static final QAd D0;
    public static final QAd D1;
    public static final QAd D2;
    public static final QAd E0;
    public static final QAd E1;
    public static final QAd E2;
    public static final QAd F0;
    public static final QAd F1;
    public static final QAd F2;
    public static final QAd G0;
    public static final QAd G1;
    public static final QAd G2;
    public static final QAd H0;
    public static final QAd H1;
    public static final QAd H2;
    public static final QAd I0;
    public static final QAd I1;
    public static final QAd I2;
    public static final QAd J0;
    public static final QAd J1;
    public static final QAd J2;
    public static final QAd K0;
    public static final QAd K1;
    public static final QAd K2;
    public static final QAd L0;
    public static final QAd L1;
    public static final QAd L2;
    public static final QAd M0;
    public static final QAd M1;
    public static final QAd M2;
    public static final QAd N0;
    public static final QAd N1;
    public static final QAd N2;
    public static final QAd O0;
    public static final QAd O1;
    public static final QAd O2;
    public static final QAd P0;
    public static final QAd P1;
    public static final QAd P2;
    public static final QAd Q0;
    public static final QAd Q1;
    public static final QAd Q2;
    public static final QAd R0;
    public static final QAd R1;
    public static final QAd R2;
    public static final QAd S0;
    public static final QAd S1;
    public static final QAd S2;
    public static final QAd T0;
    public static final QAd T1;
    public static final QAd T2;
    public static final QAd U0;
    public static final QAd U1;
    public static final QAd U2;
    public static final QAd V0;
    public static final QAd V1;
    public static final QAd V2;
    public static final QAd W0;
    public static final QAd W1;
    public static final QAd W2;
    public static final QAd X;
    public static final QAd X0;
    public static final QAd X1;
    public static final QAd X2;
    public static final QAd Y;
    public static final QAd Y0;
    public static final QAd Y1;
    public static final QAd Y2;
    public static final QAd Z;
    public static final QAd Z0;
    public static final QAd Z1;
    public static final QAd Z2;
    public static final QAd a1;
    public static final QAd a2;
    public static final QAd a3;
    public static final QAd b1;
    public static final QAd b2;
    public static final QAd b3;
    public static final QAd c;
    public static final QAd c1;
    public static final QAd c2;
    public static final QAd c3;
    public static final QAd d1;
    public static final QAd d2;
    public static final QAd d3;
    public static final QAd e0;
    public static final QAd e1;
    public static final QAd e2;
    public static final /* synthetic */ QAd[] e3;
    public static final QAd f0;
    public static final QAd f1;
    public static final QAd f2;
    public static final QAd g0;
    public static final QAd g1;
    public static final QAd g2;
    public static final QAd h0;
    public static final QAd h1;
    public static final QAd h2;
    public static final QAd i0;
    public static final QAd i1;
    public static final QAd i2;
    public static final QAd j0;
    public static final QAd j1;
    public static final QAd j2;
    public static final QAd k0;
    public static final QAd k1;
    public static final QAd k2;
    public static final QAd l0;
    public static final QAd l1;
    public static final QAd l2;
    public static final QAd m0;
    public static final QAd m1;
    public static final QAd m2;
    public static final QAd n0;
    public static final QAd n1;
    public static final QAd n2;
    public static final QAd o0;
    public static final QAd o1;
    public static final QAd o2;
    public static final QAd p0;
    public static final QAd p1;
    public static final QAd p2;
    public static final QAd q0;
    public static final QAd q1;
    public static final QAd q2;
    public static final QAd r0;
    public static final QAd r1;
    public static final QAd r2;
    public static final QAd s0;
    public static final QAd s1;
    public static final QAd s2;
    public static final QAd t;
    public static final QAd t0;
    public static final QAd t1;
    public static final QAd t2;
    public static final QAd u0;
    public static final QAd u1;
    public static final QAd u2;
    public static final QAd v0;
    public static final QAd v1;
    public static final QAd v2;
    public static final QAd w0;
    public static final QAd w1;
    public static final QAd w2;
    public static final QAd x0;
    public static final QAd x1;
    public static final QAd x2;
    public static final QAd y0;
    public static final QAd y1;
    public static final QAd y2;
    public static final QAd z0;
    public static final QAd z1;
    public static final QAd z2;
    public final AI3 a;
    public final EnumC48048zI3 b = EnumC48048zI3.b3;

    /* JADX INFO: Fake field, exist only in values array */
    QAd EF7;

    /* JADX INFO: Fake field, exist only in values array */
    QAd EF9;

    /* JADX INFO: Fake field, exist only in values array */
    QAd EF11;

    /* JADX INFO: Fake field, exist only in values array */
    QAd EF13;

    /* JADX INFO: Fake field, exist only in values array */
    QAd EF0;

    static {
        QAd qAd = new QAd("ROUTE_TAG", 0, QR1.R(""));
        c = qAd;
        QAd qAd2 = new QAd("FORCE_FAILURE_STAGE", 1, QR1.K(EnumC17151cBd.a));
        t = qAd2;
        QAd qAd3 = new QAd("OVERRIDE_TIER_GATE", 2, QR1.K(N7i.b));
        X = qAd3;
        QAd qAd4 = new QAd("OVERRIDE_SUBSCRIPTION_PROVIDER", 3, QR1.K(EnumC42482v7i.a));
        Y = qAd4;
        QAd qAd5 = new QAd("OVERRIDE_CURRENT_PLAN_REF_ID_MOCK", 4, QR1.K(EnumC17861cj4.NONE));
        QAd qAd6 = new QAd("ALWAYS_SHOW_UPSELLS", 5, QR1.I(false));
        QAd qAd7 = new QAd("OVERRIDE_SUBSCRIPTION_STATUS", 6, QR1.K(O7i.a));
        QAd qAd8 = new QAd("OVERRIDE_SUBSCRIPTION_TIER", 7, QR1.K(V7i.a));
        QAd qAd9 = new QAd("ALWAYS_SHOW_SS_NUX", 8, QR1.I(false));
        Z = qAd9;
        QAd qAd10 = new QAd("SUBSCRIPTION_STORE", 9, QR1.K(P7i.a));
        e0 = qAd10;
        QAd qAd11 = new QAd("PLUS_APP_START_CONFIG", 10, AbstractC39113sc5.y(858, ""));
        f0 = qAd11;
        QAd qAd12 = new QAd("PLUS_SHAKE_TO_REPORT_ENABLED", 11, AbstractC39113sc5.v("PLUS_SHAKE_TO_REPORT_ENABLED", true));
        g0 = qAd12;
        QAd qAd13 = new QAd("BADGING_MANAGEMENT_PAGE_LAST_VIEW_TIMESTAMP", 12, AbstractC39113sc5.x(689, 0L));
        h0 = qAd13;
        QAd qAd14 = new QAd("GATE_SEARCH_ENABLED", 13, AbstractC39113sc5.v("PLUS_SEARCH_ENABLED", true));
        i0 = qAd14;
        QAd qAd15 = new QAd("PLUS_NEW_TO_SNAPCHAT_PLUS", 14, AbstractC39113sc5.v("PLUS_NEW_TO_SNAPCHAT_PLUS", false));
        j0 = qAd15;
        QAd qAd16 = new QAd("PLUS_NEW_TO_SNAPCHAT_PLUS_TIMESTAMP", 15, AbstractC39113sc5.o(1687485779695L, "PLUS_NEW_TO_SNAPCHAT_TIMESTAMP"));
        k0 = qAd16;
        QAd qAd17 = new QAd("PLUS_SUBSCRIPTION_SYNCER_ENABLED", 16, AbstractC39113sc5.v("PLUS_SUBSCRIPTION_SYNCER_ENABLED", true));
        l0 = qAd17;
        QAd qAd18 = new QAd("PLUS_SUBSCRIPTION_REQUIRES_EMAIL", 17, AbstractC39113sc5.v("PLUS_PURCHASE_REQUIRE_EMAIL", false));
        m0 = qAd18;
        QAd qAd19 = new QAd("PLUS_FEATURE_LOGGER_KILLSWITCH", 18, AbstractC39113sc5.v("PLUS_FEATURE_LOGGER_KILLSWITCH", false));
        n0 = qAd19;
        QAd qAd20 = new QAd("PLUS_SYNC_CONFIG", 19, QR1.R(""));
        o0 = qAd20;
        QAd qAd21 = new QAd("PLUS_SYNC_DYNAMIC_PROFILE_CAMPAIGNS_ENABLED", 20, AbstractC39113sc5.v("PLUS_DYNAMIC_PROFILE_CAMPAIGNS_ENABLED", false));
        p0 = qAd21;
        QAd qAd22 = new QAd("PLUS_SYNC_FRIEND_PROFILE_CAMPAIGNS_ENABLED", 21, AbstractC39113sc5.v("PLUS_FRIEND_PROFILE_CAMPAIGNS_ENABLED", false));
        q0 = qAd22;
        QAd qAd23 = new QAd("APP_APPEARANCE_ENTRY_POINT_ENABLED", 22, AbstractC39113sc5.v("PLUS_APP_APPEARANCE_SETTINGS_UPSELL_ENABLED", true));
        r0 = qAd23;
        QAd qAd24 = new QAd("MY_PROFILE_UPSELL_CARD_IMPRESSION_COUNT", 23, AbstractC39113sc5.x(707, 0L));
        s0 = qAd24;
        QAd qAd25 = new QAd("MY_PROFILE_UPSELL_CARD_IMPRESSION_MAX_CAP", 24, AbstractC39113sc5.o(0L, "PLUS_MY_PROFILE_UPSELL_IMPRESSION_MAX_CAP"));
        t0 = qAd25;
        QAd qAd26 = new QAd("MY_PROFILE_UPSELL_CARD_IMPRESSION_TIME_MS", 25, AbstractC39113sc5.x(683, 0L));
        u0 = qAd26;
        QAd qAd27 = new QAd("MY_PROFILE_UPSELL_CONFIG", 26, AbstractC39113sc5.s(C32593njj.class, new C32593njj(), "PLUS_UPSELL_MY_PROFILE_CONFIG"));
        v0 = qAd27;
        QAd qAd28 = new QAd("MY_PROFILE_UPSELL_REDUCE_UI_COMPLEXITY", 27, AbstractC39113sc5.v("PLUS_MY_PROFILE_UPSELL_CARD_REDUCED_UI_COMPLEXITY", false));
        w0 = qAd28;
        QAd qAd29 = new QAd("MY_PROFILE_UPSELL_STATE", 28, AbstractC39113sc5.y(851, ""));
        x0 = qAd29;
        QAd qAd30 = new QAd("FRIEND_PROFILE_SUBSCRIBED_UPSELL_CONFIG", 29, AbstractC39113sc5.s(C32593njj.class, new C32593njj(), "PLUS_UPSELL_FRIEND_PROFILE_SUBSCRIBED_CONFIG"));
        y0 = qAd30;
        QAd qAd31 = new QAd("FRIEND_PROFILE_SUBSCRIBED_UPSELL_STATE", 30, QR1.R(""));
        z0 = qAd31;
        QAd qAd32 = new QAd("FRIEND_PROFILE_UPSELL_CONFIG", 31, AbstractC39113sc5.s(C32593njj.class, new C32593njj(), "PLUS_UPSELL_FRIEND_PROFILE_CONFIG"));
        A0 = qAd32;
        QAd qAd33 = new QAd("FRIEND_PROFILE_UPSELL_STATE", 32, QR1.R(""));
        B0 = qAd33;
        DI3 di3 = DI3.b;
        AI3 ai3 = new AI3(di3, (Object) (-1));
        ai3.e0 = 672;
        QAd qAd34 = new QAd("PLUS_TAKEOVER_IMPRESSION_COUNT", 33, ai3);
        QAd qAd35 = new QAd("PLUS_TAKEOVER_TIMESTAMP_SEC", 34, AbstractC39113sc5.x(673, -1L));
        QAd qAd36 = new QAd("STORY_MANAGEMENT_UPSELL_CONFIG", 35, AbstractC39113sc5.s(C32593njj.class, new C32593njj(), "PLUS_UPSELL_STORY_MANAGEMENT_CONFIG"));
        C0 = qAd36;
        QAd qAd37 = new QAd("STORY_MANAGEMENT_UPSELL_STATE", 36, AbstractC39113sc5.y(783, ""));
        D0 = qAd37;
        QAd qAd38 = new QAd("AI_CAMERA_MODE_GATE", 37, AbstractC39113sc5.v("GENERATIVE_AI_TEXT_TO_IMAGE_KILLSWITCH", false));
        E0 = qAd38;
        QAd qAd39 = new QAd("GENERATIVE_AI_SNAP_IN_CHAT_ENABLED", 38, AbstractC39113sc5.v("GENERATIVE_AI_SNAP_IN_CHAT_ENABLED", false));
        F0 = qAd39;
        QAd qAd40 = new QAd("APP_ICON_IMPRESSION_TIME_MS", 39, AbstractC39113sc5.x(686, 0L));
        G0 = qAd40;
        QAd qAd41 = new QAd("APP_ICON_COUNTDOWN_TIMESTAMP_MS", 40, AbstractC39113sc5.o(0L, "PLUS_APP_ICON_COUNTDOWN_TIMESTAMP_MS"));
        H0 = qAd41;
        QAd qAd42 = new QAd("APP_ICON_MAX_TIMESTAMP_MS", 41, AbstractC39113sc5.o(0L, "PLUS_APP_ICON_MAX_ADDED_TIMESTAMP_MS"));
        I0 = qAd42;
        QAd qAd43 = new QAd("APP_ICON_SELECTION", 42, AbstractC39113sc5.y(651, ""));
        J0 = qAd43;
        QAd qAd44 = new QAd("APP_THEME_BADGE", 43, AbstractC39113sc5.o(1675201863889L, "PLUS_FEATURE_BADGING_CUSTOM_APP_THEME"));
        K0 = qAd44;
        QAd qAd45 = new QAd("APP_THEME_CAPTURE_COLOR_SELECTION", 44, AbstractC39113sc5.y(713, ""));
        L0 = qAd45;
        QAd qAd46 = new QAd("APP_THEME_NAVIGATION_BAR_EDITING_ENABLED", 45, AbstractC39113sc5.v("PLUS_NAVIGATION_BAR_EDITING_ENABLED", true));
        M0 = qAd46;
        QAd qAd47 = new QAd("APP_THEME_SELECTION", 46, AbstractC39113sc5.y(731, ""));
        N0 = qAd47;
        QAd qAd48 = new QAd("APP_THEME_UPSELL_STATE", 47, AbstractC39113sc5.y(829, ""));
        O0 = qAd48;
        QAd qAd49 = new QAd("APP_THEME_UPSELL_CONFIG", 48, AbstractC39113sc5.s(C32593njj.class, new C32593njj(), "PLUS_UPSELL_APP_THEME_CONFIG"));
        P0 = qAd49;
        QAd qAd50 = new QAd("BEST_FRIEND_POSES_GATE", 49, AbstractC39113sc5.v("PLUS_FEATURE_GATING_BEST_FRIEND_POSES", false));
        Q0 = qAd50;
        QAd qAd51 = new QAd("BITMOJI_FASHION_BADGE", 50, AbstractC39113sc5.o(0L, "PLUS_FEATURE_BADGING_BITMOJI_FASHION"));
        R0 = qAd51;
        QAd qAd52 = new QAd("BITMOJI_FASHION_GATE", 51, AbstractC39113sc5.v("BITMOJI_PLUS_FASHION_ENABLED", false));
        S0 = qAd52;
        QAd qAd53 = new QAd("BRANDED_ENTRY_POINT_UNPIN_MY_AI_ENABLED", 52, AbstractC39113sc5.v("PLUS_BRANDED_ENTRY_POINT_UNPIN_MY_AI_ENABLED", false));
        T0 = qAd53;
        QAd qAd54 = new QAd("BRANDED_ENTRY_POINT_PIN_BFF_ENABLED", 53, AbstractC39113sc5.v("PLUS_BRANDED_ENTRY_POINT_PIN_BFF_ENABLED", false));
        U0 = qAd54;
        QAd qAd55 = new QAd("BRANDED_ENTRY_POINT_VIEWABLE_AGAIN_SNAP_ENABLED", 54, AbstractC39113sc5.v("PLUS_BRANDED_ENTRY_POINT_VIEWABLE_AGAIN_SNAP_ENABLED", false));
        V0 = qAd55;
        QAd qAd56 = new QAd("BUDDY_PASS_GATE", 55, AbstractC39113sc5.v("PLUS_FEATURE_GATING_BUDDY_PASS", false));
        W0 = qAd56;
        QAd qAd57 = new QAd("BUDDY_PASS_BADGE", 56, AbstractC39113sc5.o(0L, "PLUS_FEATURE_BADGING_BUDDY_PASS"));
        X0 = qAd57;
        QAd qAd58 = new QAd("BUDDY_PASS_UNREDEEMED_TIMESTAMP", 57, AbstractC39113sc5.x(1154, 0L));
        Y0 = qAd58;
        QAd qAd59 = new QAd("CHAT_WALLPAPER_BADGE", 58, AbstractC39113sc5.o(1675201863889L, "PLUS_FEATURE_BADGING_CHAT_WALLPAPERS"));
        Z0 = qAd59;
        QAd qAd60 = new QAd("CHAT_WALLPAPER_IN_MEMORIES", 59, AbstractC39113sc5.v("PLUS_MEMORIES_CHAT_WALLPAPER_ENABLED", false));
        a1 = qAd60;
        QAd qAd61 = new QAd("CUSTOM_CHAT_COLORS_VIEWING", 60, AbstractC39113sc5.s(C16548bk4.class, new C16548bk4(), "CUSTOM_CHAT_COLOR"));
        b1 = qAd61;
        QAd qAd62 = new QAd("CUSTOM_STICKERS_GATE", 61, AbstractC39113sc5.v("PLUS_FEATURE_GATING_CUSTOM_STICKERS", false));
        c1 = qAd62;
        QAd qAd63 = new QAd("DREAMS_EARLY_ACCESS_GATE", 62, AbstractC39113sc5.v("DREAMS_PLUS_EARLY_ACCESS", false));
        d1 = qAd63;
        QAd qAd64 = new QAd("DREAMS_FREE_GATE", 63, AbstractC39113sc5.v("DREAMS_IN_SNAPCHAT_PLUS", false));
        e1 = qAd64;
        QAd qAd65 = new QAd("DREAMS_MAIN_GATE", 64, AbstractC39113sc5.v("dreams_memories_tab_enabled", false));
        f1 = qAd65;
        QAd qAd66 = new QAd("DREAMS_SKIP_WAITLIST_GATE", 65, AbstractC39113sc5.v("dreams_waitlist_enabled", false));
        g1 = qAd66;
        QAd qAd67 = new QAd("EXTENDED_BEST_FRIENDS_DISABLE_TOGGLE", 66, AbstractC39113sc5.z(967, false));
        h1 = qAd67;
        QAd qAd68 = new QAd("EXTENDED_BEST_FRIENDS_GATE", 67, AbstractC39113sc5.v("PLUS_EXTENDED_BEST_FRIENDS", true));
        i1 = qAd68;
        QAd qAd69 = new QAd("FAMILY_PLAN_ADDED_SEEN_TIMESTAMP", 68, AbstractC39113sc5.x(957, 0L));
        j1 = qAd69;
        QAd qAd70 = new QAd("FAMILY_PLAN_RECEIVER_GATE", 69, AbstractC39113sc5.v("PLUS_FEATURE_FAMILY_PLAN_RECEIVER_GATE", true));
        k1 = qAd70;
        QAd qAd71 = new QAd("FRIEND_REFERRALS_BADGE", 70, AbstractC39113sc5.o(0L, "PLUS_FEATURE_BADGING_FRIEND_REFERRALS"));
        l1 = qAd71;
        QAd qAd72 = new QAd("FRIEND_REFERRALS_GATE", 71, AbstractC39113sc5.v("PLUS_FEATURE_GATING_FRIEND_REFERRALS", false));
        m1 = qAd72;
        QAd qAd73 = new QAd("FRIEND_SNAPSCORE_CHANGE_DISABLE_TOGGLE", 72, AbstractC39113sc5.z(966, false));
        n1 = qAd73;
        QAd qAd74 = new QAd("FRIEND_SOLAR_SYSTEM_DISABLE_TOGGLE", 73, AbstractC39113sc5.z(965, true));
        o1 = qAd74;
        QAd qAd75 = new QAd("GENERATIVE_AI_MAGIC_CAPTION_GATE", 74, AbstractC39113sc5.v("GENERATIVE_AI_MAGIC_CAPTION_KILLSWITCH", false));
        p1 = qAd75;
        QAd qAd76 = new QAd("GENERATIVE_AI_STICKERS_GATE", 75, AbstractC39113sc5.v("PLUS_FEATURE_GATING_GEN_AI_STICKERS", false));
        q1 = qAd76;
        QAd qAd77 = new QAd("GENERATIVE_AI_STICKERS_P_AND_L", 76, AbstractC39113sc5.z(1024, false));
        r1 = qAd77;
        QAd qAd78 = new QAd("GENERATIVE_AI_STORY_REPLY_GATE", 77, AbstractC39113sc5.v("GENERATIVE_AI_STORY_REPLY_KILLSWITCH", false));
        s1 = qAd78;
        QAd qAd79 = new QAd("GIFTING_BADGE", 78, AbstractC39113sc5.o(1671470754525L, "PLUS_FEATURE_BADGING_GIFTING"));
        t1 = qAd79;
        QAd qAd80 = new QAd("GIFTING_CHAT_BIRTHDAY_UPSELL_ENABLED", 79, AbstractC39113sc5.v("PLUS_CHAT_BIRTHDAY_UPSELL_ENABLED", true));
        u1 = qAd80;
        QAd qAd81 = new QAd("GIFTING_CHAT_BIRTHDAY_UPSELL_THRESHOLD", 80, AbstractC39113sc5.f(7, "PLUS_CHAT_BIRTHDAY_UPSELL_THRESHOLD"));
        v1 = qAd81;
        QAd qAd82 = new QAd("GIFTING_OPTIMIZATION_ENABLED", 81, AbstractC39113sc5.v("PLUS_GIFTING_OPTIMIZATION_ENABLED", false));
        w1 = qAd82;
        QAd qAd83 = new QAd("GIFTING_PURCHASE_ENABLED", 82, AbstractC39113sc5.v("PLUS_FEATURE_GIFT_PURCHASE_ENABLED_ANDROID", false));
        x1 = qAd83;
        QAd qAd84 = new QAd("GIFTING_UNREDEEMED_TIMESTAMP", 83, AbstractC39113sc5.x(738, 0L));
        y1 = qAd84;
        QAd qAd85 = new QAd("GIFTING_UNREDEEMED_IMPRESSION_TIMESTAMP", 84, QR1.N(0L));
        z1 = qAd85;
        QAd qAd86 = new QAd("GIFTING_CACHE", 85, QR1.R(""));
        A1 = qAd86;
        QAd qAd87 = new QAd("HOME_TAB_GATE", 86, AbstractC39113sc5.v("PLUS_FEATURE_GATING_DEFAULT_TAB", true));
        B1 = qAd87;
        QAd qAd88 = new QAd("HOME_TAB_TRAY_ENABLED", 87, AbstractC39113sc5.v("ENABLE_HOME_TAB_TRAY", true));
        C1 = qAd88;
        QAd qAd89 = new QAd("INSTANT_STREAKS_BADGE", 88, AbstractC39113sc5.o(0L, "PLUS_FEATURE_BADGING_INSTANT_STREAKS"));
        D1 = qAd89;
        QAd qAd90 = new QAd("INSTANT_STREAKS_ENABLED", 89, AbstractC39113sc5.z(1102, false));
        E1 = qAd90;
        QAd qAd91 = new QAd("INSTANT_STREAKS_GATE", 90, AbstractC39113sc5.v("PLUS_FEATURE_GATING_INSTANT_STREAKS", false));
        F1 = qAd91;
        QAd qAd92 = new QAd("LENS_CREATIVE_GATE", 91, AbstractC39113sc5.v("PLUS_FEATURE_GATING_LENS_CREATIVE", false));
        G1 = qAd92;
        QAd qAd93 = new QAd("LIGHTNING_SNAPS_BADGE", 92, AbstractC39113sc5.o(0L, "PLUS_FEATURE_BADGING_LIGHTNING_SNAPS"));
        H1 = qAd93;
        QAd qAd94 = new QAd("LIGHTNING_SNAPS_DISABLE_TOGGLE", 93, AbstractC39113sc5.z(985, false));
        I1 = qAd94;
        QAd qAd95 = new QAd("MAP_APPEARANCE_BADGE", 94, AbstractC39113sc5.o(1692134134711L, "PLUS_FEATURE_BADGING_MAP_APPEARANCE"));
        J1 = qAd95;
        QAd qAd96 = new QAd("MAP_FOOTSTEPS_BADGE", 95, AbstractC39113sc5.o(0L, "PLUS_FEATURE_BADGING_MAP_FOOTSTEPS"));
        K1 = qAd96;
        QAd qAd97 = new QAd("MAP_FOOTSTEPS_GATE", 96, AbstractC39113sc5.v("PLUS_FEATURE_GATING_MAP_FOOTSTEPS", false));
        L1 = qAd97;
        QAd qAd98 = new QAd("MAP_HOMES_GATE", 97, AbstractC39113sc5.v("PLUS_FEATURE_GATING_MAP_HOMES", false));
        M1 = qAd98;
        QAd qAd99 = new QAd("MERLIN_BIO_GATE", 98, AbstractC39113sc5.v("PLUS_FEATURE_GATING_MERLIN_BIO", true));
        N1 = qAd99;
        QAd qAd100 = new QAd("MERLIN_BIO_SELECTION", 99, AbstractC39113sc5.y(758, ""));
        O1 = qAd100;
        QAd qAd101 = new QAd("MERLIN_BIO_ENABLED_FOR_NON_SUBS", 100, AbstractC39113sc5.v("MERLIN_BIO_ENABLED_FOR_NON_SUBS", false));
        P1 = qAd101;
        QAd qAd102 = new QAd("MERLIN_GATE", 101, AbstractC39113sc5.v("PLUS_FEATURE_GATING_MERLIN", true));
        Q1 = qAd102;
        QAd qAd103 = new QAd("MERLIN_GOOGLE_ADS_CONFIG", 102, AbstractC39113sc5.s(C23531gx8.class, new C23531gx8(), "MERLIN_GOOGLE_SDK_ADS_CONFIG"));
        R1 = qAd103;
        QAd qAd104 = new QAd("MUTUALLY_PINNED_BFF_EMOJI", 103, AbstractC39113sc5.y(1010, "❤️\u200d🔥"));
        S1 = qAd104;
        QAd qAd105 = new QAd("MUTUALLY_PINNED_BFF_GATE", 104, AbstractC39113sc5.v("PLUS_FEATURE_GATING_MUTUALLY_PINNED_BFF", true));
        T1 = qAd105;
        QAd qAd106 = new QAd("MUTUALLY_PINNED_BFF_PUBLIC", 105, AbstractC39113sc5.z(1011, false));
        U1 = qAd106;
        QAd qAd107 = new QAd("MERLIN_NON_SUBSCRIBERS", 106, AbstractC39113sc5.v("MERLIN_PUBLIC_INIT_ENABLED", false));
        V1 = qAd107;
        QAd qAd108 = new QAd("PEEK_A_PEEK_BADGE", 107, AbstractC39113sc5.o(0L, "PLUS_FEATURE_BADGING_PEEK_A_PEEK"));
        W1 = qAd108;
        QAd qAd109 = new QAd("PEEK_A_PEEK_DISABLE_TOGGLE", 108, AbstractC39113sc5.z(909, false));
        X1 = qAd109;
        QAd qAd110 = new QAd("PETS_IN_PRESENCE_CHAT_UPSELL_ENABLED", Tweaks.MAX_HOURS_AFTER_STREAK_EXPIRE_TO_ENABLE_RESTORE, AbstractC39113sc5.v("PLUS_PETS_IN_PRESENCE_CHAT_UPSELL_ENABLED", true));
        Y1 = qAd110;
        AI3 ai32 = new AI3(di3, (Object) 0);
        ai32.e0 = 652;
        QAd qAd111 = new QAd("PLUS_BADGE_VISIBILITY_TOGGLE", Tweaks.ENABLE_STREAK_EDUCATION, ai32);
        Z1 = qAd111;
        QAd qAd112 = new QAd("POST_SEND_EMOJI_ENABLED", 111, AbstractC39113sc5.v("ENABLE_SENDER_POST_VIEW_EMOJI", false));
        a2 = qAd112;
        QAd qAd113 = new QAd("POST_VIEW_EMOJI_SELECTION", 112, AbstractC39113sc5.y(692, ""));
        b2 = qAd113;
        QAd qAd114 = new QAd("PRESENCE_HINTS_BADGE", Tweaks.DELTA_SYNC_SQLITE_SHARED_STORAGE_CACHE_SIZE, AbstractC39113sc5.o(0L, "PLUS_FEATURE_BADGING_PRESENCE_HINTS"));
        c2 = qAd114;
        QAd qAd115 = new QAd("PRESENCE_HINTS_USER_ENABLED", Tweaks.FAIL_DECRYPT_FOR_DUPLEX_SNAPS_TEST_ONLY, AbstractC39113sc5.z(1031, false));
        d2 = qAd115;
        QAd qAd116 = new QAd("SENT_REPLAY_GATE", 115, AbstractC39113sc5.v("PLUS_FEATURE_GATING_REPLAY_OWN_SNAP", false));
        e2 = qAd116;
        QAd qAd117 = new QAd("REWATCH_DISABLE_TOGGLE", 116, AbstractC39113sc5.z(662, false));
        f2 = qAd117;
        QAd qAd118 = new QAd("SNAPSCORE_MULTIPLIER_ENABLED_TOGGLE", 117, AbstractC39113sc5.z(938, false));
        g2 = qAd118;
        QAd qAd119 = new QAd("SETTINGS_MANAGEMENT_CARD_LAYOUT", 118, AbstractC39113sc5.f(0, "PLUS_SETTINGS_MANAGEMENT_CARD_LAYOUT"));
        h2 = qAd119;
        QAd qAd120 = new QAd("SETTINGS_UPSELL_CONFIG", 119, AbstractC39113sc5.s(C32593njj.class, new C32593njj(), "PLUS_UPSELL_SETTINGS_CONFIG"));
        i2 = qAd120;
        QAd qAd121 = new QAd("SETTINGS_UPSELL_STATE", 120, AbstractC39113sc5.y(1056, ""));
        j2 = qAd121;
        QAd qAd122 = new QAd("SETTINGS_UPSELL_CARD_LAYOUT", 121, AbstractC39113sc5.f(0, "PLUS_SETTINGS_UPSELL_CARD_LAYOUT"));
        k2 = qAd122;
        QAd qAd123 = new QAd("SNAP_MODES_BADGE", 122, AbstractC39113sc5.o(0L, "PLUS_FEATURE_BADGING_SNAP_MODES"));
        l2 = qAd123;
        QAd qAd124 = new QAd("SNAP_MODES_ONE_TIME_SNAP_GATE", 123, AbstractC39113sc5.v("PLUS_FEATURE_GATING_SNAP_MODE_ONE_TIME_ONLY", false));
        m2 = qAd124;
        QAd qAd125 = new QAd("SNAP_MODES_SELF_DESTRUCT_SNAP_GATE", 124, AbstractC39113sc5.v("PLUS_FEATURE_GATING_SNAP_MODE_SELF_DESTRUCT", false));
        n2 = qAd125;
        QAd qAd126 = new QAd("SNAP_MODES_UPSELL_ACTION_MENU_ENABLED", 125, AbstractC39113sc5.v("PLUS_UPSELL_SNAPS_MODES_ACTION_MENU_ENABLED", false));
        o2 = qAd126;
        QAd qAd127 = new QAd("SNAP_MODES_UPSELL_TOOLBAR_ENABLED", 126, AbstractC39113sc5.v("PLUS_UPSELL_SNAPS_MODES_TOOLBAR_ENABLED", false));
        p2 = qAd127;
        QAd qAd128 = new QAd("STORY_BOOST_END_TIMESTAMP", 127, AbstractC39113sc5.x(740, 0L));
        q2 = qAd128;
        QAd qAd129 = new QAd("STORY_BOOST_START_TIMESTAMP", 128, AbstractC39113sc5.x(739, 0L));
        r2 = qAd129;
        QAd qAd130 = new QAd("STORY_REPLIES_IMPRESSION_TIME_MS", 129, AbstractC39113sc5.x(689, 0L));
        QAd qAd131 = new QAd("STORY_REPLIES_UPSELL_CONFIG", 130, AbstractC39113sc5.s(C32593njj.class, new C32593njj(), "PLUS_UPSELL_STORY_REPLIES_CONFIG"));
        s2 = qAd131;
        QAd qAd132 = new QAd("STORY_REPLIES_UPSELL_STATE", 131, AbstractC39113sc5.y(784, ""));
        t2 = qAd132;
        QAd qAd133 = new QAd("STORY_TIMER_CUSTOM_STORIES_GATE", 132, AbstractC39113sc5.v("PLUS_FEATURE_GATING_STORY_TIMER_CUSTOM_STORIES", true));
        u2 = qAd133;
        QAd qAd134 = new QAd("STORY_TIMER_GATE", 133, AbstractC39113sc5.v("PLUS_FEATURE_GATING_STORY_TIMER", true));
        v2 = qAd134;
        QAd qAd135 = new QAd("STORY_VIEW_NOTIFICATION_SETTINGS", 134, AbstractC39113sc5.y(969, ""));
        w2 = qAd135;
        QAd qAd136 = new QAd("STORY_VIEW_TIMESTAMP_DISABLED", 135, AbstractC39113sc5.z(970, false));
        x2 = qAd136;
        QAd qAd137 = new QAd("STREAK_RESTORE_IN_FRIEND_PROFILE", 136, AbstractC39113sc5.v("PLUS_STREAK_RESTORE_IN_FRIEND_PROFILE", true));
        y2 = qAd137;
        QAd qAd138 = new QAd("STREAK_RESTORE_IN_FRIEND_PROFILE_HOURS", 137, AbstractC39113sc5.f(48, "PLUS_STREAK_RESTORE_IN_FRIEND_PROFILE_HOURS"));
        QAd qAd139 = new QAd("STREAK_RESTORE_PRIMARY_PLUS_UPSELL", 138, AbstractC39113sc5.v("PLUS_STREAK_RESTORE_PRIMARY_PLUS_UPSELLS", false));
        z2 = qAd139;
        QAd qAd140 = new QAd("THREE_TAB_ENABLED_OVERRIDE", 139, AbstractC39113sc5.v("NON_PLUS_FEATURE_GATING_THREE_TAB", false));
        A2 = qAd140;
        QAd qAd141 = new QAd("THREE_TAB_GRADIENT_FOOTER", Tweaks.SPONSORED_SNAPS_FEED_INSERT_MODE, AbstractC39113sc5.v("THREE_TAB_GRADIENT_FOOTER", false));
        B2 = qAd141;
        QAd qAd142 = new QAd("THREE_TAB_MIXED_FEED_SUBS_TOGGLE_ENABLED", Tweaks.SPONSORED_SNAPS_USER_INPUT_MODE, AbstractC39113sc5.v("FEED_SWITCHER_ENABLED", false));
        C2 = qAd142;
        QAd qAd143 = new QAd("THREE_TAB_FEED_SWITCHER_OPTIMIZATIONS", Tweaks.CALLBACK_FETCH_ON_FEED_DELEGATE, AbstractC39113sc5.f(0, "FEED_SWITCHER_OPTIMIZATIONS"));
        D2 = qAd143;
        QAd qAd144 = new QAd("TRUE_APP_THEMES_ENABLED", Tweaks.CALLBACK_QUERY_ON_FEED_DELEGATE, AbstractC39113sc5.v("PLUS_TRUE_APPTHEMES_ENABLED", false));
        E2 = qAd144;
        QAd qAd145 = new QAd("MIXED_CAROUSEL_P2R_TTL_MS_ANDROID", Tweaks.CALLBACK_SYNC_ON_FEED_DELEGATE, AbstractC39113sc5.f(0, "MIXED_CAROUSEL_P2R_TTL_MS_ANDROID"));
        F2 = qAd145;
        QAd qAd146 = new QAd("FRIENDS_TAB_CLEAN_UP", Tweaks.FEED_PAGINATION_V4_ENABLED, AbstractC39113sc5.v("SIMPLE_SNAPCHAT_FRIENDS_TAB_CLEAN_UP", false));
        G2 = qAd146;
        QAd qAd147 = new QAd("MIXED_CAROUSEL_PULL_DOWN_ENABLED", Tweaks.AUTO_PAGINATE_QUERY_FEED_ENABLED, AbstractC39113sc5.v("STORIES_CAROUSEL_IN_CHAT_PULL_DOWN_NFS", false));
        H2 = qAd147;
        QAd qAd148 = new QAd("MIXED_CAROUSEL_PULL_DOWN_P2R_DELAY_MS", Tweaks.AUTO_PAGINATE_QUERY_FEED_LITE_ENABLED, AbstractC39113sc5.o(0L, "STORIES_CAROUSEL_PULL_DOWN_P2R_DELAY_MS"));
        I2 = qAd148;
        QAd qAd149 = new QAd("MIXED_CAROUSEL_PULL_DOWN_AUTO_EXPAND_MODE", Tweaks.EXTENSION_DB_WAL_KILLSWITCH, AbstractC39113sc5.f(0, "STORIES_CAROUSEL_IN_CHAT_FORCED_EXPANSION"));
        J2 = qAd149;
        QAd qAd150 = new QAd("MIXED_CAROUSEL_SPLIT_FS_AND_NFS_PLAYBACK", Tweaks.EXTENSION_FAIL_SYNC_WRITE_KILLSWITCH, AbstractC39113sc5.v("MIXED_CAROUSEL_SPLIT_FS_NFS_PLAYBACK_ANDROID", false));
        K2 = qAd150;
        QAd qAd151 = new QAd("SHORTER_FOOTER_FF", Tweaks.LOGIN_PREFETCH_MIN_ENTRIES, AbstractC39113sc5.v("SIMPLE_SNAPCHAT_SHORTER_FOOTER_FF", false));
        L2 = qAd151;
        QAd qAd152 = new QAd("SIMPLE_SNAPCHAT_MAP_BUTTON_IN_HEADER", Tweaks.LOGIN_PREFETCH_MAX_ENTRIES, AbstractC39113sc5.v("SIMPLE_SNAPCHAT_MAP_BUTTON_IN_HEADER", false));
        M2 = qAd152;
        QAd qAd153 = new QAd("REMOVE_EXTRA_MARGIN_FOR_MIXED_CAROUSEL", Tweaks.LOGIN_PREFETCH_PAGE_SIZE, AbstractC39113sc5.v("REMOVE_EXTRA_MARGIN_FOR_MIXED_CAROUSEL_ANDROID", true));
        N2 = qAd153;
        DI3 di32 = DI3.t;
        AI3 ai33 = new AI3(di32, Float.valueOf(0.0f));
        ai33.t = "FF_FIXED_SIZE_CARD_STORY_CAROUSEL_MULTIPLIER_ANDROID";
        QAd qAd154 = new QAd("FF_FIXED_SIZE_CARD_STORY_CAROUSEL_MULTIPLIER", 153, ai33);
        O2 = qAd154;
        AI3 ai34 = new AI3(di32, Float.valueOf(0.0f));
        ai34.t = "DF_FIXED_SIZE_CARD_STORY_CAROUSEL_MULTIPLIER_ANDROID";
        QAd qAd155 = new QAd("DF_FIXED_SIZE_CARD_STORY_CAROUSEL_MULTIPLIER", Tweaks.ENABLE_LOGIN_PREFETCH, ai34);
        P2 = qAd155;
        QAd qAd156 = new QAd("MIXED_CAROUSEL_PRE_INFLATE_ALL_VIEWS", Tweaks.ENABLE_POST_SYNC_QUERY, AbstractC39113sc5.v("MIXED_CAROUSEL_PRE_INFLATE_ALL_VIEWS", false));
        Q2 = qAd156;
        QAd qAd157 = new QAd("MIXED_CAROUSEL_FIX_FRIEND_OPT_IN_STATE", Tweaks.ENABLE_MEDIA_PREFETCH_IGNORE_DOWNLOAD_STATUS, AbstractC39113sc5.v("MIXED_CAROUSEL_FIX_FRIEND_OPT_IN_STATE", false));
        R2 = qAd157;
        QAd qAd158 = new QAd("MIXED_CAROUSEL_UNIFY_PAGE_SESSION_ID", Tweaks.ENABLE_FEED_SYNC_V4_CORRECTION, AbstractC39113sc5.v("MIXED_CAROUSEL_UNIFY_PAGE_SESSION_ID", false));
        S2 = qAd158;
        QAd qAd159 = new QAd("MIXED_CAROUSEL_CLEAR_STORIES_NOTIFS_ON_FEED_ENTER", Tweaks.EEL_GROUP_CONFIG_COF_OVERRIDE64, AbstractC39113sc5.v("MIXED_CAROUSEL_CLEAR_STORIES_NOTIFS_ON_FEED_ENTER", false));
        T2 = qAd159;
        QAd qAd160 = new QAd("MIXED_CAROUSEL_RECTANGULAR_NFS_ITEM_CONFIG", Tweaks.ENABLE_RETRY_POST_SYNC_PREFETCH, AbstractC39113sc5.f(0, "MIXED_CAROUSEL_RECTANGULAR_NFS_ITEM_CONFIG_ANDROID"));
        U2 = qAd160;
        QAd qAd161 = new QAd("SIMPLE_SNAPCHAT_SETTINGS_FORCE_SWITCH", Tweaks.ENABLE_PUBLIC_GROUPS, AbstractC39113sc5.f(0, "SIMPLE_SNAPCHAT_SETTINGS_FORCE_SWITCH"));
        QAd qAd162 = new QAd("ONBOARDING_NUX_USE_COMPOSER_PAGE", Tweaks.ENABLE_AD_SYNC_ON_P2R, AbstractC39113sc5.v("SIMPLE_SNAPCHAT_ONBOARDING_NUX_USE_COMPOSER_PAGE", false));
        V2 = qAd162;
        QAd qAd163 = new QAd("SHOULD_USE_MIXED_FEED_FOURTH_TAB", Tweaks.ENABLE_STREAK_SETTINGS, AbstractC39113sc5.v("TAB__SWAP_TEST_COF", false));
        W2 = qAd163;
        QAd qAd164 = new QAd("DISABLE_SPOTLIGHT_SWIPE_TO_PROFILE", 163, AbstractC39113sc5.v("Horizontal_Swipe_To_Profile_From_Spotlight_Disabled", true));
        QAd qAd165 = new QAd("STORIES_CAROUSEL_IN_CHAT_5_TAB_ENABLED", 164, AbstractC39113sc5.v("STORIES_CAROUSEL_IN_CHAT_5_TAB_ENABLED", false));
        X2 = qAd165;
        QAd qAd166 = new QAd("REMOVE_FS_CAROUSEL_IN_DF_ENABLED", 165, AbstractC39113sc5.v("REMOVE_FS_CAROUSEL_IN_DF_ENABLED", false));
        Y2 = qAd166;
        QAd qAd167 = new QAd("STORIES_CAROUSEL_IN_CHAT_NUM_FS_PER_SUBS", 166, AbstractC39113sc5.f(-1, "stories_carousel_in_chat_num_fs_per_subs"));
        Z2 = qAd167;
        QAd qAd168 = new QAd("FEED_SWITCHER_ENABLED_IN_5_TAB", 167, AbstractC39113sc5.v("feed_switcher_enabled_5t", false));
        a3 = qAd168;
        QAd qAd169 = new QAd("FEED_SWITCHER_FOLLOWING_V2", 168, AbstractC39113sc5.v("MIXED_FEED_FOLLOWING_ENABLED", false));
        b3 = qAd169;
        QAd qAd170 = new QAd("LENS_PLUS_ELIGIBILITY_DIALOGS_ENABLED", 169, AbstractC39113sc5.v("LENS_PLUS_ELIGIBILITY_DIALOGS_ENABLED", false));
        c3 = qAd170;
        AI3 ai35 = new AI3(DI3.Y, "https://help.snapchat.com/");
        ai35.t = "LENS_PLUS_ELIGIBILITY_DIALOG_SUPPORT_URL";
        QAd qAd171 = new QAd("LENS_PLUS_ELIGIBILITY_DIALOG_SUPPORT_URL", 170, ai35);
        d3 = qAd171;
        e3 = new QAd[]{qAd, qAd2, qAd3, qAd4, qAd5, qAd6, qAd7, qAd8, qAd9, qAd10, qAd11, qAd12, qAd13, qAd14, qAd15, qAd16, qAd17, qAd18, qAd19, qAd20, qAd21, qAd22, qAd23, qAd24, qAd25, qAd26, qAd27, qAd28, qAd29, qAd30, qAd31, qAd32, qAd33, qAd34, qAd35, qAd36, qAd37, qAd38, qAd39, qAd40, qAd41, qAd42, qAd43, qAd44, qAd45, qAd46, qAd47, qAd48, qAd49, qAd50, qAd51, qAd52, qAd53, qAd54, qAd55, qAd56, qAd57, qAd58, qAd59, qAd60, qAd61, qAd62, qAd63, qAd64, qAd65, qAd66, qAd67, qAd68, qAd69, qAd70, qAd71, qAd72, qAd73, qAd74, qAd75, qAd76, qAd77, qAd78, qAd79, qAd80, qAd81, qAd82, qAd83, qAd84, qAd85, qAd86, qAd87, qAd88, qAd89, qAd90, qAd91, qAd92, qAd93, qAd94, qAd95, qAd96, qAd97, qAd98, qAd99, qAd100, qAd101, qAd102, qAd103, qAd104, qAd105, qAd106, qAd107, qAd108, qAd109, qAd110, qAd111, qAd112, qAd113, qAd114, qAd115, qAd116, qAd117, qAd118, qAd119, qAd120, qAd121, qAd122, qAd123, qAd124, qAd125, qAd126, qAd127, qAd128, qAd129, qAd130, qAd131, qAd132, qAd133, qAd134, qAd135, qAd136, qAd137, qAd138, qAd139, qAd140, qAd141, qAd142, qAd143, qAd144, qAd145, qAd146, qAd147, qAd148, qAd149, qAd150, qAd151, qAd152, qAd153, qAd154, qAd155, qAd156, qAd157, qAd158, qAd159, qAd160, qAd161, qAd162, qAd163, qAd164, qAd165, qAd166, qAd167, qAd168, qAd169, qAd170, qAd171};
    }

    public QAd(String str, int i, AI3 ai3) {
        this.a = ai3;
    }

    public static QAd valueOf(String str) {
        return (QAd) Enum.valueOf(QAd.class, str);
    }

    public static QAd[] values() {
        return (QAd[]) e3.clone();
    }

    @Override // defpackage.BI3
    public final EnumC48048zI3 e() {
        return this.b;
    }

    @Override // defpackage.BI3
    public final /* bridge */ /* synthetic */ String getName() {
        return name();
    }

    @Override // defpackage.BI3
    public final AI3 j() {
        return this.a;
    }
}
