package defpackage;

import android.view.ViewGroup;
import java.util.Arrays;
import java.util.HashMap;

/* loaded from: classes.dex */
public final class RL3 {
    public int a;
    public final UL3 b;
    public final TL3 c;
    public final SL3 d;
    public final VL3 e;
    public HashMap f;

    /* JADX WARN: Type inference failed for: r0v0, types: [java.lang.Object, UL3] */
    /* JADX WARN: Type inference failed for: r0v1, types: [java.lang.Object, TL3] */
    /* JADX WARN: Type inference failed for: r0v2, types: [java.lang.Object, SL3] */
    /* JADX WARN: Type inference failed for: r0v3, types: [java.lang.Object, VL3] */
    public RL3() {
        ?? obj = new Object();
        obj.a = 0;
        obj.b = 0;
        obj.c = 1.0f;
        obj.d = Float.NaN;
        this.b = obj;
        ?? obj2 = new Object();
        obj2.a = -1;
        obj2.b = -1;
        obj2.c = Float.NaN;
        obj2.d = Float.NaN;
        this.c = obj2;
        ?? obj3 = new Object();
        obj3.a = false;
        obj3.d = -1;
        obj3.e = -1;
        obj3.f = -1.0f;
        obj3.g = -1;
        obj3.h = -1;
        obj3.i = -1;
        obj3.j = -1;
        obj3.k = -1;
        obj3.l = -1;
        obj3.m = -1;
        obj3.n = -1;
        obj3.o = -1;
        obj3.p = -1;
        obj3.q = -1;
        obj3.r = -1;
        obj3.s = -1;
        obj3.t = 0.5f;
        obj3.u = 0.5f;
        obj3.v = null;
        obj3.w = -1;
        obj3.x = 0;
        obj3.y = 0.0f;
        obj3.z = -1;
        obj3.A = -1;
        obj3.B = -1;
        obj3.C = -1;
        obj3.D = -1;
        obj3.E = -1;
        obj3.F = -1;
        obj3.G = -1;
        obj3.H = -1;
        obj3.I = -1;
        obj3.f15775J = -1;
        obj3.K = -1;
        obj3.L = -1;
        obj3.M = -1;
        obj3.N = -1;
        obj3.O = -1.0f;
        obj3.P = -1.0f;
        obj3.Q = 0;
        obj3.R = 0;
        obj3.S = 0;
        obj3.T = 0;
        obj3.U = -1;
        obj3.V = -1;
        obj3.W = -1;
        obj3.X = -1;
        obj3.Y = 1.0f;
        obj3.Z = 1.0f;
        obj3.a0 = -1;
        obj3.b0 = 0;
        obj3.c0 = -1;
        obj3.g0 = false;
        obj3.h0 = false;
        obj3.i0 = true;
        this.d = obj3;
        ?? obj4 = new Object();
        obj4.a = 0.0f;
        obj4.b = 0.0f;
        obj4.c = 0.0f;
        obj4.d = 1.0f;
        obj4.e = 1.0f;
        obj4.f = Float.NaN;
        obj4.g = Float.NaN;
        obj4.h = 0.0f;
        obj4.i = 0.0f;
        obj4.j = 0.0f;
        obj4.k = false;
        obj4.l = 0.0f;
        this.e = obj4;
        this.f = new HashMap();
    }

    public final void a(LL3 ll3) {
        SL3 sl3 = this.d;
        ll3.d = sl3.g;
        ll3.e = sl3.h;
        ll3.f = sl3.i;
        ll3.g = sl3.j;
        ll3.h = sl3.k;
        ll3.i = sl3.l;
        ll3.j = sl3.m;
        ll3.k = sl3.n;
        ll3.l = sl3.o;
        ll3.p = sl3.p;
        ll3.q = sl3.q;
        ll3.r = sl3.r;
        ll3.s = sl3.s;
        ((ViewGroup.MarginLayoutParams) ll3).leftMargin = sl3.C;
        ((ViewGroup.MarginLayoutParams) ll3).rightMargin = sl3.D;
        ((ViewGroup.MarginLayoutParams) ll3).topMargin = sl3.E;
        ((ViewGroup.MarginLayoutParams) ll3).bottomMargin = sl3.F;
        ll3.x = sl3.N;
        ll3.y = sl3.M;
        ll3.u = sl3.f15775J;
        ll3.w = sl3.L;
        ll3.z = sl3.t;
        ll3.A = sl3.u;
        ll3.m = sl3.w;
        ll3.n = sl3.x;
        ll3.o = sl3.y;
        ll3.B = sl3.v;
        ll3.P = sl3.z;
        ll3.Q = sl3.A;
        ll3.E = sl3.O;
        ll3.D = sl3.P;
        ll3.G = sl3.R;
        ll3.F = sl3.Q;
        ll3.S = sl3.g0;
        ll3.T = sl3.h0;
        ll3.H = sl3.S;
        ll3.I = sl3.T;
        ll3.L = sl3.U;
        ll3.M = sl3.V;
        ll3.f15731J = sl3.W;
        ll3.K = sl3.X;
        ll3.N = sl3.Y;
        ll3.O = sl3.Z;
        ll3.R = sl3.B;
        ll3.c = sl3.f;
        ll3.a = sl3.d;
        ll3.b = sl3.e;
        ((ViewGroup.MarginLayoutParams) ll3).width = sl3.b;
        ((ViewGroup.MarginLayoutParams) ll3).height = sl3.c;
        String str = sl3.f0;
        if (str != null) {
            ll3.U = str;
        }
        ll3.setMarginStart(sl3.H);
        ll3.setMarginEnd(sl3.G);
        ll3.a();
    }

    public final Object clone() {
        RL3 rl3 = new RL3();
        SL3 sl3 = rl3.d;
        sl3.getClass();
        SL3 sl32 = this.d;
        sl3.a = sl32.a;
        sl3.b = sl32.b;
        sl3.c = sl32.c;
        sl3.d = sl32.d;
        sl3.e = sl32.e;
        sl3.f = sl32.f;
        sl3.g = sl32.g;
        sl3.h = sl32.h;
        sl3.i = sl32.i;
        sl3.j = sl32.j;
        sl3.k = sl32.k;
        sl3.l = sl32.l;
        sl3.m = sl32.m;
        sl3.n = sl32.n;
        sl3.o = sl32.o;
        sl3.p = sl32.p;
        sl3.q = sl32.q;
        sl3.r = sl32.r;
        sl3.s = sl32.s;
        sl3.t = sl32.t;
        sl3.u = sl32.u;
        sl3.v = sl32.v;
        sl3.w = sl32.w;
        sl3.x = sl32.x;
        sl3.y = sl32.y;
        sl3.z = sl32.z;
        sl3.A = sl32.A;
        sl3.B = sl32.B;
        sl3.C = sl32.C;
        sl3.D = sl32.D;
        sl3.E = sl32.E;
        sl3.F = sl32.F;
        sl3.G = sl32.G;
        sl3.H = sl32.H;
        sl3.I = sl32.I;
        sl3.f15775J = sl32.f15775J;
        sl3.K = sl32.K;
        sl3.L = sl32.L;
        sl3.M = sl32.M;
        sl3.N = sl32.N;
        sl3.O = sl32.O;
        sl3.P = sl32.P;
        sl3.Q = sl32.Q;
        sl3.R = sl32.R;
        sl3.S = sl32.S;
        sl3.T = sl32.T;
        sl3.U = sl32.U;
        sl3.V = sl32.V;
        sl3.W = sl32.W;
        sl3.X = sl32.X;
        sl3.Y = sl32.Y;
        sl3.Z = sl32.Z;
        sl3.a0 = sl32.a0;
        sl3.b0 = sl32.b0;
        sl3.c0 = sl32.c0;
        sl3.f0 = sl32.f0;
        int[] iArr = sl32.d0;
        if (iArr != null) {
            sl3.d0 = Arrays.copyOf(iArr, iArr.length);
        } else {
            sl3.d0 = null;
        }
        sl3.e0 = sl32.e0;
        sl3.g0 = sl32.g0;
        sl3.h0 = sl32.h0;
        sl3.i0 = sl32.i0;
        TL3 tl3 = rl3.c;
        tl3.getClass();
        TL3 tl32 = this.c;
        tl32.getClass();
        tl3.a = tl32.a;
        tl3.b = tl32.b;
        tl3.d = tl32.d;
        tl3.c = tl32.c;
        UL3 ul3 = rl3.b;
        UL3 ul32 = this.b;
        ul3.a = ul32.a;
        ul3.c = ul32.c;
        ul3.d = ul32.d;
        ul3.b = ul32.b;
        VL3 vl3 = rl3.e;
        vl3.getClass();
        VL3 vl32 = this.e;
        vl32.getClass();
        vl3.a = vl32.a;
        vl3.b = vl32.b;
        vl3.c = vl32.c;
        vl3.d = vl32.d;
        vl3.e = vl32.e;
        vl3.f = vl32.f;
        vl3.g = vl32.g;
        vl3.h = vl32.h;
        vl3.i = vl32.i;
        vl3.j = vl32.j;
        vl3.k = vl32.k;
        vl3.l = vl32.l;
        rl3.a = this.a;
        return rl3;
    }
}
