package com.snap.talkcore;

import com.snapchat.client.messaging.Tweaks;
import defpackage.EnumC5431Jv3;
import defpackage.InterfaceC4889Iv3;

/* JADX WARN: Failed to restore enum class, 'enum' modifier and super class removed */
/* JADX WARN: Unknown enum class pattern. Please report as an issue! */
@InterfaceC4889Iv3(propertyReplacements = "", schema = "'CsmInvalidInitialState':100,'CsmUnexpectedPublishedMediaInIncomingCall':101,'CsmNoPublishedMediaInCall':102,'CsmNoPublishedMediaInOutgoingCall':103,'CsmPublishAfterCallEnd':104,'CsmSendLeftCallRequest':105,'CsmSendStartCallRequest':106,'CsmSendStopCallRequest':107,'CsmStartStreamerConnectionAfterCallEnd':108,'CsmNoCallMediaWhileInCall':109,'CsmNoJoinedTimestamp':110,'CsmSharedLensInGroupCall':111,'CsmMissingUserIdOneOnOneCallOnInit':114,'CsmRingAgainInOneOnOneCall':117,'CsmSendJoinedCallRequest':118,'CsmSendTransitionToGroupRequest':119,'CsmSendTransitionToGroupRequestGroup':120,'CsmSendTransitionToGroupRequestNoAddedParticipants':121,'CsmLoadConversationInfoTimeout':122,'CsmLoadConversationInfoFailure':123,'CsmLoadConversationInfoNoId':124,'CsmLoadConversationInfoGroup':125,'CsmLoadConversationInfoFailureInvalid':126,'CsmNotEnoughRemoteParticipants':127,'CsmTransitionToGroupTimeout':128,'CsmTransitionToGroupResultHandledInWrongState':129,'NmcIllegalNextCallState':300,'NmcNoneStateNoEndReason':301,'NmcUnexpectedEventForRemoteHungUp':302,'NmcUnexpectedEventForConnectionFailure':303,'NmcUnexpectedOutgoingCallRejected':304,'NmcUnexpectedOutgoingCallTimeout':305,'NmcUnexpectedJoinCallAlreadyEnded':306,'NscRemoteUserStateMissing':400,'NscPublishBeforeStart':401,'NscPublishUfsBeforeStart':402,'PlatformBridgeSessionCreationFailed':500,'PlatformBridgePlatformEventError':501,'PlatformBridgeInvalidIntent':502,'PlatformBridgeUnhandledEvent':503,'PlatformBridgeNonIncomingCallActionMessageFailedToDisplay':504,'PlatformBridgeStatusMessageSendFailed':505,'PlatformBridgeCachedTalkCoreAlreadyExists':506,'PlatformBridgeCallingManagerInitFailed':508,'PlatformSessionCreationFailed':600,'PlatformSessionCreationFailedOnResume':601,'PlatformVolatileMessageProcessingFailed':602,'PlatformCallRequestProcessingFailed':603,'PlatformTalkCorePrepareDependenciesFailed':604,'PlatformTalkCoreInitFailed':605,'ParsingFailed':700,'ParsingNoDataForVolatileMessage':701,'ParsingInvalidMessageSchema':702,'ParsingInvalidConversationId':703,'ParsingInvalidSenderId':704,'ParsingCallRequestFailed':705,'ParsingInvalidCallActionPayload':706,'ParsingNonStartIncomingCallAction':707,'ParsingNonCallActionPayload':708,'ParsingInvalidNotificationPayload':709,'ParsingNonCallActionPayloadInNotification':710,'ParsingInvalidPersistingStateJson':711,'ParsingInvalidPersistingState':712,'ParsingInvalidStreamerPayload':713,'FailedToProcessIncomingCallMessage':714,'VideoDecoderUnexpectedMimeType':800,'VideoDecoderInitialization':801,'VideoDecoderOutputSurfaceInitialization':802,'VideoDecoderFramePoolCreation':803,'VideoDecoderFramePoolCheckOut':804,'VideoDecoderFramePoolDispose':805,'VideoDecoderOutputSurfaceRelease':806,'VideoDecoderOutputSurfaceCopy':807,'VideoRendererEglInitialization':900,'VideoRendererCreation':901,'VideoRendererDisposal':902,'VideoRendererSurfaceUpdate':903,'VideoRendererFrameRendering':904,'VideoRendererResize':905,'VideoRendererAttachSurface':906,'VideoRendererReleaseSurface':907,'VideoRendererCleanCache':908,'VideoRendererReleaseEgl':909,'VideoRendererReleaseRenderPass':910,'VideoRendererSurfaceResize':911,'VideoRendererSurfaceUnbind':912,'ScreenSharingRequestPermission':1000,'ScreenSharingBindService':1001,'ScreenSharingServiceStop':1002,'ScreenSharingMediaProjection':1003,'ScreenSharingVirtualDisplay':1004,'ScreenSharingFrameThrottle':1005,'ScreenSharingVirtualDisplayResize':1006,'WebUserUpdateBeforeSignaling':1100,'WebMsgBeforeConnectionParams':1101,'WebMsgParsingNoTalkId':1102,'WebMsgParsingNoIceCreds':1103,'WebMsgParsingNoTransportParams':1104,'WebMsgParsingNoLocalSsrcs':1105,'WebMsgParsingNoFixedRelaySsrcs':1106,'WebCallLogAppendFailedPrecondition':1107,'BlizzardCallAttemptUnexpectedCallState':1300,'BlizzardCallAttemptUndefinedCallUuid':1301,'BlizzardCallRequestUndefinedCallUuid':1302,'BlizzardMetricsShadowerError':1303,'DuplexCallRequestFailure':1400,'DuplexStreamerDataFailure':1401,'DuplexValdiSendMessageFailure':1403,'DuplexValdiRegisterMessageHandlerFailure':1405,'CallLogAppendFailureInCollector':1500,'CallLogAppendFailureFromMissedNotification':1501,'CallLogAppendMissingPayload':1502,'CallLogAppendMissingCallId':1503,'CallLogPlatformFeedSyncTriggerFailed':1504,'CallLogPlatformRecentCallsTriggerFailed':1505,'CallLogLocalPutFailureInCollector':1506,'CallLogLocalPutFailureFromMissedNotification':1507,'InCallServiceStartForeground':1600,'InAppPipFloatingTransition':1601,'InitialTalkContextFallback':1602,'MissingTalkContextOnLaunch':1603,'InCallServicePostNotification':1604,'CallFeedbackAudio':1700,'CallFeedbackAudioRemote':1701,'CallFeedbackAudioLocal':1702,'CallFeedbackAudioEcho':1703,'CallFeedbackAudioBackgroundNoise':1704,'CallFeedbackAudioCutting':1705,'CallFeedbackAudioVolume':1706,'CallFeedbackAudioOther':1707,'CallFeedbackVideo':1708,'CallFeedbackVideoBlurry':1709,'CallFeedbackVideoCamera':1710,'CallFeedbackVideoBlank':1711,'CallFeedbackVideoOther':1712,'CallFeedbackCallConnection':1713,'CallFeedbackCallConnectionCantJoin':1714,'CallFeedbackCallConnectionHungUp':1715,'CallFeedbackCallConnectionLaggy':1716,'CallFeedbackCallConnectionOther':1717,'CallFeedbackExternalDeviceConnection':1718,'CallFeedbackExternalDeviceConnectionBluetoothAudio':1719,'CallFeedbackExternalDeviceConnectionMicrophone':1720,'CallFeedbackExternalDeviceConnectionOther':1721,'CallFeedbackOther':1722,'CallStatusMessageSenderSendFailed':1800,'CallStatusMessageSenderSendFailedStatusUnknown':1830,'CallingUiCallingSessionTimeout':1900,'CallingUiGetCallingSessionError':1901,'CallingUiGetCallingSessionNotReady':1902,'AudioMLModelFetchError':2000", type = EnumC5431Jv3.a)
/* loaded from: classes8.dex */
public final class CallingErrorCode {
    public static final CallingErrorCode CsmInvalidInitialState = new Enum("CsmInvalidInitialState", 0);
    public static final CallingErrorCode CsmUnexpectedPublishedMediaInIncomingCall = new Enum("CsmUnexpectedPublishedMediaInIncomingCall", 1);
    public static final CallingErrorCode CsmNoPublishedMediaInCall = new Enum("CsmNoPublishedMediaInCall", 2);
    public static final CallingErrorCode CsmNoPublishedMediaInOutgoingCall = new Enum("CsmNoPublishedMediaInOutgoingCall", 3);
    public static final CallingErrorCode CsmPublishAfterCallEnd = new Enum("CsmPublishAfterCallEnd", 4);
    public static final CallingErrorCode CsmSendLeftCallRequest = new Enum("CsmSendLeftCallRequest", 5);
    public static final CallingErrorCode CsmSendStartCallRequest = new Enum("CsmSendStartCallRequest", 6);
    public static final CallingErrorCode CsmSendStopCallRequest = new Enum("CsmSendStopCallRequest", 7);
    public static final CallingErrorCode CsmStartStreamerConnectionAfterCallEnd = new Enum("CsmStartStreamerConnectionAfterCallEnd", 8);
    public static final CallingErrorCode CsmNoCallMediaWhileInCall = new Enum("CsmNoCallMediaWhileInCall", 9);
    public static final CallingErrorCode CsmNoJoinedTimestamp = new Enum("CsmNoJoinedTimestamp", 10);
    public static final CallingErrorCode CsmSharedLensInGroupCall = new Enum("CsmSharedLensInGroupCall", 11);
    public static final CallingErrorCode CsmMissingUserIdOneOnOneCallOnInit = new Enum("CsmMissingUserIdOneOnOneCallOnInit", 12);
    public static final CallingErrorCode CsmRingAgainInOneOnOneCall = new Enum("CsmRingAgainInOneOnOneCall", 13);
    public static final CallingErrorCode CsmSendJoinedCallRequest = new Enum("CsmSendJoinedCallRequest", 14);
    public static final CallingErrorCode CsmSendTransitionToGroupRequest = new Enum("CsmSendTransitionToGroupRequest", 15);
    public static final CallingErrorCode CsmSendTransitionToGroupRequestGroup = new Enum("CsmSendTransitionToGroupRequestGroup", 16);
    public static final CallingErrorCode CsmSendTransitionToGroupRequestNoAddedParticipants = new Enum("CsmSendTransitionToGroupRequestNoAddedParticipants", 17);
    public static final CallingErrorCode CsmLoadConversationInfoTimeout = new Enum("CsmLoadConversationInfoTimeout", 18);
    public static final CallingErrorCode CsmLoadConversationInfoFailure = new Enum("CsmLoadConversationInfoFailure", 19);
    public static final CallingErrorCode CsmLoadConversationInfoNoId = new Enum("CsmLoadConversationInfoNoId", 20);
    public static final CallingErrorCode CsmLoadConversationInfoGroup = new Enum("CsmLoadConversationInfoGroup", 21);
    public static final CallingErrorCode CsmLoadConversationInfoFailureInvalid = new Enum("CsmLoadConversationInfoFailureInvalid", 22);
    public static final CallingErrorCode CsmNotEnoughRemoteParticipants = new Enum("CsmNotEnoughRemoteParticipants", 23);
    public static final CallingErrorCode CsmTransitionToGroupTimeout = new Enum("CsmTransitionToGroupTimeout", 24);
    public static final CallingErrorCode CsmTransitionToGroupResultHandledInWrongState = new Enum("CsmTransitionToGroupResultHandledInWrongState", 25);
    public static final CallingErrorCode NmcIllegalNextCallState = new Enum("NmcIllegalNextCallState", 26);
    public static final CallingErrorCode NmcNoneStateNoEndReason = new Enum("NmcNoneStateNoEndReason", 27);
    public static final CallingErrorCode NmcUnexpectedEventForRemoteHungUp = new Enum("NmcUnexpectedEventForRemoteHungUp", 28);
    public static final CallingErrorCode NmcUnexpectedEventForConnectionFailure = new Enum("NmcUnexpectedEventForConnectionFailure", 29);
    public static final CallingErrorCode NmcUnexpectedOutgoingCallRejected = new Enum("NmcUnexpectedOutgoingCallRejected", 30);
    public static final CallingErrorCode NmcUnexpectedOutgoingCallTimeout = new Enum("NmcUnexpectedOutgoingCallTimeout", 31);
    public static final CallingErrorCode NmcUnexpectedJoinCallAlreadyEnded = new Enum("NmcUnexpectedJoinCallAlreadyEnded", 32);
    public static final CallingErrorCode NscRemoteUserStateMissing = new Enum("NscRemoteUserStateMissing", 33);
    public static final CallingErrorCode NscPublishBeforeStart = new Enum("NscPublishBeforeStart", 34);
    public static final CallingErrorCode NscPublishUfsBeforeStart = new Enum("NscPublishUfsBeforeStart", 35);
    public static final CallingErrorCode PlatformBridgeSessionCreationFailed = new Enum("PlatformBridgeSessionCreationFailed", 36);
    public static final CallingErrorCode PlatformBridgePlatformEventError = new Enum("PlatformBridgePlatformEventError", 37);
    public static final CallingErrorCode PlatformBridgeInvalidIntent = new Enum("PlatformBridgeInvalidIntent", 38);
    public static final CallingErrorCode PlatformBridgeUnhandledEvent = new Enum("PlatformBridgeUnhandledEvent", 39);
    public static final CallingErrorCode PlatformBridgeNonIncomingCallActionMessageFailedToDisplay = new Enum("PlatformBridgeNonIncomingCallActionMessageFailedToDisplay", 40);
    public static final CallingErrorCode PlatformBridgeStatusMessageSendFailed = new Enum("PlatformBridgeStatusMessageSendFailed", 41);
    public static final CallingErrorCode PlatformBridgeCachedTalkCoreAlreadyExists = new Enum("PlatformBridgeCachedTalkCoreAlreadyExists", 42);
    public static final CallingErrorCode PlatformBridgeCallingManagerInitFailed = new Enum("PlatformBridgeCallingManagerInitFailed", 43);
    public static final CallingErrorCode PlatformSessionCreationFailed = new Enum("PlatformSessionCreationFailed", 44);
    public static final CallingErrorCode PlatformSessionCreationFailedOnResume = new Enum("PlatformSessionCreationFailedOnResume", 45);
    public static final CallingErrorCode PlatformVolatileMessageProcessingFailed = new Enum("PlatformVolatileMessageProcessingFailed", 46);
    public static final CallingErrorCode PlatformCallRequestProcessingFailed = new Enum("PlatformCallRequestProcessingFailed", 47);
    public static final CallingErrorCode PlatformTalkCorePrepareDependenciesFailed = new Enum("PlatformTalkCorePrepareDependenciesFailed", 48);
    public static final CallingErrorCode PlatformTalkCoreInitFailed = new Enum("PlatformTalkCoreInitFailed", 49);
    public static final CallingErrorCode ParsingFailed = new Enum("ParsingFailed", 50);
    public static final CallingErrorCode ParsingNoDataForVolatileMessage = new Enum("ParsingNoDataForVolatileMessage", 51);
    public static final CallingErrorCode ParsingInvalidMessageSchema = new Enum("ParsingInvalidMessageSchema", 52);
    public static final CallingErrorCode ParsingInvalidConversationId = new Enum("ParsingInvalidConversationId", 53);
    public static final CallingErrorCode ParsingInvalidSenderId = new Enum("ParsingInvalidSenderId", 54);
    public static final CallingErrorCode ParsingCallRequestFailed = new Enum("ParsingCallRequestFailed", 55);
    public static final CallingErrorCode ParsingInvalidCallActionPayload = new Enum("ParsingInvalidCallActionPayload", 56);
    public static final CallingErrorCode ParsingNonStartIncomingCallAction = new Enum("ParsingNonStartIncomingCallAction", 57);
    public static final CallingErrorCode ParsingNonCallActionPayload = new Enum("ParsingNonCallActionPayload", 58);
    public static final CallingErrorCode ParsingInvalidNotificationPayload = new Enum("ParsingInvalidNotificationPayload", 59);
    public static final CallingErrorCode ParsingNonCallActionPayloadInNotification = new Enum("ParsingNonCallActionPayloadInNotification", 60);
    public static final CallingErrorCode ParsingInvalidPersistingStateJson = new Enum("ParsingInvalidPersistingStateJson", 61);
    public static final CallingErrorCode ParsingInvalidPersistingState = new Enum("ParsingInvalidPersistingState", 62);
    public static final CallingErrorCode ParsingInvalidStreamerPayload = new Enum("ParsingInvalidStreamerPayload", 63);
    public static final CallingErrorCode FailedToProcessIncomingCallMessage = new Enum("FailedToProcessIncomingCallMessage", 64);
    public static final CallingErrorCode VideoDecoderUnexpectedMimeType = new Enum("VideoDecoderUnexpectedMimeType", 65);
    public static final CallingErrorCode VideoDecoderInitialization = new Enum("VideoDecoderInitialization", 66);
    public static final CallingErrorCode VideoDecoderOutputSurfaceInitialization = new Enum("VideoDecoderOutputSurfaceInitialization", 67);
    public static final CallingErrorCode VideoDecoderFramePoolCreation = new Enum("VideoDecoderFramePoolCreation", 68);
    public static final CallingErrorCode VideoDecoderFramePoolCheckOut = new Enum("VideoDecoderFramePoolCheckOut", 69);
    public static final CallingErrorCode VideoDecoderFramePoolDispose = new Enum("VideoDecoderFramePoolDispose", 70);
    public static final CallingErrorCode VideoDecoderOutputSurfaceRelease = new Enum("VideoDecoderOutputSurfaceRelease", 71);
    public static final CallingErrorCode VideoDecoderOutputSurfaceCopy = new Enum("VideoDecoderOutputSurfaceCopy", 72);
    public static final CallingErrorCode VideoRendererEglInitialization = new Enum("VideoRendererEglInitialization", 73);
    public static final CallingErrorCode VideoRendererCreation = new Enum("VideoRendererCreation", 74);
    public static final CallingErrorCode VideoRendererDisposal = new Enum("VideoRendererDisposal", 75);
    public static final CallingErrorCode VideoRendererSurfaceUpdate = new Enum("VideoRendererSurfaceUpdate", 76);
    public static final CallingErrorCode VideoRendererFrameRendering = new Enum("VideoRendererFrameRendering", 77);
    public static final CallingErrorCode VideoRendererResize = new Enum("VideoRendererResize", 78);
    public static final CallingErrorCode VideoRendererAttachSurface = new Enum("VideoRendererAttachSurface", 79);
    public static final CallingErrorCode VideoRendererReleaseSurface = new Enum("VideoRendererReleaseSurface", 80);
    public static final CallingErrorCode VideoRendererCleanCache = new Enum("VideoRendererCleanCache", 81);
    public static final CallingErrorCode VideoRendererReleaseEgl = new Enum("VideoRendererReleaseEgl", 82);
    public static final CallingErrorCode VideoRendererReleaseRenderPass = new Enum("VideoRendererReleaseRenderPass", 83);
    public static final CallingErrorCode VideoRendererSurfaceResize = new Enum("VideoRendererSurfaceResize", 84);
    public static final CallingErrorCode VideoRendererSurfaceUnbind = new Enum("VideoRendererSurfaceUnbind", 85);
    public static final CallingErrorCode ScreenSharingRequestPermission = new Enum("ScreenSharingRequestPermission", 86);
    public static final CallingErrorCode ScreenSharingBindService = new Enum("ScreenSharingBindService", 87);
    public static final CallingErrorCode ScreenSharingServiceStop = new Enum("ScreenSharingServiceStop", 88);
    public static final CallingErrorCode ScreenSharingMediaProjection = new Enum("ScreenSharingMediaProjection", 89);
    public static final CallingErrorCode ScreenSharingVirtualDisplay = new Enum("ScreenSharingVirtualDisplay", 90);
    public static final CallingErrorCode ScreenSharingFrameThrottle = new Enum("ScreenSharingFrameThrottle", 91);
    public static final CallingErrorCode ScreenSharingVirtualDisplayResize = new Enum("ScreenSharingVirtualDisplayResize", 92);
    public static final CallingErrorCode WebUserUpdateBeforeSignaling = new Enum("WebUserUpdateBeforeSignaling", 93);
    public static final CallingErrorCode WebMsgBeforeConnectionParams = new Enum("WebMsgBeforeConnectionParams", 94);
    public static final CallingErrorCode WebMsgParsingNoTalkId = new Enum("WebMsgParsingNoTalkId", 95);
    public static final CallingErrorCode WebMsgParsingNoIceCreds = new Enum("WebMsgParsingNoIceCreds", 96);
    public static final CallingErrorCode WebMsgParsingNoTransportParams = new Enum("WebMsgParsingNoTransportParams", 97);
    public static final CallingErrorCode WebMsgParsingNoLocalSsrcs = new Enum("WebMsgParsingNoLocalSsrcs", 98);
    public static final CallingErrorCode WebMsgParsingNoFixedRelaySsrcs = new Enum("WebMsgParsingNoFixedRelaySsrcs", 99);
    public static final CallingErrorCode WebCallLogAppendFailedPrecondition = new Enum("WebCallLogAppendFailedPrecondition", 100);
    public static final CallingErrorCode BlizzardCallAttemptUnexpectedCallState = new Enum("BlizzardCallAttemptUnexpectedCallState", 101);
    public static final CallingErrorCode BlizzardCallAttemptUndefinedCallUuid = new Enum("BlizzardCallAttemptUndefinedCallUuid", 102);
    public static final CallingErrorCode BlizzardCallRequestUndefinedCallUuid = new Enum("BlizzardCallRequestUndefinedCallUuid", 103);
    public static final CallingErrorCode BlizzardMetricsShadowerError = new Enum("BlizzardMetricsShadowerError", 104);
    public static final CallingErrorCode DuplexCallRequestFailure = new Enum("DuplexCallRequestFailure", 105);
    public static final CallingErrorCode DuplexStreamerDataFailure = new Enum("DuplexStreamerDataFailure", 106);
    public static final CallingErrorCode DuplexValdiSendMessageFailure = new Enum("DuplexValdiSendMessageFailure", 107);
    public static final CallingErrorCode DuplexValdiRegisterMessageHandlerFailure = new Enum("DuplexValdiRegisterMessageHandlerFailure", 108);
    public static final CallingErrorCode CallLogAppendFailureInCollector = new Enum("CallLogAppendFailureInCollector", Tweaks.MAX_HOURS_AFTER_STREAK_EXPIRE_TO_ENABLE_RESTORE);
    public static final CallingErrorCode CallLogAppendFailureFromMissedNotification = new Enum("CallLogAppendFailureFromMissedNotification", Tweaks.ENABLE_STREAK_EDUCATION);
    public static final CallingErrorCode CallLogAppendMissingPayload = new Enum("CallLogAppendMissingPayload", 111);
    public static final CallingErrorCode CallLogAppendMissingCallId = new Enum("CallLogAppendMissingCallId", 112);
    public static final CallingErrorCode CallLogPlatformFeedSyncTriggerFailed = new Enum("CallLogPlatformFeedSyncTriggerFailed", Tweaks.DELTA_SYNC_SQLITE_SHARED_STORAGE_CACHE_SIZE);
    public static final CallingErrorCode CallLogPlatformRecentCallsTriggerFailed = new Enum("CallLogPlatformRecentCallsTriggerFailed", Tweaks.FAIL_DECRYPT_FOR_DUPLEX_SNAPS_TEST_ONLY);
    public static final CallingErrorCode CallLogLocalPutFailureInCollector = new Enum("CallLogLocalPutFailureInCollector", 115);
    public static final CallingErrorCode CallLogLocalPutFailureFromMissedNotification = new Enum("CallLogLocalPutFailureFromMissedNotification", 116);
    public static final CallingErrorCode InCallServiceStartForeground = new Enum("InCallServiceStartForeground", 117);
    public static final CallingErrorCode InAppPipFloatingTransition = new Enum("InAppPipFloatingTransition", 118);
    public static final CallingErrorCode InitialTalkContextFallback = new Enum("InitialTalkContextFallback", 119);
    public static final CallingErrorCode MissingTalkContextOnLaunch = new Enum("MissingTalkContextOnLaunch", 120);
    public static final CallingErrorCode InCallServicePostNotification = new Enum("InCallServicePostNotification", 121);
    public static final CallingErrorCode CallFeedbackAudio = new Enum("CallFeedbackAudio", 122);
    public static final CallingErrorCode CallFeedbackAudioRemote = new Enum("CallFeedbackAudioRemote", 123);
    public static final CallingErrorCode CallFeedbackAudioLocal = new Enum("CallFeedbackAudioLocal", 124);
    public static final CallingErrorCode CallFeedbackAudioEcho = new Enum("CallFeedbackAudioEcho", 125);
    public static final CallingErrorCode CallFeedbackAudioBackgroundNoise = new Enum("CallFeedbackAudioBackgroundNoise", 126);
    public static final CallingErrorCode CallFeedbackAudioCutting = new Enum("CallFeedbackAudioCutting", 127);
    public static final CallingErrorCode CallFeedbackAudioVolume = new Enum("CallFeedbackAudioVolume", 128);
    public static final CallingErrorCode CallFeedbackAudioOther = new Enum("CallFeedbackAudioOther", 129);
    public static final CallingErrorCode CallFeedbackVideo = new Enum("CallFeedbackVideo", 130);
    public static final CallingErrorCode CallFeedbackVideoBlurry = new Enum("CallFeedbackVideoBlurry", 131);
    public static final CallingErrorCode CallFeedbackVideoCamera = new Enum("CallFeedbackVideoCamera", 132);
    public static final CallingErrorCode CallFeedbackVideoBlank = new Enum("CallFeedbackVideoBlank", 133);
    public static final CallingErrorCode CallFeedbackVideoOther = new Enum("CallFeedbackVideoOther", 134);
    public static final CallingErrorCode CallFeedbackCallConnection = new Enum("CallFeedbackCallConnection", 135);
    public static final CallingErrorCode CallFeedbackCallConnectionCantJoin = new Enum("CallFeedbackCallConnectionCantJoin", 136);
    public static final CallingErrorCode CallFeedbackCallConnectionHungUp = new Enum("CallFeedbackCallConnectionHungUp", 137);
    public static final CallingErrorCode CallFeedbackCallConnectionLaggy = new Enum("CallFeedbackCallConnectionLaggy", 138);
    public static final CallingErrorCode CallFeedbackCallConnectionOther = new Enum("CallFeedbackCallConnectionOther", 139);
    public static final CallingErrorCode CallFeedbackExternalDeviceConnection = new Enum("CallFeedbackExternalDeviceConnection", Tweaks.SPONSORED_SNAPS_FEED_INSERT_MODE);
    public static final CallingErrorCode CallFeedbackExternalDeviceConnectionBluetoothAudio = new Enum("CallFeedbackExternalDeviceConnectionBluetoothAudio", Tweaks.SPONSORED_SNAPS_USER_INPUT_MODE);
    public static final CallingErrorCode CallFeedbackExternalDeviceConnectionMicrophone = new Enum("CallFeedbackExternalDeviceConnectionMicrophone", Tweaks.CALLBACK_FETCH_ON_FEED_DELEGATE);
    public static final CallingErrorCode CallFeedbackExternalDeviceConnectionOther = new Enum("CallFeedbackExternalDeviceConnectionOther", Tweaks.CALLBACK_QUERY_ON_FEED_DELEGATE);
    public static final CallingErrorCode CallFeedbackOther = new Enum("CallFeedbackOther", Tweaks.CALLBACK_SYNC_ON_FEED_DELEGATE);
    public static final CallingErrorCode CallStatusMessageSenderSendFailed = new Enum("CallStatusMessageSenderSendFailed", Tweaks.FEED_PAGINATION_V4_ENABLED);
    public static final CallingErrorCode CallStatusMessageSenderSendFailedStatusUnknown = new Enum("CallStatusMessageSenderSendFailedStatusUnknown", Tweaks.AUTO_PAGINATE_QUERY_FEED_ENABLED);
    public static final CallingErrorCode CallingUiCallingSessionTimeout = new Enum("CallingUiCallingSessionTimeout", Tweaks.AUTO_PAGINATE_QUERY_FEED_LITE_ENABLED);
    public static final CallingErrorCode CallingUiGetCallingSessionError = new Enum("CallingUiGetCallingSessionError", Tweaks.EXTENSION_DB_WAL_KILLSWITCH);
    public static final CallingErrorCode CallingUiGetCallingSessionNotReady = new Enum("CallingUiGetCallingSessionNotReady", Tweaks.EXTENSION_FAIL_SYNC_WRITE_KILLSWITCH);
    public static final CallingErrorCode AudioMLModelFetchError = new Enum("AudioMLModelFetchError", Tweaks.LOGIN_PREFETCH_MIN_ENTRIES);
    public static final /* synthetic */ CallingErrorCode[] a = {CsmInvalidInitialState, CsmUnexpectedPublishedMediaInIncomingCall, CsmNoPublishedMediaInCall, CsmNoPublishedMediaInOutgoingCall, CsmPublishAfterCallEnd, CsmSendLeftCallRequest, CsmSendStartCallRequest, CsmSendStopCallRequest, CsmStartStreamerConnectionAfterCallEnd, CsmNoCallMediaWhileInCall, CsmNoJoinedTimestamp, CsmSharedLensInGroupCall, CsmMissingUserIdOneOnOneCallOnInit, CsmRingAgainInOneOnOneCall, CsmSendJoinedCallRequest, CsmSendTransitionToGroupRequest, CsmSendTransitionToGroupRequestGroup, CsmSendTransitionToGroupRequestNoAddedParticipants, CsmLoadConversationInfoTimeout, CsmLoadConversationInfoFailure, CsmLoadConversationInfoNoId, CsmLoadConversationInfoGroup, CsmLoadConversationInfoFailureInvalid, CsmNotEnoughRemoteParticipants, CsmTransitionToGroupTimeout, CsmTransitionToGroupResultHandledInWrongState, NmcIllegalNextCallState, NmcNoneStateNoEndReason, NmcUnexpectedEventForRemoteHungUp, NmcUnexpectedEventForConnectionFailure, NmcUnexpectedOutgoingCallRejected, NmcUnexpectedOutgoingCallTimeout, NmcUnexpectedJoinCallAlreadyEnded, NscRemoteUserStateMissing, NscPublishBeforeStart, NscPublishUfsBeforeStart, PlatformBridgeSessionCreationFailed, PlatformBridgePlatformEventError, PlatformBridgeInvalidIntent, PlatformBridgeUnhandledEvent, PlatformBridgeNonIncomingCallActionMessageFailedToDisplay, PlatformBridgeStatusMessageSendFailed, PlatformBridgeCachedTalkCoreAlreadyExists, PlatformBridgeCallingManagerInitFailed, PlatformSessionCreationFailed, PlatformSessionCreationFailedOnResume, PlatformVolatileMessageProcessingFailed, PlatformCallRequestProcessingFailed, PlatformTalkCorePrepareDependenciesFailed, PlatformTalkCoreInitFailed, ParsingFailed, ParsingNoDataForVolatileMessage, ParsingInvalidMessageSchema, ParsingInvalidConversationId, ParsingInvalidSenderId, ParsingCallRequestFailed, ParsingInvalidCallActionPayload, ParsingNonStartIncomingCallAction, ParsingNonCallActionPayload, ParsingInvalidNotificationPayload, ParsingNonCallActionPayloadInNotification, ParsingInvalidPersistingStateJson, ParsingInvalidPersistingState, ParsingInvalidStreamerPayload, FailedToProcessIncomingCallMessage, VideoDecoderUnexpectedMimeType, VideoDecoderInitialization, VideoDecoderOutputSurfaceInitialization, VideoDecoderFramePoolCreation, VideoDecoderFramePoolCheckOut, VideoDecoderFramePoolDispose, VideoDecoderOutputSurfaceRelease, VideoDecoderOutputSurfaceCopy, VideoRendererEglInitialization, VideoRendererCreation, VideoRendererDisposal, VideoRendererSurfaceUpdate, VideoRendererFrameRendering, VideoRendererResize, VideoRendererAttachSurface, VideoRendererReleaseSurface, VideoRendererCleanCache, VideoRendererReleaseEgl, VideoRendererReleaseRenderPass, VideoRendererSurfaceResize, VideoRendererSurfaceUnbind, ScreenSharingRequestPermission, ScreenSharingBindService, ScreenSharingServiceStop, ScreenSharingMediaProjection, ScreenSharingVirtualDisplay, ScreenSharingFrameThrottle, ScreenSharingVirtualDisplayResize, WebUserUpdateBeforeSignaling, WebMsgBeforeConnectionParams, WebMsgParsingNoTalkId, WebMsgParsingNoIceCreds, WebMsgParsingNoTransportParams, WebMsgParsingNoLocalSsrcs, WebMsgParsingNoFixedRelaySsrcs, WebCallLogAppendFailedPrecondition, BlizzardCallAttemptUnexpectedCallState, BlizzardCallAttemptUndefinedCallUuid, BlizzardCallRequestUndefinedCallUuid, BlizzardMetricsShadowerError, DuplexCallRequestFailure, DuplexStreamerDataFailure, DuplexValdiSendMessageFailure, DuplexValdiRegisterMessageHandlerFailure, CallLogAppendFailureInCollector, CallLogAppendFailureFromMissedNotification, CallLogAppendMissingPayload, CallLogAppendMissingCallId, CallLogPlatformFeedSyncTriggerFailed, CallLogPlatformRecentCallsTriggerFailed, CallLogLocalPutFailureInCollector, CallLogLocalPutFailureFromMissedNotification, InCallServiceStartForeground, InAppPipFloatingTransition, InitialTalkContextFallback, MissingTalkContextOnLaunch, InCallServicePostNotification, CallFeedbackAudio, CallFeedbackAudioRemote, CallFeedbackAudioLocal, CallFeedbackAudioEcho, CallFeedbackAudioBackgroundNoise, CallFeedbackAudioCutting, CallFeedbackAudioVolume, CallFeedbackAudioOther, CallFeedbackVideo, CallFeedbackVideoBlurry, CallFeedbackVideoCamera, CallFeedbackVideoBlank, CallFeedbackVideoOther, CallFeedbackCallConnection, CallFeedbackCallConnectionCantJoin, CallFeedbackCallConnectionHungUp, CallFeedbackCallConnectionLaggy, CallFeedbackCallConnectionOther, CallFeedbackExternalDeviceConnection, CallFeedbackExternalDeviceConnectionBluetoothAudio, CallFeedbackExternalDeviceConnectionMicrophone, CallFeedbackExternalDeviceConnectionOther, CallFeedbackOther, CallStatusMessageSenderSendFailed, CallStatusMessageSenderSendFailedStatusUnknown, CallingUiCallingSessionTimeout, CallingUiGetCallingSessionError, CallingUiGetCallingSessionNotReady, AudioMLModelFetchError};

    public static CallingErrorCode valueOf(String str) {
        return (CallingErrorCode) Enum.valueOf(CallingErrorCode.class, str);
    }

    public static CallingErrorCode[] values() {
        return (CallingErrorCode[]) a.clone();
    }
}
