package com.snapchat.client.content_manager;

/* loaded from: classes6.dex */
public enum StreamErrorReason {
    STREAMNETWORKERROR,
    STREAMCONTENTFORBIDDENERROR,
    STREAMCONTENTNOTFOUNDERROR,
    STREAMCACHEREADERROR,
    STREAMCACHEWRITEERROR,
    STREAMUNEXPECTEDDATAERROR,
    STREAMRANGEERROR,
    STREAMREFERENCECOUNTZEROERROR,
    STREAMCANCELLED,
    BOLTCONTENTREFRESHED
}
