package com.snapchat.client.messaging;

/* loaded from: classes.dex */
public enum ForceFailSendFlowStepName {
    PERSISTSENDQUEUEDSTEP,
    VALIDATESENDORDERSTEP,
    VALIDATESENDMESSAGENETWORKSTEP,
    CREATENETWORKGROUPSSTEP,
    JOINCONVERSATIONSTEP,
    ENSURECONVERSATIONSTEP,
    PREPAREMEDIAWITHDELEGATESTEP,
    PREPAREGROUPINVITEWITHDELEGATESTEP,
    ENCRYPTSTEP,
    MCSSENDSTEP
}
